"use strict";
(()=>{
 const app=document.getElementById("app"),status=document.getElementById("status"),refresh=document.getElementById("refresh"),pending=new Map(),stampDrafts=new Map();
 const operations={emesse:"Fatture emesse",estere:"Fatture estere emesse",ricevute:"Fatture ricevute","mancata-consegna":"Mancata consegna",corrispettivi:"Corrispettivi",bolli:"Bolli e prospetto F24"};
 const states={planned:"Piano da avviare",starting:"Avvio in corso",waiting_for_login:"Accesso da completare",running:"Acquisizione in corso",finalizing:"Preparazione dei report",complete:"Acquisizione completa",partial:"Acquisizione parziale",cancelled:"Acquisizione interrotta",failed:"Acquisizione non completata",interrupted:"Worker non più attivo",not_available:"Non disponibile",incomplete:"Da completare",acquired:"Acquisito",downloaded:"Nuovo originale",verified_existing:"Già presente, verificato"};
 let id=0,host={},data,view="plan",busy=false,dirty=false,draft,filter="",onlyErrors=false,timer,startKey,resumeKey;
 const node=(tag,text,cls)=>{const el=document.createElement(tag);if(text!==undefined)el.textContent=text;if(cls)el.className=cls;return el;};
 const say=(text,error=false)=>{status.textContent=text;status.classList.toggle("error",error);};
 function request(method,params){return new Promise((resolve,reject)=>{const number=++id;const timeout=setTimeout(()=>{pending.delete(number);reject(new Error("Il servizio non ha risposto. Aggiorna per leggere lo stato salvato prima di riprovare."));},160000);pending.set(number,{resolve,reject,timeout});window.parent.postMessage({jsonrpc:"2.0",id:number,method,params},"*");});}
 async function call(action,args={}){const result=await request("tools/call",{name:`agenzia_workspace_${action}`,arguments:{workspace_ref:data.workspace_ref,...args}});if(result.isError)throw new Error(result.content?.[0]?.text||"Operazione non riuscita");return result._meta.agenzia;}
 async function run(action){if(busy)return;busy=true;app.setAttribute("aria-busy","true");try{await action();}catch(error){say(error.message,true);}finally{busy=false;app.setAttribute("aria-busy","false");}}
 function button(label,action,cls){const el=node("button",label,cls);el.type="button";el.addEventListener("click",()=>run(action));return el;}
 function field(label,type,value,change){const wrapper=node("label",undefined,"field"),input=node("input");input.type=type;input.value=value||"";input.addEventListener("input",()=>change(input.value));wrapper.append(node("span",label),input);return {wrapper,input};}
 function table(headers,rows){const wrap=node("div",undefined,"table-wrap"),table=node("table"),thead=node("thead"),tr=node("tr"),tbody=node("tbody");headers.forEach(h=>tr.append(node("th",h)));thead.append(tr);for(const values of rows){const row=node("tr");for(const value of values){const td=node("td");if(value instanceof Node)td.append(value);else td.textContent=value??"";row.append(td);}tbody.append(row);}table.append(thead,tbody);wrap.append(table);return wrap;}
 function clientName(vat){return data.plan.clients.find(c=>c.vat_number===vat)?.name||vat;}
 async function save(){if(!dirty)return;data=await call("save",{revision:data.revision,plan:draft});draft=structuredClone(data.plan);dirty=false;startKey=undefined;say("Selezione conservata. L'acquisizione non è ancora avviata.");}
 async function setView(next){if(dirty)await save();view=next;if(data.run_id && next!=="plan")await update(true);else render();}
 function schedule(){clearTimeout(timer);if(["starting","running","waiting_for_login","finalizing"].includes(data?.state))timer=setTimeout(()=>run(()=>update(false)),4000);}
 async function update(force){if(dirty){if(force)await save();else return schedule();}if(!data?.run_id){say("Piano aperto. Conserva la selezione per avviare il lavoro.");return;}const next=await call("status",{run_id:data.run_id,offset:data.offset||0,exceptions_only:onlyErrors});data=next;render();schedule();}
 function render(){app.replaceChildren();refresh.disabled=!data?.workspace_ref;if(!data||data.state==="unbound"){app.append(node("p",data?.message||"Indica a Vera il file clienti e il periodo da acquisire.","empty"));app.setAttribute("aria-busy","false");return;}
  const shell=node("div",undefined,"shell"),rail=node("aside",undefined,"rail"),nav=node("nav"),main=node("main");nav.setAttribute("aria-label","Acquisizione Agenzia");rail.append(node("p","Agenzia","eyebrow"),nav);
  for(const [key,label]of [["plan","Piano"],["run","Avanzamento"],["invoices","Fatture"],["cash","Corrispettivi"],["stamp","Bolli e F24"],["outputs","File e archivio"]]){if(key!=="plan"&&!data.run_id)continue;const item=button(label,()=>setView(key));if(view===key)item.setAttribute("aria-current","page");nav.append(item);}
  shell.append(rail,main);app.append(shell);main.append(node("p","Vera · Fatture e Corrispettivi","eyebrow"));
  if(view==="plan")renderPlan(main);else if(view==="run")renderRun(main);else if(view==="invoices")renderInvoices(main);else if(view==="cash")renderCash(main);else if(view==="stamp")renderStamp(main);else renderOutputs(main);
  app.setAttribute("aria-busy","false");
 }
 function renderPlan(main){draft=structuredClone(data.plan);main.append(node("h1","Scegli cosa acquisire"),node("p","Seleziona clienti, periodo e documenti. Vera apre Chrome per il tuo accesso e conserva gli originali nella cartella scelta.","sub"));const fields=node("div",undefined,"fields");
  for(const [key,label]of [["date_from","Dal"],["date_to","Al"]])fields.append(field(label,"date",draft[key],value=>{draft[key]=value;dirty=true;}).wrapper);main.append(fields);
  const categories=node("fieldset"),choices=node("div",undefined,"choices");categories.append(node("legend","Documenti e riepiloghi"),choices);for(const [key,label]of Object.entries(operations)){const row=node("label",undefined,"choice"),box=node("input");box.type="checkbox";box.checked=draft.operations.includes(key);box.addEventListener("change",()=>{draft.operations=box.checked?[...draft.operations,key]:draft.operations.filter(x=>x!==key);dirty=true;});row.append(box,node("span",label));choices.append(row);}main.append(categories);
  main.append(node("h2","Clienti"));const list=node("div");function clients(){list.replaceChildren();const rows=data.source_clients.filter(c=>`${c.name} ${c.vat_number}`.toLocaleLowerCase().includes(filter.toLocaleLowerCase())).map(c=>{const box=node("input");box.type="checkbox";box.setAttribute("aria-label",`Seleziona ${c.name}`);box.checked=draft.clients.some(x=>x.vat_number===c.vat_number);box.addEventListener("change",()=>{draft.clients=box.checked?[...draft.clients,c]:draft.clients.filter(x=>x.vat_number!==c.vat_number);dirty=true;});return[box,c.name,node("span",c.tax_code,"identifier"),node("span",c.vat_number,"identifier")];});list.append(table(["","Cliente","Codice fiscale","Partita IVA"],rows));}main.append(field("Cerca cliente","search",filter,value=>{filter=value;clients();}).wrapper,list);clients();
  const access=node("details");access.append(node("summary","Modalità di accesso"),node("p",draft.access_mode==="incaricato"?`Incaricato · utenza di lavoro ${draft.work_identity}`:"Delega diretta"),node("p","Per cambiare modalità o utenza di lavoro, chiedi a Vera di preparare un nuovo piano. Password e PIN vanno inseriti soltanto nel portale."));main.append(access);
  const actions=node("div",undefined,"actions");actions.append(button("Conserva selezione",async()=>{await save();render();}));if(!data.run_id)actions.append(button("Avvia acquisizione",async()=>{await save();startKey ||= crypto.randomUUID();data=await call("start",{revision:data.revision,request_id:startKey});view="run";render();schedule();},"primary"));main.append(actions);
  if(data.recent_runs?.length){main.append(node("h2","Esecuzioni conservate"));for(const previous of data.recent_runs)main.append(button(`${previous.started_at} · ${states[previous.state]||previous.state}`,async()=>{data=await call("status",{run_id:previous.run_id});view="run";render();schedule();}));}
  main.append(node("p","I bolli sono rilevati per trimestre intero. Il piano non dispone pagamenti né invii fiscali.","notice"));
 }
 function renderRun(main){main.append(node("h1",states[data.state]||data.state),node("p",`${data.plan.clients.length} clienti · ${data.plan.date_from} — ${data.plan.date_to}`,"sub"));
  if(data.state==="waiting_for_login"){main.append(node("p","Completa l'accesso nella finestra Chrome aperta da Vera. Inserisci lì credenziali, PIN ed eventuale secondo fattore.","notice"),button("Ho completato l'accesso",async()=>{await call("continue",{run_id:data.run_id});say("Accesso confermato. Il worker verifica il portale e prosegue.");schedule();},"primary"));}
  const counts=node("div",undefined,"counts");for(const [key,label]of [["downloaded","nuovi originali"],["verified_existing","già presenti e verificati"],["failed_documents","documenti da recuperare"]]){const p=node("p");p.append(node("strong",String(data[key]||0)),node("span",label));counts.append(p);}main.append(counts);
  if(data.scopes_expected){main.append(node("p",`${data.scopes_complete||0} ambiti completi su ${data.scopes_expected}`));const progress=node("progress");progress.max=data.scopes_expected;progress.value=data.scopes_complete||0;progress.setAttribute("aria-label","Ambiti completati");main.append(progress);}
  if(data.error||data.stop_reason)main.append(node("p",`Da verificare: ${data.error||data.stop_reason}`,"notice"));
  const actions=node("div",undefined,"actions");if(["starting","running","waiting_for_login","finalizing"].includes(data.state))actions.append(button("Interrompi",async()=>{await call("cancel",{run_id:data.run_id});say("Interruzione richiesta. Gli originali già acquisiti restano conservati.");}));else actions.append(button("Riprendi e verifica il periodo",async()=>{resumeKey ||= crypto.randomUUID();data=await call("resume",{run_id:data.run_id,request_id:resumeKey});resumeKey=undefined;render();schedule();},"primary"));main.append(actions);
  main.append(table(["Cliente","Operazione","Periodo","Esito","Righe portale"],(data.scopes||[]).map(s=>[clientName(s.client),operations[s.operation],`${s.year} · T${s.quarter}`,states[s.status]||s.status,s.portal_count??"—"])));
 }
 function renderInvoices(main){main.append(node("h1","Originali e anomalie"));const choice=node("label",undefined,"choice"),check=node("input");check.type="checkbox";check.checked=onlyErrors;check.addEventListener("change",()=>run(async()=>{onlyErrors=check.checked;data.offset=0;await update(true);}));choice.append(check,node("span","Mostra soltanto i documenti da recuperare"));main.append(choice);
  main.append(table(["Cliente","Categoria","Periodo","Esito","Da verificare"],(data.invoice_results||[]).map(row=>[clientName(row.client),operations[row.operation],`${row.year} · T${row.quarter}`,states[row.status]||row.status,row.error||""])));
  const actions=node("div",undefined,"actions"),offset=data.offset||0;if(offset)actions.append(button("Precedenti",async()=>{data.offset=Math.max(0,offset-40);await update(true);}));if(offset+40<(data.invoice_total||0))actions.append(button("Successive",async()=>{data.offset=offset+40;await update(true);}));main.append(actions,node("p",`${data.invoice_total||0} risultati. Il registro CSV conserva i percorsi e gli hash degli originali. Le firme P7M non sono validate.`,"sub"));
 }
 function renderCash(main){main.append(node("h1","Corrispettivi"),node("p","Il riepilogo Excel conserva gli invii per ogni tipo di dispositivo e i totali per data di rilevazione e per mese. Le righe con importi o identità mancanti restano segnalate.","sub"));const scopes=(data.scopes||[]).filter(s=>s.operation==="corrispettivi");main.append(table(["Cliente","Periodo","Invii portale","Esito"],scopes.map(s=>[clientName(s.client),`${s.year} · T${s.quarter}`,s.portal_count??"—",states[s.status]||s.status])));main.append(node("h2","Righe da riesaminare"),table(["Cliente","Dispositivo","Riga","Segnalazioni"],(data.cash_review_issues||[]).map(i=>[clientName(i.client),i.device,i.row,i.issues.join(", ")])));}
 function download(file){const bytes=Uint8Array.from(atob(file.base64),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:file.mime})),link=node("a");link.href=url;link.download=file.name;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),20000);}
 function renderStamp(main){main.append(node("h1","Bolli e prospetto F24"),node("p","L'importo calcolato dal portale non è necessariamente il residuo da versare. Scegli i trimestri da includere e indica importo residuo, scadenza e motivo del riesame. Vera prepara un prospetto PDF, senza inviare o pagare.","sub"));
  const selected=[];const rows=(data.stamp_duty||[]).map(event=>{const evidence=event.evidence;if(evidence.status!=="acquired")return[clientName(event.client),`${event.year} · T${event.quarter}`,"—","Non disponibile","","","",""];const key=`${data.run_id}:${event.client}:${event.year}:${event.quarter}`;if(!stampDrafts.has(key))stampDrafts.set(key,{selected:false,item:{client:event.client,year:event.year,quarter:event.quarter,amount:"",due_date:"",note:""}});const local=stampDrafts.get(key),item=local.item,check=node("input");check.type="checkbox";check.checked=local.selected;if(local.selected)selected.push(item);check.setAttribute("aria-label",`Includi ${clientName(event.client)} ${event.year} trimestre ${event.quarter}`);const amount=field("Residuo EUR","number",item.amount,v=>item.amount=v),due=field("Scadenza","date",item.due_date,v=>item.due_date=v),note=field("Motivo del riesame","text",item.note,v=>item.note=v);amount.input.step="0.01";amount.input.min="0.01";amount.input.className="amount";note.input.className="review-note";check.addEventListener("change",()=>{local.selected=check.checked;const i=selected.indexOf(item);if(check.checked)selected.push(item);else if(i>=0)selected.splice(i,1);});return[clientName(event.client),`${event.year} · T${event.quarter}`,`${evidence.amount} EUR`,evidence.payment_status||"Stato non indicato",check,amount.wrapper,due.wrapper,note.wrapper];});
  main.append(table(["Cliente","Trimestre","Importo portale","Pagamento","Includi","Residuo","Scadenza","Riesame"],rows));if(rows.length)main.append(button("Genera prospetto dai valori riesaminati",async()=>{if(!selected.length)throw new Error("Seleziona almeno un trimestre e completa i valori riesaminati.");const result=await call("f24",{run_id:data.run_id,revision:data.report_revision,review:{schema_version:"vera-agenzia-f24/v1",reviewed:true,items:selected}});download(result.download);say("Prospetto conservato e scaricato. Nessun pagamento disposto.");},"primary"));
 }
 function renderOutputs(main){main.append(node("h1","File e archivio"),node("p","I risultati sono conservati nella cartella scelta. Il worker verifica gli originali già presenti prima di riutilizzarli.","sub"));for(const [name,label]of [["riepilogo.xlsx","Riepilogo Excel"],["fatture.csv","Registro fatture CSV"],["model_data_report.md","Rapporto sui dati al modello"]]){const row=node("div",undefined,"file");row.append(node("span",label),button("Scarica",async()=>download((await call("download",{run_id:data.run_id,name})).download)));main.append(row);}if(data.plan.clients.some(c=>c.archive_client_id))main.append(button("Importa gli originali in Studio Archive",async()=>{const result=await call("archive",{run_id:data.run_id});say(`${result.originals} originali registrati negli incarichi selezionati.`);}));else main.append(node("p","Per registrare gli originali in Studio Archive, collega con Vera i clienti e gli incarichi esatti. Il collegamento non viene dedotto dal nome.","notice"));
  const detail=node("details");detail.append(node("summary","Dettagli del lavoro"),node("p",data.run_directory||"","technical"),node("p",`Esecuzione: ${data.run_id}`,"technical"));main.append(detail);
  if(host.hostCapabilities?.message?.text)main.append(button("Riesamina i risultati con Vera",async()=>{const text=`Riesamina l'acquisizione Agenzia ${data.run_id} nella cartella ${data.run_directory}. Verifica prima status e report.json; distingui originali acquisiti, anomalie e dati mancanti. Non considerare i bolli come residui da pagare. Registra nel rapporto dati soltanto le letture effettive.`;const response=await request("ui/message",{role:"user",content:[{type:"text",text}]});if(response?.isError)throw new Error("La chat non ha confermato la ricezione.");say("Richiesta consegnata alla chat per il riesame.");}));
 }
 refresh.addEventListener("click",()=>run(()=>update(true)));
 window.addEventListener("message",event=>{if(event.source!==window.parent)return;const message=event.data;if(!message||message.jsonrpc!=="2.0")return;if(pending.has(message.id)){const entry=pending.get(message.id);clearTimeout(entry.timeout);pending.delete(message.id);message.error?entry.reject(new Error(message.error.message)):entry.resolve(message.result);return;}if(message.method==="ui/notifications/tool-result"&&message.params?._meta?.agenzia){data=message.params._meta.agenzia;view=data.run_id?"run":"plan";render();schedule();}if(message.method==="ui/notifications/host-context-changed")host={...host,hostContext:message.params};});
 window.addEventListener("beforeunload",event=>{if(dirty){event.preventDefault();event.returnValue="";}});
 (async()=>{try{host=await request("ui/initialize",{protocolVersion:"2026-01-26",appInfo:{name:"Vera · Acquisizione Agenzia",version:"1.0.0"},appCapabilities:{availableDisplayModes:["inline","fullscreen"]}});window.parent.postMessage({jsonrpc:"2.0",method:"ui/notifications/initialized"},"*");if(!data){const result=await request("tools/call",{name:"agenzia_workspace_open",arguments:{}});if(!data){data=result._meta.agenzia;render();}}}catch(error){say(error.message,true);app.setAttribute("aria-busy","false");}})();
})();
