from __future__ import annotations

import json
from typing import Dict, List
import logging

import polars as pl

from modules.check_entries.constants import (
    LANGUAGE_ALIASES,
    LANGUAGE_NAMES,
    LOCALIZED_STRINGS,
)
from modules.check_entries.utils import flatten_mismatches
from modules.llm.batch_runner import run_step_text
from src.io_utils import get_schema_and_column_names


def generate_audit_note(
    llm_wrapper,
    result_df: pl.DataFrame,
    lang: str = "eng",
) -> str:
    """Create an audit note summarising journal entry checks.

    Parameters
    ----------
    llm_wrapper: object
        Wrapper used to call the LLM.
    result_df: pl.DataFrame
        DataFrame returned by ``run_automatic_check``.
    lang: str, default "eng"
        Language code or name used for localization.

    Returns
    -------
    str
        Narrative audit note generated by the LLM.
    """

    lang_code = LANGUAGE_ALIASES.get(lang.lower(), lang.lower())
    lang_name = LANGUAGE_NAMES.get(lang_code, lang_code)
    translations = LOCALIZED_STRINGS.get(lang_code, LOCALIZED_STRINGS["eng"])

    mismatches_df = result_df.filter(pl.col("check_status") == "mismatch")
    columns, _ = get_schema_and_column_names(mismatches_df)
    explanation_col = "explanation"
    mismatch_type_col = "mismatch_type"
    if "mismatches" in columns:
        mismatches_df, mapping = flatten_mismatches(mismatches_df, "mismatches")
        explanation_col = mapping.get("explanation", explanation_col)
        mismatch_type_col = mapping.get("mismatch_type", mismatch_type_col)
        current_cols, _ = get_schema_and_column_names(mismatches_df)
        drop_cols = [
            col
            for col in ("explanation", "mismatch_type")
            if col in current_cols and mapping.get(col) != col
        ]
        if drop_cols:
            mismatches_df = mismatches_df.drop(drop_cols)
        flat_cols, _ = get_schema_and_column_names(mismatches_df)
        if mismatch_type_col in flat_cols:
            categorized = mismatches_df.with_columns(
                pl.col(mismatch_type_col)
                .cast(pl.Utf8)
                .replace(
                    {
                        "amount_mismatch": "amount",
                        "date_mismatch": "date",
                        "beneficiary_mismatch": "beneficiary",
                        "timing_difference": "timing_difference",
                        "missing_transaction": "missing_transaction",
                        "duplicate_transaction": "duplicate_transaction",
                        "fraud": "fraud",
                    }
                )
                .fill_null("other")
                .alias("mismatch_type")
            )
            if mismatch_type_col != "mismatch_type":
                categorized = categorized.drop(mismatch_type_col)
        else:
            patterns = {
                "amount": translations["amount_mismatch"].split(":")[0],
                "date": translations["date_mismatch"].split(":")[0],
                "beneficiary": translations["beneficiary_mismatch"].split(":")[0],
                "timing_difference": translations.get(
                    "timing_difference", "Timing difference"
                ).split(":")[0],
                "missing_transaction": translations.get(
                    "missing_transaction", "Missing transaction"
                ).split(":")[0],
                "duplicate_transaction": translations.get(
                    "duplicate_transaction", "Duplicate transaction"
                ).split(":")[0],
                "fraud": translations.get("fraud", "Fraud").split(":")[0],
            }
            categorized = mismatches_df.with_columns(
                pl.when(pl.col(explanation_col).str.starts_with(patterns["amount"]))
                .then(pl.lit("amount"))
                .when(pl.col(explanation_col).str.starts_with(patterns["date"]))
                .then(pl.lit("date"))
                .when(pl.col(explanation_col).str.starts_with(patterns["beneficiary"]))
                .then(pl.lit("beneficiary"))
                .when(
                    pl.col(explanation_col).str.starts_with(
                        patterns["timing_difference"]
                    )
                )
                .then(pl.lit("timing_difference"))
                .when(
                    pl.col(explanation_col).str.starts_with(
                        patterns["missing_transaction"]
                    )
                )
                .then(pl.lit("missing_transaction"))
                .when(
                    pl.col(explanation_col).str.starts_with(
                        patterns["duplicate_transaction"]
                    )
                )
                .then(pl.lit("duplicate_transaction"))
                .when(pl.col(explanation_col).str.starts_with(patterns["fraud"]))
                .then(pl.lit("fraud"))
                .otherwise(pl.lit("other"))
                .alias("mismatch_type")
            )
    else:
        patterns = {
            "amount": translations["amount_mismatch"].split(":")[0],
            "date": translations["date_mismatch"].split(":")[0],
            "beneficiary": translations["beneficiary_mismatch"].split(":")[0],
            "timing_difference": translations.get(
                "timing_difference", "Timing difference"
            ).split(":")[0],
            "missing_transaction": translations.get(
                "missing_transaction", "Missing transaction"
            ).split(":")[0],
            "duplicate_transaction": translations.get(
                "duplicate_transaction", "Duplicate transaction"
            ).split(":")[0],
            "fraud": translations.get("fraud", "Fraud").split(":")[0],
        }
        categorized = mismatches_df.with_columns(
            pl.when(pl.col(explanation_col).str.starts_with(patterns["amount"]))
            .then(pl.lit("amount"))
            .when(pl.col(explanation_col).str.starts_with(patterns["date"]))
            .then(pl.lit("date"))
            .when(pl.col(explanation_col).str.starts_with(patterns["beneficiary"]))
            .then(pl.lit("beneficiary"))
            .when(
                pl.col(explanation_col).str.starts_with(patterns["timing_difference"])
            )
            .then(pl.lit("timing_difference"))
            .when(
                pl.col(explanation_col).str.starts_with(patterns["missing_transaction"])
            )
            .then(pl.lit("missing_transaction"))
            .when(
                pl.col(explanation_col).str.starts_with(
                    patterns["duplicate_transaction"]
                )
            )
            .then(pl.lit("duplicate_transaction"))
            .when(pl.col(explanation_col).str.starts_with(patterns["fraud"]))
            .then(pl.lit("fraud"))
            .otherwise(pl.lit("other"))
            .alias("mismatch_type")
        )

    mismatch_details: Dict[str, List[str]] = {
        "amount": [],
        "date": [],
        "beneficiary": [],
        "timing_difference": [],
        "missing_transaction": [],
        "duplicate_transaction": [],
        "fraud": [],
    }
    uncategorized: List[str] = []
    for row in categorized.select(["mismatch_type", explanation_col]).to_dicts():
        if row["mismatch_type"] in mismatch_details:
            mismatch_details[row["mismatch_type"]].append(row[explanation_col])
        else:
            uncategorized.append(row[explanation_col])
    counts = {k: len(v) for k, v in mismatch_details.items()}

    payload = {
        "totals": counts,
        "details": mismatch_details,
        "uncategorized": uncategorized,
    }
    prompt_user = (
        "You are an accounting assistant. Using the data below, "
        "write an audit note with the following sections: Scope, Procedures, "
        "Findings, Recommendations/Next Steps. The Findings section should "
        "list each mismatch category with its count and bullet descriptions, "
        "followed by any uncategorized discrepancies listed individually. "
        "Do not create an 'Other' category.\n"
        f"Data: {json.dumps(payload)}"
    )
    prompt_system = f"Respond in {lang_name}."
    return run_step_text(
        llm_wrapper, "quickRewriteQuery", prompt_system, prompt_user
    )[0]
