"""French presentation text, independent of the case's governing jurisdiction."""

from __future__ import annotations

__all__ = ["FRENCH"]

FRENCH = {
    "Period": "Période",
    "Comparison": "Comparaison",
    "Print current view": "Imprimer la vue actuelle",
    "client": "Client",
    "Report sections": "Sections du rapport",
    "Income statement": "Compte de résultat",
    "Cash": "Trésorerie",
    "Sources": "Sources",
    "Current planning question": "Question de cette itération",
    "What we learned": "Ce que nous avons appris",
    "Decision in this round": "Décision de cette itération",
    "Next test or action": "Prochaine vérification ou action",
    "When to revisit": "Quand réexaminer le plan",
    "Planning history and input changes": "Historique et modifications des données",
    "Financing assessment": "Évaluation du financement",
    "Bank debt": "Crédit bancaire",
    "Venture equity": "Capital-risque",
    "Provider not yet selected": "Financeur à identifier",
    "Financing conclusion pending evidence and review": "Conclusion sur le financement en attente de justificatifs et de révision",
    "Recommendation pending evidence and review": "Recommandation en attente de justificatifs et de révision",
    "Explore financing": "Examiner le financement",
    "Prepare the request": "Préparer la demande",
    "Revise the request": "Revoir la demande",
    "Requested financing is not suitable": "Le financement demandé n’est pas adapté",
    "Business credibility and demand": "Crédibilité de l’activité et demande",
    "Use of funds and proposed loan terms": "Emploi des fonds et conditions du prêt",
    "Repayment from operating cash": "Remboursement par la trésorerie d’exploitation",
    "Repayment under adverse conditions": "Remboursement en conditions défavorables",
    "Borrower, existing debt and sponsor contribution": "Emprunteur, dette existante et apport des associés",
    "Guarantees and collateral": "Garanties et sûretés",
    "Lender requirements and missing evidence": "Exigences du prêteur et justificatifs manquants",
    "Market opportunity and customer evidence": "Marché et éléments probants sur les clients",
    "Competition and defensible advantage": "Concurrence et avantage défendable",
    "Traction and repeatable growth": "Résultats commerciaux et croissance reproductible",
    "Team and ability to execute": "Équipe et capacité de réalisation",
    "Use of funds and funded milestones": "Emploi des fonds et étapes financées",
    "Cash runway and further funding": "Autonomie de trésorerie et financements ultérieurs",
    "Ownership, dilution and investor return": "Actionnariat, dilution et rendement pour l’investisseur",
    "Investor fit and missing evidence": "Adéquation avec l’investisseur et justificatifs manquants",
    "The forecast does not yet cover the stated repayment or funding milestone.": "Les prévisions ne couvrent pas encore l’échéance de remboursement ou l’étape financée déclarée.",
    "This assessment does not establish lender or investor approval.": "Cette évaluation ne vaut pas accord du prêteur ou de l’investisseur.",
    "Business plan": "Plan d’affaires",
    "Audience": "Destinataires",
    "internal": "Usage interne",
    "Recommendation": "Recommandation",
    "Business assessment withheld": "Évaluation de l’activité suspendue",
    "Correct the conflicting calculations and supporting claims, then review the recommendation again. The submitted assessment is retained in the case record; it is not presented as a conclusion.": "Corriger les calculs et les affirmations contradictoires, puis réexaminer la recommandation. L’évaluation reçue reste au dossier sans être présentée comme une conclusion.",
    "Proceed": "Poursuivre",
    "Test": "Tester",
    "Redesign": "Revoir la conception",
    "Stop": "Arrêter",
    "What this judgment depends on": "Conditions de cette appréciation",
    "What would change the recommendation": "Éléments susceptibles de modifier la recommandation",
    "The business and its customers": "L’activité et ses clients",
    "Demand and route to market": "Demande et canaux de vente",
    "How the business would operate": "Organisation de l’activité",
    "Prices, costs and sustainable sales": "Prix, coûts et chiffre d’affaires soutenable",
    "Cash, investment and financing": "Trésorerie, investissement et financement",
    "Alternatives worth considering": "Solutions alternatives à examiner",
    "What to do next": "Prochaines actions et responsabilités",
    "Material uncertainties and limitations": "Incertitudes et limites significatives",
    "Provisional assessment. Material evidence or review remains open; this is not a finalized business plan.": "Évaluation provisoire : des éléments probants ou des vérifications restent à obtenir. Le plan d’affaires n’est pas finalisé.",
    "Basis and review": "Fondement et révision",
    "Provisional interpretation — professional review pending": "Interprétation provisoire ; révision professionnelle en attente",
    "Reviewed interpretation": "Interprétation révisée",
    "Sources and calculation references": "Sources et références des calculs",
    "Source": "Source",
    "Reference": "Référence",
    "Value": "Valeur",
    "Claim / use": "Affirmation / utilisation",
    "Location": "Page ou cellules",
    "Not specified": "Non précisé",
    "Action": "Action",
    "Owner": "Responsable",
    "When": "Échéance",
    "Undated operating period": "Période d’activité non datée",
    "Evidence / decision criterion": "Preuve / critère de décision",
    "Supporting evidence, calculations and review record": "Justificatifs, calculs et dossier de révision",
    "Chart data and calculation lineage": "Données du graphique et références des calculs",
    "Month": "Mois",
    "Series": "Série",
    "Calculation ID": "Référence de calcul",
    "Before new financing": "Avant les nouveaux financements",
    "After scheduled financing": "Après les financements prévus",
    "EBITDA by scenario": "EBITDA par scénario",
    "Monthly cash": "Trésorerie mensuelle",
    "Calculation": "Calcul",
    "Source observation": "Donnée de la source",
    "Sum": "Somme",
    "Ratio": "Ratio",
    "Draft for discussion": "Projet pour discussion",
    "Page": "Page",
    "Variance = comparison − baseline. Percent uses the baseline; n/a for zero or negative baselines. Colors follow each row's convention; gray when unspecified.": "Écart = comparaison − référence. Pourcentage calculé sur la référence ; n/d si elle est nulle ou négative. Couleurs selon la convention de chaque ligne ; gris si non précisée.",
    "This conclusion is withheld pending correction of its supporting claims.": "Cette conclusion est suspendue jusqu’à correction des affirmations qui la fondent.",
    "Explicit evidence gap": "Élément probant manquant",
    "Forecast horizon not yet established": "Horizon prévisionnel à établir",
    "Currency not established": "Devise à établir",
    "startup": "Création d’entreprise",
    "established": "Entreprise existante",
    "Business assessment incomplete": "Évaluation de l’activité incomplète",
    "The available calculations and notes do not yet constitute a business plan. A recommendation and the business questions still need to be addressed.": "Les calculs et notes disponibles ne constituent pas encore un plan d’affaires. La recommandation et les questions relatives à l’activité restent à traiter.",
    "Validation status": "État de validation",
    "Checks establish internal consistency and file identity, not whether a business is viable.": "Les contrôles vérifient la cohérence interne et l’identité des fichiers ; ils ne démontrent pas la viabilité de l’activité.",
    "Unresolved matters": "Points non résolus",
    "Cross-source figure comparison": "Comparaison des chiffres entre sources",
}
