from __future__ import annotations

"""Outreach helpers for small, reviewable email batches."""

from modules.outreach.batch import (
    DAILY_COUNTRY_LIMIT,
    DAILY_LANGUAGE_LIMIT,
    OutreachLead,
    OutreachMessage,
    PreparedOutreachEmail,
    build_italian_commercialisti_message,
    daily_country_usage,
    daily_language_usage,
    daily_quota_usage,
    email_hash,
    load_blocked_hashes,
    load_leads_csv,
    normalise_email,
    normalise_language,
    normalise_locale,
    normalise_quota_key,
    parse_outreach_template,
    prepare_outreach_batch,
    prepare_template_outreach_batch,
    quota_daily_limit,
    record_outreach_batch_sent,
    scrub_raw_emails,
    write_prepared_batch_jsonl,
)
from modules.outreach.lead_bank import (
    DEFAULT_REQUEST_TIMEOUT_SECONDS,
    DiscoveredLeadBatch,
    build_lead_bank_from_sources,
    discover_leads_from_html,
    discover_leads_from_source,
    extract_email_addresses,
    extract_pdf_text,
    fetch_html_with_playwright,
    fetch_static_html,
    fetch_static_source_text,
    load_source_urls,
)
from modules.outreach.queue import (
    QUEUE_FIELDNAMES,
    QueueBatchResult,
    append_leads_to_queue,
    eligible_queue_status,
    prepare_queue_outreach_batch,
    record_queue_batch_sent,
)

__all__ = [
    "DAILY_LANGUAGE_LIMIT",
    "DAILY_COUNTRY_LIMIT",
    "OutreachLead",
    "OutreachMessage",
    "PreparedOutreachEmail",
    "DEFAULT_REQUEST_TIMEOUT_SECONDS",
    "DiscoveredLeadBatch",
    "QUEUE_FIELDNAMES",
    "QueueBatchResult",
    "append_leads_to_queue",
    "build_lead_bank_from_sources",
    "build_italian_commercialisti_message",
    "daily_country_usage",
    "daily_language_usage",
    "daily_quota_usage",
    "email_hash",
    "eligible_queue_status",
    "discover_leads_from_html",
    "discover_leads_from_source",
    "extract_email_addresses",
    "extract_pdf_text",
    "fetch_html_with_playwright",
    "fetch_static_html",
    "fetch_static_source_text",
    "load_blocked_hashes",
    "load_leads_csv",
    "load_source_urls",
    "normalise_email",
    "normalise_language",
    "normalise_locale",
    "normalise_quota_key",
    "parse_outreach_template",
    "prepare_outreach_batch",
    "prepare_queue_outreach_batch",
    "prepare_template_outreach_batch",
    "quota_daily_limit",
    "record_queue_batch_sent",
    "record_outreach_batch_sent",
    "scrub_raw_emails",
    "write_prepared_batch_jsonl",
]
