"""Fixed display labels for the native advisory evidence map."""

from __future__ import annotations

__all__ = ["lineage_labels"]

_LANGUAGES = ("en", "it", "fr", "de", "es")
_COPY = {
    "title": (
        "Advisory evidence map",
        "Mappa delle fonti e delle conclusioni",
        "Carte des sources et des conclusions",
        "Quellen- und Aussagenübersicht",
        "Mapa de fuentes y conclusiones",
    ),
    "intro": (
        "This is a readable view of the structured evidence and claim registers. It records declared provenance; it does not prove that a claim is correct.",
        "Questa vista collega fonti e affermazioni registrate. Documenta i riferimenti dichiarati; non dimostra da sola la correttezza delle conclusioni.",
        "Cette vue relie les sources et les affirmations enregistrées. Elle documente les références déclarées sans démontrer à elle seule la justesse des conclusions.",
        "Diese Übersicht verbindet erfasste Quellen und Aussagen. Sie dokumentiert die angegebenen Bezüge, belegt aber für sich allein nicht die Richtigkeit der Schlussfolgerungen.",
        "Esta vista relaciona las fuentes y las afirmaciones registradas. Documenta las referencias declaradas, sin demostrar por sí sola que las conclusiones sean correctas.",
    ),
    "evidence": (
        "Evidence",
        "Fonti ed evidenze",
        "Sources et éléments probants",
        "Quellen und Belege",
        "Fuentes y evidencias",
    ),
    "claims": (
        "Claims",
        "Affermazioni e conclusioni",
        "Affirmations et conclusions",
        "Aussagen und Schlussfolgerungen",
        "Afirmaciones y conclusiones",
    ),
    "no_evidence": (
        "No evidence receipts recorded.",
        "Nessuna evidenza registrata.",
        "Aucun élément probant enregistré.",
        "Keine Belege erfasst.",
        "No hay evidencias registradas.",
    ),
    "no_claims": (
        "No claims recorded.",
        "Nessuna affermazione registrata.",
        "Aucune affirmation enregistrée.",
        "Keine Aussagen erfasst.",
        "No hay afirmaciones registradas.",
    ),
    "none_recorded": (
        "None recorded.",
        "Nessuna voce registrata.",
        "Aucun élément enregistré.",
        "Keine Einträge erfasst.",
        "No hay elementos registrados.",
    ),
    "not_recorded": (
        "not recorded",
        "non registrato",
        "non renseigné",
        "nicht erfasst",
        "no registrado",
    ),
    "observation_label": (
        "Observation",
        "Osservazione",
        "Observation",
        "Beobachtung",
        "Observación",
    ),
    "source": ("Source", "Fonte", "Source", "Quelle", "Fuente"),
    "source_files": (
        "Source files",
        "File di origine",
        "Fichiers sources",
        "Quelldateien",
        "Archivos de origen",
    ),
    "capture": ("Capture", "Acquisizione", "Acquisition", "Erfassung", "Captura"),
    "verification": (
        "Verification",
        "Verifica",
        "Vérification",
        "Prüfung",
        "Comprobación",
    ),
    "scope": ("Scope", "Perimetro", "Périmètre", "Umfang", "Alcance"),
    "limitations": ("Limitations", "Limiti", "Limites", "Grenzen", "Límites"),
    "statement": ("Statement", "Affermazione", "Affirmation", "Aussage", "Afirmación"),
    "decision_use": (
        "Decision use",
        "Ruolo nella decisione",
        "Rôle dans la décision",
        "Rolle für die Entscheidung",
        "Papel en la decisión",
    ),
    "depends_on": (
        "Depends on",
        "Dipende da",
        "Dépend de",
        "Abhängig von",
        "Depende de",
    ),
    "derivation": (
        "Derivation",
        "Ragionamento o derivazione",
        "Raisonnement ou dérivation",
        "Begründung oder Herleitung",
        "Razonamiento o derivación",
    ),
    "decision_implication": (
        "Decision implication",
        "Conseguenza per la decisione",
        "Conséquence pour la décision",
        "Folge für die Entscheidung",
        "Consecuencia para la decisión",
    ),
    "missing_evidence": (
        "Evidence that would change the position",
        "Evidenze che cambierebbero la valutazione",
        "Éléments qui changeraient l'évaluation",
        "Belege, die die Bewertung ändern würden",
        "Evidencias que cambiarían la evaluación",
    ),
    "uncertainty": (
        "Uncertainty",
        "Incertezze",
        "Incertitudes",
        "Unsicherheiten",
        "Incertidumbres",
    ),
    "state": ("State", "Stato", "État", "Status", "Estado"),
    "relationships": (
        "Evidence relationships",
        "Collegamenti alle evidenze",
        "Liens avec les éléments probants",
        "Bezüge zu den Belegen",
        "Relaciones con las evidencias",
    ),
    "analysis": ("Analysis", "Analisi", "Analyse", "Analyse", "Análisis"),
    "proves": (
        "Proves",
        "Che cosa dimostra",
        "Ce qui est démontré",
        "Was belegt wird",
        "Qué demuestra",
    ),
    "does_not_prove": (
        "Does not prove",
        "Che cosa non dimostra",
        "Ce qui n'est pas démontré",
        "Was nicht belegt wird",
        "Qué no demuestra",
    ),
    "directness": (
        "Directness",
        "Direttezza del supporto",
        "Caractère direct du soutien",
        "Unmittelbarkeit des Belegs",
        "Carácter directo del respaldo",
    ),
    "reliability": (
        "Reliability",
        "Attendibilità",
        "Fiabilité",
        "Verlässlichkeit",
        "Fiabilidad",
    ),
    "corroboration": (
        "Corroboration",
        "Riscontri",
        "Corroboration",
        "Bestätigung",
        "Corroboración",
    ),
    "bias": (
        "Bias or limitation",
        "Possibili distorsioni o limiti",
        "Biais possibles ou limites",
        "Mögliche Verzerrungen oder Grenzen",
        "Posibles sesgos o límites",
    ),
    "appearances": (
        "Output appearances",
        "Presenza nei documenti prodotti",
        "Présence dans les livrables",
        "Verwendung in Ergebnisdokumenten",
        "Apariciones en los documentos generados",
    ),
    "supersedes": (
        "Replaces earlier claim",
        "Sostituisce l'affermazione precedente",
        "Remplace l'affirmation précédente",
        "Ersetzt die frühere Aussage",
        "Sustituye la afirmación anterior",
    ),
    "local_document": (
        "local document",
        "documento locale",
        "document local",
        "lokales Dokument",
        "documento local",
    ),
    "web_capture": (
        "web capture",
        "pagina web acquisita",
        "capture de page web",
        "erfasste Webseite",
        "captura web",
    ),
    "interview_transcript": (
        "interview transcript",
        "trascrizione di intervista",
        "transcription d'entretien",
        "Interviewtranskript",
        "transcripción de entrevista",
    ),
    "dataset": (
        "dataset",
        "insieme di dati",
        "jeu de données",
        "Datensatz",
        "conjunto de datos",
    ),
    "calculation_run": (
        "calculation run",
        "esecuzione di calcolo",
        "exécution de calcul",
        "Berechnungslauf",
        "ejecución de cálculo",
    ),
    "management_assertion": (
        "management assertion",
        "dichiarazione della direzione",
        "déclaration de la direction",
        "Aussage der Geschäftsleitung",
        "declaración de la dirección",
    ),
    "advisor_judgement": (
        "advisor judgement",
        "giudizio del consulente",
        "jugement du conseil",
        "Beraterurteil",
        "juicio del asesor",
    ),
    "prior_clara_output": (
        "earlier Clara output",
        "precedente risultato di Clara",
        "résultat antérieur de Clara",
        "früheres Clara-Ergebnis",
        "resultado anterior de Clara",
    ),
    "other": ("other", "altro", "autre", "sonstiges", "otro"),
    "captured": ("captured", "acquisita", "acquis", "erfasst", "capturada"),
    "assertion_only": (
        "assertion only",
        "sola dichiarazione",
        "déclaration seule",
        "nur Aussage",
        "solo declaración",
    ),
    "unavailable": (
        "unavailable",
        "non disponibile",
        "indisponible",
        "nicht verfügbar",
        "no disponible",
    ),
    "not_checked": (
        "not checked",
        "non verificata",
        "non vérifié",
        "nicht geprüft",
        "no comprobada",
    ),
    "identity_verified": (
        "identity verified",
        "identità verificata",
        "identité vérifiée",
        "Identität geprüft",
        "identidad comprobada",
    ),
    "rechecked_unchanged": (
        "rechecked, unchanged",
        "riverificata, invariata",
        "revérifié, inchangé",
        "erneut geprüft, unverändert",
        "revisada, sin cambios",
    ),
    "rechecked_changed": (
        "rechecked, changed",
        "riverificata, modificata",
        "revérifié, modifié",
        "erneut geprüft, verändert",
        "revisada, modificada",
    ),
    "supports": ("supports", "sostiene", "étaye", "stützt", "respalda"),
    "weakens": ("weakens", "indebolisce", "affaiblit", "schwächt", "debilita"),
    "contradicts": (
        "contradicts",
        "contraddice",
        "contredit",
        "widerspricht",
        "contradice",
    ),
    "creates": ("creates", "genera", "crée", "begründet", "genera"),
    "context": ("context", "contesto", "contexte", "Kontext", "contexto"),
    "direct": ("direct", "diretto", "direct", "direkt", "directo"),
    "indirect": ("indirect", "indiretto", "indirect", "indirekt", "indirecto"),
    "contextual": (
        "contextual",
        "di contesto",
        "contextuel",
        "kontextbezogen",
        "contextual",
    ),
    "unknown": (
        "unknown",
        "non determinato",
        "indéterminé",
        "unbestimmt",
        "no determinado",
    ),
    "high": ("high", "alta", "élevée", "hoch", "alta"),
    "medium": ("medium", "media", "moyenne", "mittel", "media"),
    "low": ("low", "bassa", "faible", "niedrig", "baja"),
    "corroborated": (
        "corroborated",
        "con riscontri",
        "corroboré",
        "bestätigt",
        "corroborada",
    ),
    "single_source": (
        "single source",
        "unica fonte",
        "source unique",
        "einzelne Quelle",
        "fuente única",
    ),
    "contradicted": (
        "contradicted",
        "contraddetto",
        "contredit",
        "widersprochen",
        "contradicha",
    ),
    "none": ("none", "nessuna", "aucune", "keine", "ninguna"),
    "all_of": (
        "all required",
        "tutte necessarie",
        "toutes nécessaires",
        "alle erforderlich",
        "todas necesarias",
    ),
    "any_of": (
        "at least one required",
        "almeno una necessaria",
        "au moins une nécessaire",
        "mindestens eine erforderlich",
        "al menos una necesaria",
    ),
    "calculation": ("calculation", "calcolo", "calcul", "Berechnung", "cálculo"),
    "reasoning": (
        "reasoning",
        "ragionamento",
        "raisonnement",
        "Begründung",
        "razonamiento",
    ),
    "aggregation": (
        "aggregation",
        "aggregazione",
        "agrégation",
        "Aggregation",
        "agregación",
    ),
    "quotation": ("quotation", "citazione", "citation", "Zitat", "cita"),
    "observation": (
        "observation",
        "osservazione",
        "observation",
        "Beobachtung",
        "observación",
    ),
    "assertion": ("assertion", "affermazione", "affirmation", "Aussage", "afirmación"),
    "inference": ("inference", "inferenza", "inférence", "Ableitung", "inferencia"),
    "conclusion": (
        "conclusion",
        "conclusione",
        "conclusion",
        "Schlussfolgerung",
        "conclusión",
    ),
    "recommendation": (
        "recommendation",
        "raccomandazione",
        "recommandation",
        "Empfehlung",
        "recomendación",
    ),
    "decision_condition": (
        "decision condition",
        "condizione per la decisione",
        "condition de décision",
        "Entscheidungsbedingung",
        "condición para la decisión",
    ),
    "supporting": (
        "supporting",
        "di supporto",
        "en soutien",
        "unterstützend",
        "de apoyo",
    ),
    "active": ("active", "attuale", "actuel", "aktuell", "actual"),
    "superseded": ("superseded", "sostituita", "remplacé", "ersetzt", "sustituida"),
    "withdrawn": ("withdrawn", "ritirata", "retiré", "zurückgezogen", "retirada"),
}


def lineage_labels(language: str) -> dict[str, str]:
    """Select fixed wording without changing source prose or recorded judgement."""
    index = _LANGUAGES.index(language) if language in _LANGUAGES else 0
    return {key: values[index] for key, values in _COPY.items()}
