"use strict";
/* App-only inspection and explicit batch checks; no portal or posting executor. */
globalThis.VeraBrowser=Object.freeze({create(api){
  const {node,button,call,say,confirmation}=api;let context,currentWork,timer,queue=Promise.resolve();const urls=new Set();let controlId=0;
  const translations={
  "it": {
    "Identificativo della voce": "Identificativo della voce",
    "Documento": "Documento",
    "Azione dichiarata": "Azione dichiarata",
    "Motivazione": "Motivazione",
    "Esito dichiarato": "Esito dichiarato",
    "Stato dichiarato": "Stato dichiarato",
    "Trattamento proposto": "Trattamento proposto",
    "Risultato effettivo": "Risultato effettivo",
    "Evidenze e dati della fattura": "Evidenze e dati della fattura",
    "Questione aperta": "Questione aperta",
    "Riferimento della registrazione": "Riferimento della registrazione",
    "Registrazione rettificata": "Registrazione rettificata",
    "Dato descritto": "Dato descritto",
    "Valore": "Valore",
    "Fonte": "Fonte",
    "Voce controllata": "Voce controllata",
    "Decisione espressa": "Decisione espressa",
    "Nota del professionista": "Nota del professionista",
    "Data del controllo": "Data del controllo",
    "Contenuto della revisione": "Contenuto della revisione",
    "Numero di revisione": "Numero di revisione",
    "Impronta della revisione precedente": "Impronta della revisione precedente",
    "Impronta del record": "Impronta del record",
    "Versione del formato": "Versione del formato",
    "Identificativo del lotto": "Identificativo del lotto",
    "Titolo": "Titolo",
    "Perimetro": "Perimetro",
    "Numero previsto di voci": "Numero previsto di voci",
    "Voci del lotto": "Voci del lotto",
    "Controlli conservati": "Controlli conservati",
    "Descrizione": "Descrizione",
    "Processo": "Processo",
    "Nome": "Nome",
    "Obiettivo": "Obiettivo",
    "Tentativi": "Tentativi",
    "Identificativo del tentativo": "Identificativo del tentativo",
    "Identificativo del processo": "Identificativo del processo",
    "Disponibile nell’ambiente qualificato": "Disponibile nell’ambiente qualificato",
    "Qualificazioni conservate": "Qualificazioni conservate",
    "Rilasci": "Rilasci",
    "Versioni": "Versioni",
    "Limiti": "Limiti",
    "Risultato": "Risultato",
    "Data di creazione": "Data di creazione",
    "Ultimo aggiornamento": "Ultimo aggiornamento",
    "Da elaborare": "Da elaborare",
    "Completata": "Completata",
    "Da decidere": "Da decidere",
    "Non riuscita": "Non riuscita",
    "Esito da verificare": "Esito da verificare",
    "Nessuna voce conservata.": "Nessuna voce conservata.",
    "Nessun campo conservato.": "Nessun campo conservato.",
    "Non indicato": "Non indicato",
    "Campo vuoto": "Campo vuoto",
    "Quali dati arrivano al modello": "Quali dati arrivano al modello",
    "Campi del controllo conservati. Nessuna decisione ancora registrata.": "Campi del controllo conservati. Nessuna decisione ancora registrata.",
    "Campi non conservati: ": "Campi non conservati: ",
    "← Clienti e incarichi": "← Clienti e incarichi",
    "Automazione web": "Automazione web",
    "Consulta lo sviluppo dei processi e controlla i risultati dei lotti conservati.": "Consulta lo sviluppo dei processi e controlla i risultati dei lotti conservati.",
    "Lotto · proposta, risultato e fonti": "Lotto · proposta, risultato e fonti",
    "Processo · tentativi e collaudo": "Processo · tentativi e collaudo",
    "Apri evidenze": "Apri evidenze",
    "Nessun processo o lotto collegato a questo operatore. Riprendi il lavoro specialistico nella chat; il pannello mostra soltanto record esistenti collegati dal runtime.": "Nessun processo o lotto collegato a questo operatore. Riprendi il lavoro specialistico nella chat; il pannello mostra soltanto record esistenti collegati dal runtime.",
    "Scarica ": "Scarica ",
    "← Processi e lotti": "← Processi e lotti",
    "Vera · Automazione web": "Vera · Automazione web",
    "Qualificato nell’ambiente registrato: il prossimo avvio verifica di nuovo il contratto.": "Qualificato nell’ambiente registrato: il prossimo avvio verifica di nuovo il contratto.",
    "Collaudo dell’ambiente da completare.": "Collaudo dell’ambiente da completare.",
    "Per insegnare o eseguire il processo usa la chat e il workflow browser esistente. L’apertura di queste evidenze non avvia una sessione Chrome.": "Per insegnare o eseguire il processo usa la chat e il workflow browser esistente. L’apertura di queste evidenze non avvia una sessione Chrome.",
    "Perimetro, versioni, rilasci e qualificazione": "Perimetro, versioni, rilasci e qualificazione",
    "Tutti i tentativi, limiti ed evidenze tecniche": "Tutti i tentativi, limiti ed evidenze tecniche",
    "Revisione ": "Revisione ",
    " · popolazione prevista: ": " · popolazione prevista: ",
    "Non ancora definita": "Non ancora definita",
    "Il risultato riportato e il controllo del professionista sono distinti. Una richiesta di correzione conserva la registrazione originale.": "Il risultato riportato e il controllo del professionista sono distinti. Una richiesta di correzione conserva la registrazione originale.",
    "Tutte le revisioni e i controlli conservati": "Tutte le revisioni e i controlli conservati",
    "Scarica rapporto verificato": "Scarica rapporto verificato",
    "Esamina e controlla voce": "Esamina e controlla voce",
    "Esamina e controlla ": "Esamina e controlla ",
    "← Lotto": "← Lotto",
    "Vera · controllo del lotto": "Vera · controllo del lotto",
    "Voce completa: proposta, risultato effettivo, motivazione e fonti": "Voce completa: proposta, risultato effettivo, motivazione e fonti",
    "Tutti i controlli precedenti su questa voce": "Tutti i controlli precedenti su questa voce",
    "Una scrittura precedente è incerta. Recupera il lotto nel workflow specialistico prima di ripetere il controllo.": "Una scrittura precedente è incerta. Recupera il lotto nel workflow specialistico prima di ripetere il controllo.",
    "Campi precedenti da confrontare": "Campi precedenti da confrontare",
    "Scarto soltanto i campi privati precedenti; conservo fatture e controlli": "Scarto soltanto i campi privati precedenti; conservo fatture e controlli",
    "Scarta campi privati": "Scarta campi privati",
    "Conferma lo scarto dei soli campi privati.": "Conferma lo scarto dei soli campi privati.",
    "Decisione espressa sul controllo": "Decisione espressa sul controllo",
    "Scegli la decisione": "Scegli la decisione",
    "Controllata": "Controllata",
    "Correzione richiesta": "Correzione richiesta",
    "Nota effettiva del professionista": "Nota effettiva del professionista",
    "Indica la decisione e una nota sul controllo svolto. Puoi conservare campi incompleti; per registrare il controllo servono entrambi e una nuova conferma.": "Indica la decisione e una nota sul controllo svolto. Puoi conservare campi incompleti; per registrare il controllo servono entrambi e una nuova conferma.",
    "Ho controllato questa voce completa e confermo la decisione espressa": "Ho controllato questa voce completa e confermo la decisione espressa",
    "Conserva campi incompleti": "Conserva campi incompleti",
    "Registra controllo": "Registra controllo",
    "Indica la decisione e la nota effettive, poi conferma la voce corrente.": "Indica la decisione e la nota effettive, poi conferma la voce corrente.",
    "Controllo conservato. Nessuna correzione contabile eseguita.": "Controllo conservato. Nessuna correzione contabile eseguita.",
    "Lingua del pannello": "Lingua del pannello",
    "Lingua del pannello non supportata.": "Lingua del pannello non supportata.",
    "Questo pannello usa route riservate all’app. Legge i processi collegati, i tentativi e i controlli dei lotti, senza chiamare il modello o navigare sui portali. Le voci del lotto possono contenere identità delle fatture, descrizioni, importi, trattamento contabile e IVA proposto ed effettivo, fonti e riferimenti di registrazione. La chat specialistica può leggere i dati autorizzati necessari al lavoro; non sono anonimizzati automaticamente. I valori degli output dichiarati artifact_only e i documenti scaricati restano esclusi dal riepilogo tecnico dei processi. Il runtime browser conserva hash e conteggi; questi non dimostrano quali dati il provider abbia ricevuto. Password, cookie, sessioni e catture grezze non appartengono al pannello. Un controllo qui registra soltanto la decisione espressa: non contabilizza, corregge sul portale, invia una richiesta di sviluppo o chiude l’Archivio.": "Questo pannello usa route riservate all’app. Legge i processi collegati, i tentativi e i controlli dei lotti, senza chiamare il modello o navigare sui portali. Le voci del lotto possono contenere identità delle fatture, descrizioni, importi, trattamento contabile e IVA proposto ed effettivo, fonti e riferimenti di registrazione. La chat specialistica può leggere i dati autorizzati necessari al lavoro; non sono anonimizzati automaticamente. I valori degli output dichiarati artifact_only e i documenti scaricati restano esclusi dal riepilogo tecnico dei processi. Il runtime browser conserva hash e conteggi; questi non dimostrano quali dati il provider abbia ricevuto. Password, cookie, sessioni e catture grezze non appartengono al pannello. Un controllo qui registra soltanto la decisione espressa: non contabilizza, corregge sul portale, invia una richiesta di sviluppo o chiude l’Archivio."
  },
  "en": {
    "Identificativo della voce": "Entry identifier",
    "Documento": "Document",
    "Azione dichiarata": "Declared action",
    "Motivazione": "Reason",
    "Esito dichiarato": "Declared outcome",
    "Stato dichiarato": "Declared status",
    "Trattamento proposto": "Proposed treatment",
    "Risultato effettivo": "Actual result",
    "Evidenze e dati della fattura": "Evidence and invoice data",
    "Questione aperta": "Open question",
    "Riferimento della registrazione": "Posting reference",
    "Registrazione rettificata": "Posting being corrected",
    "Dato descritto": "Described field",
    "Valore": "Value",
    "Fonte": "Source",
    "Voce controllata": "Reviewed entry",
    "Decisione espressa": "Expressed decision",
    "Nota del professionista": "Professional’s note",
    "Data del controllo": "Review date",
    "Contenuto della revisione": "Revision contents",
    "Numero di revisione": "Revision number",
    "Impronta della revisione precedente": "Previous revision fingerprint",
    "Impronta del record": "Record fingerprint",
    "Versione del formato": "Format version",
    "Identificativo del lotto": "Batch identifier",
    "Titolo": "Title",
    "Perimetro": "Scope",
    "Numero previsto di voci": "Expected entry count",
    "Voci del lotto": "Batch entries",
    "Controlli conservati": "Saved reviews",
    "Descrizione": "Description",
    "Processo": "Process",
    "Nome": "Name",
    "Obiettivo": "Objective",
    "Tentativi": "Attempts",
    "Identificativo del tentativo": "Attempt identifier",
    "Identificativo del processo": "Process identifier",
    "Disponibile nell’ambiente qualificato": "Available in the qualified environment",
    "Qualificazioni conservate": "Saved qualifications",
    "Rilasci": "Releases",
    "Versioni": "Versions",
    "Limiti": "Limitations",
    "Risultato": "Result",
    "Data di creazione": "Creation date",
    "Ultimo aggiornamento": "Last updated",
    "Da elaborare": "Pending",
    "Completata": "Completed",
    "Da decidere": "Decision needed",
    "Non riuscita": "Failed",
    "Esito da verificare": "Outcome needs verification",
    "Nessuna voce conservata.": "No saved entries.",
    "Nessun campo conservato.": "No saved fields.",
    "Non indicato": "Not specified",
    "Campo vuoto": "Empty field",
    "Quali dati arrivano al modello": "What data reaches the model",
    "Campi del controllo conservati. Nessuna decisione ancora registrata.": "Review fields saved. No decision recorded yet.",
    "Campi non conservati: ": "Fields not saved: ",
    "← Clienti e incarichi": "← Clients and engagements",
    "Automazione web": "Browser automation",
    "Consulta lo sviluppo dei processi e controlla i risultati dei lotti conservati.": "Inspect process development and review saved batch results.",
    "Lotto · proposta, risultato e fonti": "Batch · proposal, result and sources",
    "Processo · tentativi e collaudo": "Process · attempts and qualification",
    "Apri evidenze": "Open evidence",
    "Nessun processo o lotto collegato a questo operatore. Riprendi il lavoro specialistico nella chat; il pannello mostra soltanto record esistenti collegati dal runtime.": "No process or batch is linked to this operator. Resume the specialist work in chat; the panel shows only existing records linked by the runtime.",
    "Scarica ": "Download ",
    "← Processi e lotti": "← Processes and batches",
    "Vera · Automazione web": "Vera · Browser automation",
    "Qualificato nell’ambiente registrato: il prossimo avvio verifica di nuovo il contratto.": "Qualified in the recorded environment: the next launch rechecks the contract.",
    "Collaudo dell’ambiente da completare.": "Environment qualification still needs completion.",
    "Per insegnare o eseguire il processo usa la chat e il workflow browser esistente. L’apertura di queste evidenze non avvia una sessione Chrome.": "Use chat and the existing browser workflow to teach or execute the process. Opening this evidence does not start a Chrome session.",
    "Perimetro, versioni, rilasci e qualificazione": "Scope, versions, releases and qualification",
    "Tutti i tentativi, limiti ed evidenze tecniche": "All attempts, limitations and technical evidence",
    "Revisione ": "Revision ",
    " · popolazione prevista: ": " · expected population: ",
    "Non ancora definita": "Not defined yet",
    "Il risultato riportato e il controllo del professionista sono distinti. Una richiesta di correzione conserva la registrazione originale.": "The reported result and the professional’s review are separate. A correction request preserves the original posting.",
    "Tutte le revisioni e i controlli conservati": "All saved revisions and reviews",
    "Scarica rapporto verificato": "Download verified report",
    "Esamina e controlla voce": "Inspect and review entry",
    "Esamina e controlla ": "Inspect and review ",
    "← Lotto": "← Batch",
    "Vera · controllo del lotto": "Vera · batch review",
    "Voce completa: proposta, risultato effettivo, motivazione e fonti": "Complete entry: proposal, actual result, reason and sources",
    "Tutti i controlli precedenti su questa voce": "All previous reviews of this entry",
    "Una scrittura precedente è incerta. Recupera il lotto nel workflow specialistico prima di ripetere il controllo.": "A previous write is uncertain. Recover the batch through the specialist workflow before repeating the review.",
    "Campi precedenti da confrontare": "Previous fields to compare",
    "Scarto soltanto i campi privati precedenti; conservo fatture e controlli": "I discard only the previous private fields; invoices and reviews stay saved",
    "Scarta campi privati": "Discard private fields",
    "Conferma lo scarto dei soli campi privati.": "Confirm discarding only the private fields.",
    "Decisione espressa sul controllo": "Expressed review decision",
    "Scegli la decisione": "Choose a decision",
    "Controllata": "Reviewed",
    "Correzione richiesta": "Correction requested",
    "Nota effettiva del professionista": "Professional’s actual note",
    "Indica la decisione e una nota sul controllo svolto. Puoi conservare campi incompleti; per registrare il controllo servono entrambi e una nuova conferma.": "Enter your decision and a note about the review performed. You can save incomplete fields; recording the review requires both fields and a fresh confirmation.",
    "Ho controllato questa voce completa e confermo la decisione espressa": "I reviewed this complete entry and confirm my expressed decision",
    "Conserva campi incompleti": "Save incomplete fields",
    "Registra controllo": "Record review",
    "Indica la decisione e la nota effettive, poi conferma la voce corrente.": "Enter the actual decision and note, then confirm the current entry.",
    "Controllo conservato. Nessuna correzione contabile eseguita.": "Review saved. No accounting correction was executed.",
    "Lingua del pannello": "Panel language",
    "Lingua del pannello non supportata.": "Unsupported panel language.",
    "Questo pannello usa route riservate all’app. Legge i processi collegati, i tentativi e i controlli dei lotti, senza chiamare il modello o navigare sui portali. Le voci del lotto possono contenere identità delle fatture, descrizioni, importi, trattamento contabile e IVA proposto ed effettivo, fonti e riferimenti di registrazione. La chat specialistica può leggere i dati autorizzati necessari al lavoro; non sono anonimizzati automaticamente. I valori degli output dichiarati artifact_only e i documenti scaricati restano esclusi dal riepilogo tecnico dei processi. Il runtime browser conserva hash e conteggi; questi non dimostrano quali dati il provider abbia ricevuto. Password, cookie, sessioni e catture grezze non appartengono al pannello. Un controllo qui registra soltanto la decisione espressa: non contabilizza, corregge sul portale, invia una richiesta di sviluppo o chiude l’Archivio.": "This panel uses app-only routes. It reads linked processes, attempts and batch reviews without calling the model or browsing portals. Batch entries may contain invoice identities, descriptions, amounts, proposed and actual accounting and VAT treatment, sources and posting references. The specialist chat may read authorized data needed for the work; it is not automatically anonymized. Values of outputs declared artifact_only and downloaded documents are excluded from the technical process summary. The browser runtime records hashes and counts; these do not establish which data the provider received. Passwords, cookies, sessions and raw captures do not belong in the panel. A review here records only the expressed decision: it does not post accounting entries, correct a portal record, submit a development request or close the Archive."
  },
  "fr": {
    "Identificativo della voce": "Identifiant de l’entrée",
    "Documento": "Document",
    "Azione dichiarata": "Action déclarée",
    "Motivazione": "Motif",
    "Esito dichiarato": "Résultat déclaré",
    "Stato dichiarato": "État déclaré",
    "Trattamento proposto": "Traitement proposé",
    "Risultato effettivo": "Résultat effectif",
    "Evidenze e dati della fattura": "Éléments probants et données de la facture",
    "Questione aperta": "Question ouverte",
    "Riferimento della registrazione": "Référence de l’écriture",
    "Registrazione rettificata": "Écriture faisant l’objet de la correction",
    "Dato descritto": "Donnée décrite",
    "Valore": "Valeur",
    "Fonte": "Source",
    "Voce controllata": "Entrée contrôlée",
    "Decisione espressa": "Décision exprimée",
    "Nota del professionista": "Note du professionnel",
    "Data del controllo": "Date du contrôle",
    "Contenuto della revisione": "Contenu de la révision",
    "Numero di revisione": "Numéro de révision",
    "Impronta della revisione precedente": "Empreinte de la révision précédente",
    "Impronta del record": "Empreinte de l’enregistrement",
    "Versione del formato": "Version du format",
    "Identificativo del lotto": "Identifiant du lot",
    "Titolo": "Titre",
    "Perimetro": "Périmètre",
    "Numero previsto di voci": "Nombre d’entrées prévu",
    "Voci del lotto": "Entrées du lot",
    "Controlli conservati": "Contrôles conservés",
    "Descrizione": "Description",
    "Processo": "Processus",
    "Nome": "Nom",
    "Obiettivo": "Objectif",
    "Tentativi": "Tentatives",
    "Identificativo del tentativo": "Identifiant de la tentative",
    "Identificativo del processo": "Identifiant du processus",
    "Disponibile nell’ambiente qualificato": "Disponible dans l’environnement qualifié",
    "Qualificazioni conservate": "Qualifications conservées",
    "Rilasci": "Versions publiées",
    "Versioni": "Versions",
    "Limiti": "Limites",
    "Risultato": "Résultat",
    "Data di creazione": "Date de création",
    "Ultimo aggiornamento": "Dernière mise à jour",
    "Da elaborare": "À traiter",
    "Completata": "Terminée",
    "Da decidere": "Décision à prendre",
    "Non riuscita": "Échec",
    "Esito da verificare": "Résultat à vérifier",
    "Nessuna voce conservata.": "Aucune entrée conservée.",
    "Nessun campo conservato.": "Aucun champ conservé.",
    "Non indicato": "Non indiqué",
    "Campo vuoto": "Champ vide",
    "Quali dati arrivano al modello": "Quelles données parviennent au modèle",
    "Campi del controllo conservati. Nessuna decisione ancora registrata.": "Champs du contrôle conservés. Aucune décision enregistrée pour le moment.",
    "Campi non conservati: ": "Champs non conservés : ",
    "← Clienti e incarichi": "← Clients et missions",
    "Automazione web": "Automatisation web",
    "Consulta lo sviluppo dei processi e controlla i risultati dei lotti conservati.": "Consultez le développement des processus et contrôlez les résultats des lots conservés.",
    "Lotto · proposta, risultato e fonti": "Lot · proposition, résultat et sources",
    "Processo · tentativi e collaudo": "Processus · tentatives et qualification",
    "Apri evidenze": "Ouvrir les éléments probants",
    "Nessun processo o lotto collegato a questo operatore. Riprendi il lavoro specialistico nella chat; il pannello mostra soltanto record esistenti collegati dal runtime.": "Aucun processus ni lot n’est associé à cet opérateur. Reprenez le travail spécialisé dans la conversation ; le panneau affiche uniquement les enregistrements existants associés par le runtime.",
    "Scarica ": "Télécharger ",
    "← Processi e lotti": "← Processus et lots",
    "Vera · Automazione web": "Vera · Automatisation web",
    "Qualificato nell’ambiente registrato: il prossimo avvio verifica di nuovo il contratto.": "Qualifié dans l’environnement enregistré : le prochain démarrage vérifie à nouveau le contrat.",
    "Collaudo dell’ambiente da completare.": "La qualification de l’environnement reste à terminer.",
    "Per insegnare o eseguire il processo usa la chat e il workflow browser esistente. L’apertura di queste evidenze non avvia una sessione Chrome.": "Utilisez la conversation et le workflow navigateur existant pour enseigner ou exécuter le processus. L’ouverture de ces éléments ne démarre pas de session Chrome.",
    "Perimetro, versioni, rilasci e qualificazione": "Périmètre, versions, publications et qualification",
    "Tutti i tentativi, limiti ed evidenze tecniche": "Toutes les tentatives, limites et preuves techniques",
    "Revisione ": "Révision ",
    " · popolazione prevista: ": " · population prévue : ",
    "Non ancora definita": "Pas encore définie",
    "Il risultato riportato e il controllo del professionista sono distinti. Una richiesta di correzione conserva la registrazione originale.": "Le résultat déclaré et le contrôle du professionnel sont distincts. Une demande de correction conserve l’écriture d’origine.",
    "Tutte le revisioni e i controlli conservati": "Toutes les révisions et tous les contrôles conservés",
    "Scarica rapporto verificato": "Télécharger le rapport vérifié",
    "Esamina e controlla voce": "Examiner et contrôler l’entrée",
    "Esamina e controlla ": "Examiner et contrôler ",
    "← Lotto": "← Lot",
    "Vera · controllo del lotto": "Vera · contrôle du lot",
    "Voce completa: proposta, risultato effettivo, motivazione e fonti": "Entrée complète : proposition, résultat effectif, motif et sources",
    "Tutti i controlli precedenti su questa voce": "Tous les contrôles antérieurs de cette entrée",
    "Una scrittura precedente è incerta. Recupera il lotto nel workflow specialistico prima di ripetere il controllo.": "Une écriture précédente est incertaine. Récupérez le lot dans le workflow spécialisé avant de répéter le contrôle.",
    "Campi precedenti da confrontare": "Champs antérieurs à comparer",
    "Scarto soltanto i campi privati precedenti; conservo fatture e controlli": "Je supprime uniquement les champs privés antérieurs ; les factures et contrôles restent conservés",
    "Scarta campi privati": "Supprimer les champs privés",
    "Conferma lo scarto dei soli campi privati.": "Confirmez la suppression des seuls champs privés.",
    "Decisione espressa sul controllo": "Décision exprimée sur le contrôle",
    "Scegli la decisione": "Choisissez une décision",
    "Controllata": "Contrôlée",
    "Correzione richiesta": "Correction demandée",
    "Nota effettiva del professionista": "Note effective du professionnel",
    "Indica la decisione e una nota sul controllo svolto. Puoi conservare campi incompleti; per registrare il controllo servono entrambi e una nuova conferma.": "Indiquez votre décision et une note sur le contrôle effectué. Vous pouvez conserver des champs incomplets ; l’enregistrement du contrôle exige les deux champs et une nouvelle confirmation.",
    "Ho controllato questa voce completa e confermo la decisione espressa": "J’ai contrôlé cette entrée complète et confirme la décision exprimée",
    "Conserva campi incompleti": "Conserver les champs incomplets",
    "Registra controllo": "Enregistrer le contrôle",
    "Indica la decisione e la nota effettive, poi conferma la voce corrente.": "Indiquez la décision et la note effectives, puis confirmez l’entrée actuelle.",
    "Controllo conservato. Nessuna correzione contabile eseguita.": "Contrôle conservé. Aucune correction comptable effectuée.",
    "Lingua del pannello": "Langue du panneau",
    "Lingua del pannello non supportata.": "Langue du panneau non prise en charge.",
    "Questo pannello usa route riservate all’app. Legge i processi collegati, i tentativi e i controlli dei lotti, senza chiamare il modello o navigare sui portali. Le voci del lotto possono contenere identità delle fatture, descrizioni, importi, trattamento contabile e IVA proposto ed effettivo, fonti e riferimenti di registrazione. La chat specialistica può leggere i dati autorizzati necessari al lavoro; non sono anonimizzati automaticamente. I valori degli output dichiarati artifact_only e i documenti scaricati restano esclusi dal riepilogo tecnico dei processi. Il runtime browser conserva hash e conteggi; questi non dimostrano quali dati il provider abbia ricevuto. Password, cookie, sessioni e catture grezze non appartengono al pannello. Un controllo qui registra soltanto la decisione espressa: non contabilizza, corregge sul portale, invia una richiesta di sviluppo o chiude l’Archivio.": "Ce panneau utilise des routes réservées à l’application. Il lit les processus associés, les tentatives et les contrôles des lots, sans appeler le modèle ni naviguer sur les portails. Les entrées du lot peuvent contenir l’identité des factures, des descriptions, des montants, le traitement comptable et de TVA proposé et effectif, les sources et les références des écritures. La conversation spécialisée peut lire les données autorisées nécessaires au travail ; elles ne sont pas automatiquement anonymisées. Les valeurs des sorties déclarées artifact_only et les documents téléchargés sont exclus du résumé technique des processus. Le runtime du navigateur conserve des empreintes et des décomptes ; ceux-ci ne prouvent pas quelles données le fournisseur a reçues. Les mots de passe, cookies, sessions et captures brutes n’appartiennent pas au panneau. Un contrôle ici conserve uniquement la décision exprimée : il ne comptabilise pas d’écriture, ne corrige pas de données sur le portail, n’envoie pas de demande de développement et ne clôture pas l’Archive."
  },
  "de": {
    "Identificativo della voce": "Kennung des Eintrags",
    "Documento": "Dokument",
    "Azione dichiarata": "Angegebene Aktion",
    "Motivazione": "Begründung",
    "Esito dichiarato": "Angegebenes Ergebnis",
    "Stato dichiarato": "Angegebener Status",
    "Trattamento proposto": "Vorgeschlagene Behandlung",
    "Risultato effettivo": "Tatsächliches Ergebnis",
    "Evidenze e dati della fattura": "Nachweise und Rechnungsdaten",
    "Questione aperta": "Offene Frage",
    "Riferimento della registrazione": "Buchungsreferenz",
    "Registrazione rettificata": "Zu berichtigende Buchung",
    "Dato descritto": "Beschriebenes Feld",
    "Valore": "Wert",
    "Fonte": "Quelle",
    "Voce controllata": "Geprüfter Eintrag",
    "Decisione espressa": "Erklärte Entscheidung",
    "Nota del professionista": "Anmerkung der Fachperson",
    "Data del controllo": "Prüfdatum",
    "Contenuto della revisione": "Inhalt der Revision",
    "Numero di revisione": "Revisionsnummer",
    "Impronta della revisione precedente": "Prüfsumme der vorherigen Revision",
    "Impronta del record": "Prüfsumme des Datensatzes",
    "Versione del formato": "Formatversion",
    "Identificativo del lotto": "Kennung des Stapels",
    "Titolo": "Titel",
    "Perimetro": "Umfang",
    "Numero previsto di voci": "Erwartete Anzahl der Einträge",
    "Voci del lotto": "Einträge des Stapels",
    "Controlli conservati": "Gespeicherte Prüfungen",
    "Descrizione": "Beschreibung",
    "Processo": "Prozess",
    "Nome": "Name",
    "Obiettivo": "Ziel",
    "Tentativi": "Versuche",
    "Identificativo del tentativo": "Kennung des Versuchs",
    "Identificativo del processo": "Prozesskennung",
    "Disponibile nell’ambiente qualificato": "In der qualifizierten Umgebung verfügbar",
    "Qualificazioni conservate": "Gespeicherte Qualifizierungen",
    "Rilasci": "Veröffentlichungen",
    "Versioni": "Versionen",
    "Limiti": "Einschränkungen",
    "Risultato": "Ergebnis",
    "Data di creazione": "Erstellungsdatum",
    "Ultimo aggiornamento": "Letzte Aktualisierung",
    "Da elaborare": "Zu bearbeiten",
    "Completata": "Abgeschlossen",
    "Da decidere": "Entscheidung erforderlich",
    "Non riuscita": "Fehlgeschlagen",
    "Esito da verificare": "Ergebnis zu prüfen",
    "Nessuna voce conservata.": "Keine gespeicherten Einträge.",
    "Nessun campo conservato.": "Keine gespeicherten Felder.",
    "Non indicato": "Nicht angegeben",
    "Campo vuoto": "Leeres Feld",
    "Quali dati arrivano al modello": "Welche Daten gelangen zum Modell",
    "Campi del controllo conservati. Nessuna decisione ancora registrata.": "Prüffelder gespeichert. Noch keine Entscheidung erfasst.",
    "Campi non conservati: ": "Felder nicht gespeichert: ",
    "← Clienti e incarichi": "← Mandanten und Aufträge",
    "Automazione web": "Browser-Automatisierung",
    "Consulta lo sviluppo dei processi e controlla i risultati dei lotti conservati.": "Prüfen Sie die Prozessentwicklung und die gespeicherten Ergebnisse der Stapel.",
    "Lotto · proposta, risultato e fonti": "Stapel · Vorschlag, Ergebnis und Quellen",
    "Processo · tentativi e collaudo": "Prozess · Versuche und Qualifizierung",
    "Apri evidenze": "Nachweise öffnen",
    "Nessun processo o lotto collegato a questo operatore. Riprendi il lavoro specialistico nella chat; il pannello mostra soltanto record esistenti collegati dal runtime.": "Diesem Bediener ist kein Prozess oder Stapel zugeordnet. Setzen Sie die Facharbeit im Chat fort; das Panel zeigt nur vorhandene Datensätze, die der Runtime zugeordnet sind.",
    "Scarica ": "Herunterladen: ",
    "← Processi e lotti": "← Prozesse und Stapel",
    "Vera · Automazione web": "Vera · Browser-Automatisierung",
    "Qualificato nell’ambiente registrato: il prossimo avvio verifica di nuovo il contratto.": "In der erfassten Umgebung qualifiziert: Beim nächsten Start wird der Vertrag erneut geprüft.",
    "Collaudo dell’ambiente da completare.": "Die Qualifizierung der Umgebung ist noch abzuschließen.",
    "Per insegnare o eseguire il processo usa la chat e il workflow browser esistente. L’apertura di queste evidenze non avvia una sessione Chrome.": "Nutzen Sie den Chat und den vorhandenen Browser-Workflow, um den Prozess anzulernen oder auszuführen. Das Öffnen dieser Nachweise startet keine Chrome-Sitzung.",
    "Perimetro, versioni, rilasci e qualificazione": "Umfang, Versionen, Veröffentlichungen und Qualifizierung",
    "Tutti i tentativi, limiti ed evidenze tecniche": "Alle Versuche, Einschränkungen und technischen Nachweise",
    "Revisione ": "Revision ",
    " · popolazione prevista: ": " · erwarteter Umfang: ",
    "Non ancora definita": "Noch nicht festgelegt",
    "Il risultato riportato e il controllo del professionista sono distinti. Una richiesta di correzione conserva la registrazione originale.": "Das angegebene Ergebnis und die Prüfung durch die Fachperson sind getrennt. Ein Berichtigungswunsch erhält die ursprüngliche Buchung.",
    "Tutte le revisioni e i controlli conservati": "Alle gespeicherten Revisionen und Prüfungen",
    "Scarica rapporto verificato": "Geprüften Bericht herunterladen",
    "Esamina e controlla voce": "Eintrag ansehen und prüfen",
    "Esamina e controlla ": "Ansehen und prüfen: ",
    "← Lotto": "← Stapel",
    "Vera · controllo del lotto": "Vera · Stapelprüfung",
    "Voce completa: proposta, risultato effettivo, motivazione e fonti": "Vollständiger Eintrag: Vorschlag, tatsächliches Ergebnis, Begründung und Quellen",
    "Tutti i controlli precedenti su questa voce": "Alle bisherigen Prüfungen dieses Eintrags",
    "Una scrittura precedente è incerta. Recupera il lotto nel workflow specialistico prima di ripetere il controllo.": "Ein vorheriger Schreibvorgang ist ungewiss. Stellen Sie den Stapel im Fachworkflow wieder her, bevor Sie die Prüfung wiederholen.",
    "Campi precedenti da confrontare": "Vorherige Felder zum Vergleich",
    "Scarto soltanto i campi privati precedenti; conservo fatture e controlli": "Ich verwerfe nur die bisherigen privaten Felder; Rechnungen und Prüfungen bleiben gespeichert",
    "Scarta campi privati": "Private Felder verwerfen",
    "Conferma lo scarto dei soli campi privati.": "Bestätigen Sie das Verwerfen nur der privaten Felder.",
    "Decisione espressa sul controllo": "Erklärte Prüfentscheidung",
    "Scegli la decisione": "Entscheidung auswählen",
    "Controllata": "Geprüft",
    "Correzione richiesta": "Berichtigung angefordert",
    "Nota effettiva del professionista": "Tatsächliche Anmerkung der Fachperson",
    "Indica la decisione e una nota sul controllo svolto. Puoi conservare campi incompleti; per registrare il controllo servono entrambi e una nuova conferma.": "Geben Sie Ihre Entscheidung und eine Anmerkung zur durchgeführten Prüfung ein. Unvollständige Felder können gespeichert werden; zum Erfassen der Prüfung sind beide Felder und eine neue Bestätigung erforderlich.",
    "Ho controllato questa voce completa e confermo la decisione espressa": "Ich habe diesen vollständigen Eintrag geprüft und bestätige meine erklärte Entscheidung",
    "Conserva campi incompleti": "Unvollständige Felder speichern",
    "Registra controllo": "Prüfung erfassen",
    "Indica la decisione e la nota effettive, poi conferma la voce corrente.": "Geben Sie die tatsächliche Entscheidung und Anmerkung ein und bestätigen Sie dann den aktuellen Eintrag.",
    "Controllo conservato. Nessuna correzione contabile eseguita.": "Prüfung gespeichert. Keine buchhalterische Berichtigung ausgeführt.",
    "Lingua del pannello": "Sprache des Panels",
    "Lingua del pannello non supportata.": "Nicht unterstützte Panelsprache.",
    "Questo pannello usa route riservate all’app. Legge i processi collegati, i tentativi e i controlli dei lotti, senza chiamare il modello o navigare sui portali. Le voci del lotto possono contenere identità delle fatture, descrizioni, importi, trattamento contabile e IVA proposto ed effettivo, fonti e riferimenti di registrazione. La chat specialistica può leggere i dati autorizzati necessari al lavoro; non sono anonimizzati automaticamente. I valori degli output dichiarati artifact_only e i documenti scaricati restano esclusi dal riepilogo tecnico dei processi. Il runtime browser conserva hash e conteggi; questi non dimostrano quali dati il provider abbia ricevuto. Password, cookie, sessioni e catture grezze non appartengono al pannello. Un controllo qui registra soltanto la decisione espressa: non contabilizza, corregge sul portale, invia una richiesta di sviluppo o chiude l’Archivio.": "Dieses Panel nutzt ausschließlich App-Routen. Es liest zugeordnete Prozesse, Versuche und Stapelprüfungen, ohne das Modell aufzurufen oder Portale zu öffnen. Stapeleinträge können Rechnungskennungen, Beschreibungen, Beträge, die vorgeschlagene und tatsächliche buchhalterische und umsatzsteuerliche Behandlung, Quellen und Buchungsreferenzen enthalten. Der Fachchat kann die für die Arbeit erforderlichen autorisierten Daten lesen; sie werden nicht automatisch anonymisiert. Werte von Ausgaben mit der Kennzeichnung artifact_only und heruntergeladene Dokumente sind vom technischen Prozessüberblick ausgeschlossen. Die Browser-Runtime speichert Prüfsummen und Anzahlen; diese belegen nicht, welche Daten der Anbieter erhalten hat. Passwörter, Cookies, Sitzungen und Rohaufnahmen gehören nicht in das Panel. Eine Prüfung hier erfasst nur die erklärte Entscheidung: Sie führt keine Buchung aus, berichtigt keine Portaldaten, übermittelt keinen Entwicklungsauftrag und schließt das Archiv nicht ab."
  },
  "es": {
    "Identificativo della voce": "Identificador de la entrada",
    "Documento": "Documento",
    "Azione dichiarata": "Acción declarada",
    "Motivazione": "Motivo",
    "Esito dichiarato": "Resultado declarado",
    "Stato dichiarato": "Estado declarado",
    "Trattamento proposto": "Tratamiento propuesto",
    "Risultato effettivo": "Resultado efectivo",
    "Evidenze e dati della fattura": "Evidencias y datos de la factura",
    "Questione aperta": "Cuestión abierta",
    "Riferimento della registrazione": "Referencia del asiento",
    "Registrazione rettificata": "Asiento que se rectifica",
    "Dato descritto": "Dato descrito",
    "Valore": "Valor",
    "Fonte": "Fuente",
    "Voce controllata": "Entrada revisada",
    "Decisione espressa": "Decisión expresada",
    "Nota del professionista": "Nota del profesional",
    "Data del controllo": "Fecha de revisión",
    "Contenuto della revisione": "Contenido de la revisión",
    "Numero di revisione": "Número de revisión",
    "Impronta della revisione precedente": "Huella de la revisión anterior",
    "Impronta del record": "Huella del registro",
    "Versione del formato": "Versión del formato",
    "Identificativo del lotto": "Identificador del lote",
    "Titolo": "Título",
    "Perimetro": "Alcance",
    "Numero previsto di voci": "Número previsto de entradas",
    "Voci del lotto": "Entradas del lote",
    "Controlli conservati": "Revisiones conservadas",
    "Descrizione": "Descripción",
    "Processo": "Proceso",
    "Nome": "Nombre",
    "Obiettivo": "Objetivo",
    "Tentativi": "Intentos",
    "Identificativo del tentativo": "Identificador del intento",
    "Identificativo del processo": "Identificador del proceso",
    "Disponibile nell’ambiente qualificato": "Disponible en el entorno cualificado",
    "Qualificazioni conservate": "Cualificaciones conservadas",
    "Rilasci": "Publicaciones",
    "Versioni": "Versiones",
    "Limiti": "Limitaciones",
    "Risultato": "Resultado",
    "Data di creazione": "Fecha de creación",
    "Ultimo aggiornamento": "Última actualización",
    "Da elaborare": "Pendiente",
    "Completata": "Completada",
    "Da decidere": "Por decidir",
    "Non riuscita": "Fallida",
    "Esito da verificare": "Resultado por verificar",
    "Nessuna voce conservata.": "No hay entradas conservadas.",
    "Nessun campo conservato.": "No hay campos conservados.",
    "Non indicato": "No indicado",
    "Campo vuoto": "Campo vacío",
    "Quali dati arrivano al modello": "Qué datos llegan al modelo",
    "Campi del controllo conservati. Nessuna decisione ancora registrata.": "Campos de la revisión conservados. Aún no se ha registrado ninguna decisión.",
    "Campi non conservati: ": "Campos no conservados: ",
    "← Clienti e incarichi": "← Clientes y encargos",
    "Automazione web": "Automatización web",
    "Consulta lo sviluppo dei processi e controlla i risultati dei lotti conservati.": "Consulte el desarrollo de los procesos y revise los resultados de los lotes conservados.",
    "Lotto · proposta, risultato e fonti": "Lote · propuesta, resultado y fuentes",
    "Processo · tentativi e collaudo": "Proceso · intentos y cualificación",
    "Apri evidenze": "Abrir evidencias",
    "Nessun processo o lotto collegato a questo operatore. Riprendi il lavoro specialistico nella chat; il pannello mostra soltanto record esistenti collegati dal runtime.": "No hay ningún proceso ni lote vinculado a este operador. Retome el trabajo especializado en el chat; el panel solo muestra registros existentes vinculados por el runtime.",
    "Scarica ": "Descargar ",
    "← Processi e lotti": "← Procesos y lotes",
    "Vera · Automazione web": "Vera · Automatización web",
    "Qualificato nell’ambiente registrato: il prossimo avvio verifica di nuovo il contratto.": "Cualificado en el entorno registrado: el próximo inicio comprobará de nuevo el contrato.",
    "Collaudo dell’ambiente da completare.": "La cualificación del entorno está pendiente.",
    "Per insegnare o eseguire il processo usa la chat e il workflow browser esistente. L’apertura di queste evidenze non avvia una sessione Chrome.": "Use el chat y el flujo de navegador existente para enseñar o ejecutar el proceso. Abrir estas evidencias no inicia una sesión de Chrome.",
    "Perimetro, versioni, rilasci e qualificazione": "Alcance, versiones, publicaciones y cualificación",
    "Tutti i tentativi, limiti ed evidenze tecniche": "Todos los intentos, limitaciones y evidencias técnicas",
    "Revisione ": "Revisión ",
    " · popolazione prevista: ": " · población prevista: ",
    "Non ancora definita": "Aún no definida",
    "Il risultato riportato e il controllo del professionista sono distinti. Una richiesta di correzione conserva la registrazione originale.": "El resultado declarado y la revisión del profesional son distintos. Una solicitud de corrección conserva el asiento original.",
    "Tutte le revisioni e i controlli conservati": "Todas las revisiones y comprobaciones conservadas",
    "Scarica rapporto verificato": "Descargar informe verificado",
    "Esamina e controlla voce": "Examinar y revisar entrada",
    "Esamina e controlla ": "Examinar y revisar ",
    "← Lotto": "← Lote",
    "Vera · controllo del lotto": "Vera · revisión del lote",
    "Voce completa: proposta, risultato effettivo, motivazione e fonti": "Entrada completa: propuesta, resultado efectivo, motivo y fuentes",
    "Tutti i controlli precedenti su questa voce": "Todas las revisiones anteriores de esta entrada",
    "Una scrittura precedente è incerta. Recupera il lotto nel workflow specialistico prima di ripetere il controllo.": "Una escritura anterior es incierta. Recupere el lote mediante el flujo especializado antes de repetir la revisión.",
    "Campi precedenti da confrontare": "Campos anteriores que comparar",
    "Scarto soltanto i campi privati precedenti; conservo fatture e controlli": "Descarto únicamente los campos privados anteriores; las facturas y revisiones se conservan",
    "Scarta campi privati": "Descartar campos privados",
    "Conferma lo scarto dei soli campi privati.": "Confirme el descarte únicamente de los campos privados.",
    "Decisione espressa sul controllo": "Decisión expresada sobre la revisión",
    "Scegli la decisione": "Elija una decisión",
    "Controllata": "Revisada",
    "Correzione richiesta": "Corrección solicitada",
    "Nota effettiva del professionista": "Nota efectiva del profesional",
    "Indica la decisione e una nota sul controllo svolto. Puoi conservare campi incompleti; per registrare il controllo servono entrambi e una nuova conferma.": "Indique su decisión y una nota sobre la revisión realizada. Puede conservar campos incompletos; para registrar la revisión se requieren ambos campos y una nueva confirmación.",
    "Ho controllato questa voce completa e confermo la decisione espressa": "He revisado esta entrada completa y confirmo mi decisión expresada",
    "Conserva campi incompleti": "Conservar campos incompletos",
    "Registra controllo": "Registrar revisión",
    "Indica la decisione e la nota effettive, poi conferma la voce corrente.": "Indique la decisión y la nota efectivas y confirme después la entrada actual.",
    "Controllo conservato. Nessuna correzione contabile eseguita.": "Revisión conservada. No se ha ejecutado ninguna corrección contable.",
    "Lingua del pannello": "Idioma del panel",
    "Lingua del pannello non supportata.": "Idioma del panel no admitido.",
    "Questo pannello usa route riservate all’app. Legge i processi collegati, i tentativi e i controlli dei lotti, senza chiamare il modello o navigare sui portali. Le voci del lotto possono contenere identità delle fatture, descrizioni, importi, trattamento contabile e IVA proposto ed effettivo, fonti e riferimenti di registrazione. La chat specialistica può leggere i dati autorizzati necessari al lavoro; non sono anonimizzati automaticamente. I valori degli output dichiarati artifact_only e i documenti scaricati restano esclusi dal riepilogo tecnico dei processi. Il runtime browser conserva hash e conteggi; questi non dimostrano quali dati il provider abbia ricevuto. Password, cookie, sessioni e catture grezze non appartengono al pannello. Un controllo qui registra soltanto la decisione espressa: non contabilizza, corregge sul portale, invia una richiesta di sviluppo o chiude l’Archivio.": "Este panel utiliza rutas reservadas a la aplicación. Lee los procesos vinculados, los intentos y las revisiones de los lotes, sin llamar al modelo ni navegar por los portales. Las entradas del lote pueden contener identidades de facturas, descripciones, importes, el tratamiento contable y de IVA propuesto y efectivo, fuentes y referencias de asientos. El chat especializado puede leer los datos autorizados necesarios para el trabajo; no se anonimizan automáticamente. Los valores de las salidas declaradas artifact_only y los documentos descargados quedan excluidos del resumen técnico de los procesos. El runtime del navegador conserva huellas y recuentos; estos no demuestran qué datos recibió el proveedor. Las contraseñas, cookies, sesiones y capturas sin procesar no pertenecen al panel. Una revisión aquí solo registra la decisión expresada: no contabiliza asientos, corrige datos en el portal, envía solicitudes de desarrollo ni cierra el Archivo."
  }
};
  let language=Object.hasOwn(translations,api.language)?api.language:"it";
  const t=text=>translations[language][text]??text;
  const exact=p=>({work_ref:p.work_ref,revision:p.revision,source_ref:p.source_ref,item_id:p.selection.id});
  const status={pending:"Da elaborare",completed:"Completata",set_aside:"Da decidere",failed:"Non riuscita",unverified:"Esito da verificare"};
  function dispose(){clearTimeout(timer);context=null;currentWork=null;for(const url of urls)URL.revokeObjectURL(url);urls.clear();}
  const fieldLabels=Object.freeze({id:"Identificativo della voce",document:"Documento",action:"Azione dichiarata",reason:"Motivazione",outcome:"Esito dichiarato",status:"Stato dichiarato",proposed:"Trattamento proposto",actual:"Risultato effettivo",evidence:"Evidenze e dati della fattura",question:"Questione aperta",posting_reference:"Riferimento della registrazione",correction_of:"Registrazione rettificata",label:"Dato descritto",value:"Valore",source:"Fonte",entry_id:"Voce controllata",decision:"Decisione espressa",note:"Nota del professionista",at:"Data del controllo",payload:"Contenuto della revisione",revision:"Numero di revisione",previous_sha256:"Impronta della revisione precedente",sha256:"Impronta del record",schema_version:"Versione del formato",batch_id:"Identificativo del lotto",title:"Titolo",scope:"Perimetro",expected_items:"Numero previsto di voci",entries:"Voci del lotto",reviews:"Controlli conservati",description:"Descrizione",process:"Processo",name:"Nome",objective:"Obiettivo",attempts:"Tentativi",attempt_id:"Identificativo del tentativo",process_id:"Identificativo del processo",available_in_qualified_environment:"Disponibile nell’ambiente qualificato",qualifications:"Qualificazioni conservate",releases:"Rilasci",versions:"Versioni",limitations:"Limiti",result:"Risultato",created_at:"Data di creazione",updated_at:"Ultimo aggiornamento"});
  function prepare(main){main.setAttribute("lang",language);main.append(node("style",`.browser-record{margin-block:1rem}.browser-record summary{font-weight:600;cursor:pointer}.browser-record dl{margin:.75rem 0;display:grid;grid-template-columns:minmax(9rem,1fr) minmax(0,3fr);gap:.5rem 1rem}.browser-record dt{font-weight:600;overflow-wrap:anywhere}.browser-record dd{margin:0;min-width:0;overflow-wrap:anywhere}.browser-record ol{padding-inline-start:1.5rem}.browser-record li+li{margin-block-start:1rem}.browser-record p{white-space:pre-wrap;overflow-wrap:anywhere}.browser-record summary:focus-visible{outline:2px solid #1b66b1;outline-offset:3px}@media(max-width:650px){.browser-record dl{grid-template-columns:minmax(0,1fr)}.browser-record dd{margin-block-end:.6rem}}`));}
  function languageChoice(main){const group=node("label",undefined,"browser-language"),select=node("select");group.setAttribute("style","display:block;margin-block:.5rem 1rem");select.setAttribute("aria-label",t("Lingua del pannello"));for(const [value,label]of [["it","Italiano"],["en","English"],["fr","Français"],["de","Deutsch"],["es","Español"]]){const option=node("option",label);option.value=value;select.append(option);}select.value=language;select.addEventListener("change",async()=>{try{await setLanguage(select.value);}catch(error){select.value=language;say(error.message,true);}});group.append(node("span",t("Lingua del pannello")+" · "),select);main.append(group);}
  async function setLanguage(value){if(!Object.hasOwn(translations,value))throw new Error(t("Lingua del pannello non supportata."));await flush();api.leaveDraft();language=value;return refresh();}
  function refresh(){return currentWork?.itemId?openEntry(currentWork.workRef,currentWork.itemId):currentWork?.workRef?open(currentWork.workRef):catalogue();}
  function readable(parent,value,title){
    const detail=node("details",undefined,"browser-record");detail.append(node("summary",title));
    const walk=(into,item)=>{
      if(Array.isArray(item)){if(!item.length){into.append(node("p",t("Nessuna voce conservata."),"caption"));return;}const list=node("ol");for(const part of item){const row=node("li");walk(row,part);list.append(row);}into.append(list);}
      else if(item!==null&&typeof item==="object"){const entries=Object.entries(item);if(!entries.length){into.append(node("p",t("Nessun campo conservato."),"caption"));return;}const fields=node("dl");for(const [key,part]of entries){const datum=node("dd");walk(datum,part);fields.append(node("dt",t(fieldLabels[key]||key)),datum);}into.append(fields);}
      else into.append(node("p",item===null?t("Non indicato"):item===""?t("Campo vuoto"):String(item),"source-excerpt"));
    };walk(detail,value);parent.append(detail);
  }
  function labelControl(main,control,text){const id="browser-review-control-"+(++controlId),label=node("label",text);control.setAttribute("id",id);label.setAttribute("for",id);main.append(label,control);}
  function privacy(main){main.append(node("h2",t("Quali dati arrivano al modello")),node("p",t("Questo pannello usa route riservate all’app. Legge i processi collegati, i tentativi e i controlli dei lotti, senza chiamare il modello o navigare sui portali. Le voci del lotto possono contenere identità delle fatture, descrizioni, importi, trattamento contabile e IVA proposto ed effettivo, fonti e riferimenti di registrazione. La chat specialistica può leggere i dati autorizzati necessari al lavoro; non sono anonimizzati automaticamente. I valori degli output dichiarati artifact_only e i documenti scaricati restano esclusi dal riepilogo tecnico dei processi. Il runtime browser conserva hash e conteggi; questi non dimostrano quali dati il provider abbia ricevuto. Password, cookie, sessioni e catture grezze non appartengono al pannello. Un controllo qui registra soltanto la decisione espressa: non contabilizza, corregge sul portale, invia una richiesta di sviluppo o chiude l’Archivio."),"caption"));}
  async function persist(){const local=context;if(!local?.editable)return queue;const fields=structuredClone(local.fields),serialized=JSON.stringify(fields);queue=queue.then(async()=>{if(local.saved===serialized)return;const saved=await call("vera_workspace_browser_draft_save",{...exact(local.page),review_ticket:local.page.review_ticket,expected_draft_revision:local.stamp,fields});local.stamp=saved.draft_revision;local.saved=serialized;local.error=null;if(context===local&&JSON.stringify(local.fields)===serialized)api.setDirty(false);say(t("Campi del controllo conservati. Nessuna decisione ancora registrata."));}).catch(error=>{local.error=error;api.setDirty(true);say(t("Campi non conservati: ")+error.message,true);});return queue;}
  async function flush(){clearTimeout(timer);await persist();if(context?.error)throw context.error;}
  async function catalogue(){await flush();api.leaveDraft();const generation=api.enter(),page=await call("vera_workspace_browser_catalogue",{});if(!api.isCurrent(generation))return;const {nav,main}=api.shell();prepare(main);nav.setAttribute("lang",language);languageChoice(main);currentWork={catalogue:true};nav.append(button(t("← Clienti e incarichi"),api.openWorks));main.append(node("p","Vera","eyebrow"),node("h1",t("Automazione web")),node("p",t("Consulta lo sviluppo dei processi e controlla i risultati dei lotti conservati."),"intro"));for(const work of page.works){const row=node("section",undefined,"output");row.append(node("h2",work.title),node("p",work.kind==="batch"?t("Lotto · proposta, risultato e fonti"):t("Processo · tentativi e collaudo")),button(t("Apri evidenze"),()=>open(work.work_ref)));main.append(row);}if(!page.configured)main.append(node("p",t("Nessun processo o lotto collegato a questo operatore. Riprendi il lavoro specialistico nella chat; il pannello mostra soltanto record esistenti collegati dal runtime."),"notice"));privacy(main);}
  async function download(page,row){const artifact=await call("vera_workspace_browser_artifact",{work_ref:page.work_ref,revision:page.revision,source_ref:page.revision}),bytes=Uint8Array.from(atob(artifact.base64),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:artifact.mime_type}));urls.add(url);const link=node("a",t("Scarica ")+artifact.name);link.href=url;link.download=artifact.name;row.append(link);link.click();}
  async function open(workRef){await flush();api.leaveDraft();const generation=api.enter(),page=await call("vera_workspace_browser_setup",{work_ref:workRef});if(!api.isCurrent(generation))return;const {nav,main}=api.shell();prepare(main);nav.setAttribute("lang",language);languageChoice(main);currentWork={workRef};nav.append(button(t("← Processi e lotti"),catalogue),button(t("← Clienti e incarichi"),api.openWorks));main.append(node("p",t("Vera · Automazione web"),"eyebrow"));
    if(page.kind==="process"){const process=page.data.process;main.append(node("h1",process.description.process.name),node("p",process.description.process.objective,"intro"),node("p",process.available_in_qualified_environment?t("Qualificato nell’ambiente registrato: il prossimo avvio verifica di nuovo il contratto."):t("Collaudo dell’ambiente da completare."),"notice"),node("p",t("Per insegnare o eseguire il processo usa la chat e il workflow browser esistente. L’apertura di queste evidenze non avvia una sessione Chrome."),"caption"));readable(main,process,t("Perimetro, versioni, rilasci e qualificazione"));readable(main,page.data.attempts,t("Tutti i tentativi, limiti ed evidenze tecniche"));}
    else{const record=page.data.record,payload=record.payload;main.append(node("h1",payload.title),node("p",payload.scope,"intro"),node("p",t("Revisione ")+record.revision+t(" · popolazione prevista: ")+(payload.expected_items===null?t("Non ancora definita"):payload.expected_items),"caption"),node("p",t("Il risultato riportato e il controllo del professionista sono distinti. Una richiesta di correzione conserva la registrazione originale."),"notice"));readable(main,page.data.history,t("Tutte le revisioni e i controlli conservati"));const report=node("section",undefined,"output");report.append(button(t("Scarica rapporto verificato"),()=>download(page,report)));main.append(report);for(const entry of payload.entries){const row=node("section",undefined,"output");row.append(node("strong",entry.document),node("p",t(status[entry.status])||entry.status),node("p",entry.question||entry.outcome),(()=>{const inspect=button(t("Esamina e controlla voce"),()=>openEntry(workRef,entry.id));inspect.setAttribute("aria-label",t("Esamina e controlla ")+entry.document);return inspect;})());main.append(row);}}
    privacy(main);
  }
  async function openEntry(workRef,itemId){await flush();api.leaveDraft();const generation=api.enter(),page=await call("vera_workspace_browser_read",{work_ref:workRef,item_id:itemId});if(!api.isCurrent(generation))return;const {nav,main}=api.shell();prepare(main);nav.setAttribute("lang",language);languageChoice(main);currentWork={workRef,itemId};nav.append(button(t("← Lotto"),()=>open(workRef)));const local={page,fields:structuredClone(page.fields),stamp:page.draft_revision,saved:JSON.stringify(page.fields),editable:page.can_write&&!page.draft_stale&&!page.pending_operations.length};context=local;api.setDirty(false);main.append(node("p",t("Vera · controllo del lotto"),"eyebrow"),node("h1",page.entry.document),node("p",t(status[page.entry.status])||page.entry.status,"caption"));readable(main,page.entry,t("Voce completa: proposta, risultato effettivo, motivazione e fonti"));readable(main,page.data.record.payload.reviews.filter(r=>r.entry_id===itemId),t("Tutti i controlli precedenti su questa voce"));
    if(page.pending_operations.length)main.append(node("p",t("Una scrittura precedente è incerta. Recupera il lotto nel workflow specialistico prima di ripetere il controllo."),"notice"));
    if(page.draft_stale){readable(main,local.fields,t("Campi precedenti da confrontare"));const check=confirmation(main,t("Scarto soltanto i campi privati precedenti; conservo fatture e controlli")),clear=button(t("Scarta campi privati"),async()=>{if(!check.checked)throw new Error(t("Conferma lo scarto dei soli campi privati."));await call("vera_workspace_browser_draft_clear",{...exact(page),review_ticket:page.review_ticket,expected_draft_revision:local.stamp,confirmed:true});api.setDirty(false);await openEntry(workRef,itemId);});check.disabled=clear.disabled=!page.can_write;main.append(clear);}
    const decision=node("select");decision.setAttribute("aria-label",t("Decisione espressa sul controllo"));for(const [value,label]of [["",t("Scegli la decisione")],["checked",t("Controllata")],["correction_requested",t("Correzione richiesta")]]){const option=node("option",label);option.value=value;decision.append(option);}decision.value=local.fields.decision;decision.disabled=!local.editable;const note=node("textarea");note.setAttribute("aria-label",t("Nota effettiva del professionista"));note.maxLength=4000;note.value=local.fields.note;note.disabled=!local.editable;const change=()=>{local.fields={decision:decision.value,note:note.value};local.confirm.checked=false;local.execution=null;api.setDirty(true);clearTimeout(timer);timer=setTimeout(persist,450);};decision.addEventListener("change",change);note.addEventListener("input",change);labelControl(main,decision,t("Decisione espressa sul controllo"));labelControl(main,note,t("Nota effettiva del professionista"));const help=node("p",t("Indica la decisione e una nota sul controllo svolto. Puoi conservare campi incompleti; per registrare il controllo servono entrambi e una nuova conferma."),"caption");help.setAttribute("id","browser-review-help-"+controlId);decision.setAttribute("aria-describedby","browser-review-help-"+controlId);note.setAttribute("aria-describedby","browser-review-help-"+controlId);main.append(help);local.confirm=confirmation(main,t("Ho controllato questa voce completa e confermo la decisione espressa"));local.confirm.disabled=!local.editable;const save=button(t("Conserva campi incompleti"),flush),commit=button(t("Registra controllo"),async()=>{await flush();if(!local.confirm.checked||!local.fields.decision||!local.fields.note.trim())throw new Error(t("Indica la decisione e la nota effettive, poi conferma la voce corrente."));local.execution=local.execution||{...exact(page),review_ticket:page.review_ticket,expected_draft_revision:local.stamp,fields:structuredClone(local.fields),confirmed:true,idempotency_key:crypto.randomUUID()};await call("vera_workspace_browser_review_commit",local.execution);api.setDirty(false);await openEntry(workRef,itemId);say(t("Controllo conservato. Nessuna correzione contabile eseguita."));},"primary");save.disabled=commit.disabled=!local.editable;main.append(save,commit);privacy(main);
  }
  return Object.freeze({catalogue,open,openEntry,flush,dispose,active:()=>Boolean(currentWork),refresh,setLanguage,language:()=>language});
}});
