"use strict";
/* Literal professional decisions use the exact existing matrix; no editorial rules. */
globalThis.VeraCommunication = Object.freeze({create(api){
  const {node,button,call,say,confirmation}=api;let context,timer,queue=Promise.resolve();const urls=new Set();
  const choices={semantic_review:"Riesame della matrice",qa_preview:"Anteprima grafica per il riesame",promote_profile:"Adotta il profilo riesaminato",render:"Produci gli elaborati riesaminati",render_review:"Riesame degli elaborati esatti",package:"Prepara il pacchetto",package_review:"Riesame del pacchetto esatto",validate:"Verifica e finalizza il pacchetto"};
  const decisions=[["","Da decidere"],["accepted","Accetta"],["returned","Restituisci"],["rejected","Rifiuta"]];
  const scope=p=>({work_ref:p.work_ref,revision:p.revision,source_ref:p.source_ref});
  function dispose(){clearTimeout(timer);context=null;for(const url of urls)URL.revokeObjectURL(url);urls.clear();}
  async function persist(){const local=context;if(!local?.editable)return queue;const fields=structuredClone(local.fields),serialized=JSON.stringify(fields);queue=queue.then(async()=>{if(local.saved===serialized)return;const saved=await call("vera_workspace_communication_draft_save",{...scope(local.page),review_ticket:local.page.review_ticket,expected_draft_revision:local.stamp,fields});local.stamp=saved.draft_revision;local.saved=serialized;local.error=null;if(context===local&&JSON.stringify(local.fields)===serialized)api.setDirty(false);say("Decisioni incomplete conservate. Nessun riesame professionale registrato.");}).catch(error=>{local.error=error;api.setDirty(true);say("Campi non conservati: "+error.message,true);});return queue;}
  async function flush(){clearTimeout(timer);await persist();if(context?.error)throw context.error;}
  function changed(local){local.confirm.checked=false;local.quality.checked=false;local.execution=null;api.setDirty(true);clearTimeout(timer);timer=setTimeout(persist,450);}
  function input(main,local,label,value,changedValue,options){const wrap=node("label",undefined,"field"),control=node(options?"select":"textarea");control.setAttribute("aria-label",label);if(options)for(const [key,text] of options){const option=node("option",text);option.value=key;control.append(option);}control.value=value;control.disabled=!local.editable;control.maxLength=2000;control.addEventListener(options?"change":"input",()=>{changedValue(control.value);changed(local);});wrap.append(node("span",label),control);main.append(wrap);return control;}
  function readable(main,value,title){const detail=node("details",undefined,"patent-record");detail.append(node("summary",title));main.append(detail);const walk=(parent,item)=>{if(item!==null&&typeof item==="object")for(const [key,part]of Object.entries(item)){const group=node("section");group.append(node("h4",key));parent.append(group);walk(group,part);}else parent.append(node("p",item===null?"Non indicato":String(item),"source-excerpt"));};walk(detail,value);}
  function privacy(main){main.append(node("h2","Quali dati arrivano al modello"),node("p","Questo pannello espone nell’app la versione completa già preparata, le valutazioni, le decisioni e gli elaborati dichiarati. Le sue route non trasferiscono contenuti al modello e non aprono storico o mappe delle identità. La preparazione specialistica resta nella chat: lo storico scelto segue pseudonimizzazione e riesame indipendente; generazione, verifica delle affermazioni, giudizio editoriale e riesame grafico hanno pacchetti e sessioni distinti. Le attestazioni del runtime non sono ricevute autentiche del provider. Il trattamento usa l’account Codex o Cowork scelto dallo studio e non è esclusivamente locale.","caption"));}
  async function catalogue(){await flush();api.leaveDraft();const generation=api.enter(),page=await call("vera_workspace_communication_catalogue",{});if(!api.isCurrent(generation))return;const {nav,main}=api.shell();nav.append(button("← Clienti e incarichi",api.openWorks));main.append(node("p","Vera","eyebrow"),node("h1","Comunicazioni dello studio"),node("p","Riprendi una versione preparata nella cartella privata dello studio. Le comunicazioni non appartengono al fascicolo di un cliente.","intro"));for(const work of page.works){const row=node("section",undefined,"output");row.append(node("h2",work.studio),node("p",work.objective),node("p",work.recommendation==="no_publish"?"Proposta di non comunicare": "Comunicazione proposta"),button("Riesamina questa versione",()=>open(work.work_ref)));main.append(row);}if(!page.configured)main.append(node("p","Nessun run di comunicazione collegato a questo operatore. Riprendi il workflow specialistico nella chat e collega il suo workspace privato attraverso la configurazione mantenuta dell’host.","notice"));privacy(main);}
  async function open(workRef){await flush();api.leaveDraft();const generation=api.enter(),page=await call("vera_workspace_communication_setup",{work_ref:workRef});if(!api.isCurrent(generation))return;const {nav,main}=api.shell();nav.append(button("← Comunicazioni dello studio",catalogue),button("← Clienti e incarichi",api.openWorks));const local={page,fields:structuredClone(page.fields),stamp:page.draft_revision,saved:JSON.stringify(page.fields),editable:page.can_write&&!page.draft_stale&&!page.pending_operations.length};context=local;api.setDirty(false);const data=page.data;main.append(node("p",data.studio,"eyebrow"),node("h1","Riesame della comunicazione"),node("p",data.intake.objective,"intro"),node("p",data.workbench.contribution.recommendation==="no_publish"?"Non comunicare è un esito completo: riesamina la motivazione e verifica i record interni.":"Le copie e gli elaborati richiedono i riesami separati del workflow. Invio e pubblicazione richiedono una scelta esterna distinta.","notice"));readable(main,data.intake,"Scopo, pubblico, canali e percorsi scelti");readable(main,data.workbench,"Versione completa, affermazioni, copie e valutazioni");readable(main,data.review_payload,"Matrice effettiva da riesaminare");readable(main,data.review_log,"Decisioni conservate");if(data.final)readable(main,data.final,"Pacchetto e verifica corrente");
    for(const file of data.artifacts){const row=node("section",undefined,"output");row.append(node("strong",file.name),button("Scarica questo elaborato",async()=>{const value=await call("vera_workspace_communication_artifact",{...scope(page),artifact_ref:file.name}),bytes=Uint8Array.from(atob(value.base64),char=>char.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:"application/octet-stream"}));urls.add(url);const link=node("a","Scarica "+value.name);link.href=url;link.download=value.name;row.append(link);link.click();}));main.append(row);}
    if(page.pending_operations.length)main.append(node("p","Una scrittura precedente richiede recupero nel workflow specialistico. Le ricevute e le versioni sono conservate; non ripetere l’operazione.","notice"));
    if(page.draft_stale){readable(main,local.fields,"Campi precedenti da confrontare");const clear=confirmation(main,"Scarto soltanto questi campi incompleti dopo il confronto con la versione corrente"),discard=button("Scarta campi privati",async()=>{if(!clear.checked)throw new Error("Conferma lo scarto dei soli campi privati.");await call("vera_workspace_communication_draft_clear",{...scope(page),review_ticket:page.review_ticket,expected_draft_revision:local.stamp,confirmed:true});api.setDirty(false);await open(workRef);});clear.disabled=discard.disabled=!page.can_write;main.append(discard);}
    else{input(main,local,"Passaggio da conservare",local.fields.operation,value=>local.fields.operation=value,[["","Scegli il passaggio"],...Object.entries(choices)]);input(main,local,"Professionista che ha svolto il riesame",local.fields.reviewer,value=>local.fields.reviewer=value);main.append(node("h2","Decisioni sulla versione esatta"));for(const scopeName of data.workbench.required_review_scopes){const row=node("section");row.append(node("h3",scopeName));const previous=local.fields.decisions[scopeName]||{decision:"",note:""};const change=(key,value)=>{local.fields.decisions[scopeName]={...(local.fields.decisions[scopeName]||previous),[key]:value};};input(row,local,"Decisione · "+scopeName,previous.decision,value=>change("decision",value),decisions);input(row,local,"Motivazione · "+scopeName,previous.note,value=>change("note",value));main.append(row);}input(main,local,"Decisione separata sugli elaborati o sul pacchetto",local.fields.decision,value=>local.fields.decision=value,decisions);input(main,local,"Nota sul passaggio scelto",local.fields.note,value=>local.fields.note=value);local.quality=confirmation(main,"Ho aperto tutti gli elaborati grafici esatti e confermo la checklist del workflow");local.confirm=confirmation(main,"Confermo questo passaggio sulla versione completa corrente. Invio e pubblicazione restano distinti");local.quality.disabled=local.confirm.disabled=!local.editable;const save=button("Conserva campi incompleti",flush),execute=button("Esegui e conserva il passaggio",async()=>{await flush();if(!local.confirm.checked)throw new Error("Riesamina e conferma il passaggio corrente.");local.execution=local.execution||{...scope(page),review_ticket:page.review_ticket,expected_draft_revision:local.stamp,fields:structuredClone(local.fields),confirmed:true,quality_checklist_confirmed:local.quality.checked,idempotency_key:crypto.randomUUID()};await call("vera_workspace_communication_execute",local.execution);api.setDirty(false);await open(workRef);say("Passaggio conservato dal workflow. Nessun invio o pubblicazione eseguito.");},"primary");save.disabled=execute.disabled=!local.editable;main.append(save,execute);}
    privacy(main);
  }
  return Object.freeze({open,catalogue,flush,dispose,active:()=>Boolean(context),refresh:()=>context?open(context.page.work_ref):catalogue()});
}});
