"use strict";
/* Complete prepared public dossier; no embedded reports or professional stamp. */
globalThis.VeraRating=Object.freeze({create(api){
  const {node,button,call,say,confirmation}=api;let context,timer,queue=Promise.resolve();const urls=new Set();
  const scope=p=>({work_ref:p.work_ref,revision:p.revision,source_ref:p.source_ref});
  function dispose(){clearTimeout(timer);context=null;for(const url of urls)URL.revokeObjectURL(url);urls.clear();}
  async function persist(){const local=context;if(!local?.editable)return queue;const fields=structuredClone(local.fields),serialized=JSON.stringify(fields);queue=queue.then(async()=>{if(local.saved===serialized)return;const saved=await call("vera_workspace_rating_draft_save",{...scope(local.page),review_ticket:local.page.review_ticket,expected_draft_revision:local.stamp,fields});local.stamp=saved.draft_revision;local.saved=serialized;local.error=null;if(context===local&&JSON.stringify(local.fields)===serialized)api.setDirty(false);say("Selezione incompleta conservata. Nessuna decisione aggiunta al caso.");}).catch(error=>{local.error=error;api.setDirty(true);say("Campi non conservati: "+error.message,true);});return queue;}
  async function flush(){clearTimeout(timer);await persist();if(context?.error)throw context.error;}
  function readable(parent,value,title){const detail=node("details",undefined,"patent-record");detail.append(node("summary",title));const walk=(into,item)=>{if(item!==null&&typeof item==="object")for(const [key,part]of Object.entries(item)){const section=node("section");section.append(node("h4",key));into.append(section);walk(section,part);}else into.append(node("p",item===null?"Non indicato":String(item),"source-excerpt"));};walk(detail,value);parent.append(detail);}
  function field(parent,local,label,key,options){const wrap=node("label",undefined,"field"),control=node(options?"select":"textarea");control.setAttribute("aria-label",label);if(options)for(const [value,text]of options){const option=node("option",text);option.value=value;control.append(option);}control.value=local.fields[key];control.maxLength=key==="note"?2000:200;control.disabled=local.page.draft_stale;control.addEventListener(options?"change":"input",()=>{local.fields[key]=control.value;local.preview=null;local.execution=null;local.confirm.checked=false;local.view.replaceChildren();if(local.editable){api.setDirty(true);clearTimeout(timer);timer=setTimeout(persist,450);}});wrap.append(node("span",label),control);parent.append(wrap);return control;}
  function privacy(main){main.append(node("h2","Quali dati arrivano al modello"),node("p","Le route del pannello sono riservate all’app: selezioni private, caso completo, estratti citati, presupposti registrati, eventi, decisioni e dossier rimangono nei metadati dell’app. Il pannello non chiama il modello né esegue ricerche. Nel percorso specialistico il modello Codex o Cowork può leggere i documenti societari, personali, giudiziari, fiscali e di pagamento scelti, originali o estrazioni riviste, citazioni, conflitti, decisioni e bozze. Prima di chiedere o leggere schede giudiziarie reali occorrono il riesame dell’incarico e del trattamento effettivo: il controllo dei record non dimostra da solo l’autorità giuridica. Nessuna anonimizzazione automatica o garanzia di trattamento esclusivamente locale; valgono le condizioni dell’account scelto. Le ricerche pubbliche devono usare quesiti senza identificativi del cliente o dettagli giudiziari identificabili.","caption"));}
  async function download(page,item,row){const value=await call("vera_workspace_rating_artifact",{...scope(page),artifact_ref:item.name}),bytes=Uint8Array.from(atob(value.base64),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:value.mime_type}));urls.add(url);const link=node("a","Scarica "+value.name);link.href=url;link.download=value.name;row.append(link);link.click();}
  async function open(workRef){await flush();api.leaveDraft();const generation=api.enter(),page=await call("vera_workspace_rating_setup",{work_ref:workRef});if(!api.isCurrent(generation))return;const {nav,main}=api.shell();nav.append(button("← Clienti e incarichi",api.openWorks));const local={page,fields:structuredClone(page.fields),stamp:page.draft_revision,saved:JSON.stringify(page.fields),editable:page.can_write&&!page.draft_stale&&!page.pending_operations.length,preview:null};context=local;api.setDirty(false);
    main.append(node("p","Vera · Rating di legalità","eyebrow"),node("h1","Dossier per la prima attribuzione"),node("p","Seleziona il caso JSON registrato nell’incarico. Controlla il dossier completo prima di conservarlo con il motore della funzione.","intro"),node("p","Il dossier conserva i giudizi presenti nel caso. Il rating ufficiale resta non attribuito e nessun invio è autorizzato. Per preparare o rivedere fatti e decisioni, riprendi Rating di legalità nella chat.","notice"));
    if(page.pending_operations.length)main.append(node("p","Una scrittura precedente è incerta. Riprendi il workflow specialistico per recuperare i record; non ripetere automaticamente il render.","notice"));
    if(page.draft_stale){readable(main,local.fields,"Selezione precedente da confrontare");const check=confirmation(main,"Scarto soltanto i campi privati precedenti; conservo dossier, fonti e ricevute"),clear=button("Scarta campi privati",async()=>{if(!check.checked)throw new Error("Conferma lo scarto dei soli campi privati.");await call("vera_workspace_rating_draft_clear",{...scope(page),review_ticket:page.review_ticket,expected_draft_revision:local.stamp,confirmed:true});api.setDirty(false);await open(workRef);});check.disabled=clear.disabled=!page.can_write;main.append(clear);}
    field(main,local,"Caso JSON registrato","case_input_id",[["","Scegli il caso"],...page.items.map(x=>[x.id,x.name])]);field(main,local,"Dossier precedente sigillato · obbligatorio nelle continuazioni","previous_input_id",[["","Nessun dossier precedente"],...page.predecessors.map(x=>[x.id,x.name])]);field(main,local,"Nota privata · non entra nel dossier","note");
    local.view=node("div");local.confirm=confirmation(main,"Ho controllato il dossier completo e confermo il render sul caso e sul predecessore selezionati");local.confirm.disabled=!local.editable||!page.can_render;
    const inspect=button("Controlla dossier scelto",async()=>{await flush();local.confirm.checked=false;const serialized=JSON.stringify(local.fields),value=await call("vera_workspace_rating_read",{...scope(page),fields:structuredClone(local.fields)});if(context!==local||serialized!==JSON.stringify(local.fields))return;local.preview=value;local.view.replaceChildren();local.view.append(node("h2",value.record.case.synthetic?"Dossier sintetico · verifica del percorso":"Dossier da riesaminare"),node("p",value.record.assessment.status,"notice"));readable(local.view,value.record,"Caso completo, presupposti, situazioni osservate, scenari condizionati e giudizi registrati");const report=node("pre",value.report,"source-excerpt");local.view.append(report);say("Anteprima completa verificata dal motore. Conferma corrente ancora da dare.");});
    const save=button("Conserva selezione incompleta",flush),execute=button("Conserva dossier",async()=>{await flush();if(!local.preview||!local.confirm.checked)throw new Error("Controlla il dossier completo e conferma il render corrente.");local.execution=local.execution||{...scope(page),review_ticket:page.review_ticket,expected_draft_revision:local.stamp,fields:structuredClone(local.fields),preview_ref:local.preview.preview_ref,confirmed:true,idempotency_key:crypto.randomUUID()};await call("vera_workspace_rating_execute",local.execution);api.setDirty(false);await open(workRef);say("Dossier conservato dal motore. Nessuna decisione professionale aggiunta e nessun invio autorizzato.");},"primary");save.disabled=!local.editable;execute.disabled=!local.editable||!page.can_render;main.append(inspect,save,execute,local.view);
    if(!page.items.length)main.append(node("p","Il run non contiene un caso JSON registrato. Prepara il caso nel percorso specialistico e importalo prima di proseguire.","notice"));
    for(const item of page.artifacts){const row=node("section",undefined,"output");row.append(node("strong",item.name));if(/^[0-9a-f]{64}\/dossier\.(json|md)$/.test(item.name))row.append(button("Scarica dossier verificato",()=>download(page,item,row)));main.append(row);}
    privacy(main);
  }
  return Object.freeze({open,flush,dispose,active:()=>Boolean(context),refresh:()=>context?open(context.page.work_ref):api.openWorks()});
}});
