from __future__ import annotations

"""Spanish copy for the server-rendered Mparanza web application."""

__all__ = ["SPANISH_PAGE_COPY"]


# Keys below are dotted paths within the corresponding resolved PAGE_COPY page.
# Keeping this as a complete, path-keyed overlay makes missing Spanish copy easy to
# detect in tests while leaving the established four-locale registry undisturbed.
SPANISH_PAGE_COPY: dict[str, dict[str, str]] = {
    "landing": {
        "thesis_alt": "La potencia no es nada sin control.",
        "primary_navigation_label": "Navegación principal",
        "language_selector_label": "Selector de idioma",
        "operator_disclosure": "Mparanza es operada por Mparanza LLC, una sociedad de responsabilidad limitada de Delaware.",
        "sign_out_button": "Cerrar sesión",
        "magic_link_placeholder": "nombre@ejemplo.com",
        "magic_link_email_label": "Correo electrónico",
        "magic_link_button": "Enviar enlace",
        "magic_link_helper": "Usa tu correo electrónico para recibir un enlace de acceso.",
        "magic_link_tooltip": "Introduce tu correo electrónico y te enviaremos un enlace de acceso de un solo uso.",
        "magic_link_invalid_email": "Introduce una dirección de correo electrónico válida.",
        "magic_link_sending": "Enviando enlace...",
        "magic_link_sent": "Consulta tu bandeja de entrada: el enlace de acceso es válido durante 15 minutos. Si no lo ves, revisa la carpeta de spam o correo no deseado.",
        "magic_link_error_generic": "No se ha podido enviar el enlace. Inténtalo de nuevo.",
    },
    "auth_login": {
        "description": "Usa el inicio de sesión con Google o solicita un enlace mágico para acceder al espacio de trabajo solicitado.",
        "helper": "La cookie de sesión se guardará de forma segura en el navegador.",
        "magic_link_placeholder": "nombre@ejemplo.com",
        "magic_link_email_label": "Correo electrónico",
        "magic_link_button": "Enviar enlace",
        "magic_link_helper": "Usa tu correo electrónico para recibir un enlace de acceso.",
        "magic_link_tooltip": "Introduce tu correo electrónico y te enviaremos un enlace de acceso de un solo uso.",
        "magic_link_invalid_email": "Introduce una dirección de correo electrónico válida.",
        "magic_link_sending": "Enviando enlace...",
        "magic_link_sent": "Consulta tu bandeja de entrada: el enlace de acceso es válido durante 15 minutos. Si no lo ves, revisa la carpeta de spam o correo no deseado.",
        "magic_link_error_generic": "No se ha podido enviar el enlace. Inténtalo de nuevo.",
        "disabled": "La autenticación está desactivada actualmente.",
        "redirect_notice": "Inicia sesión para continuar a la página solicitada.",
        "home_link_aria": "Volver a la página de inicio",
    },
    "slides_editor": {
        "home_link_aria": "Volver a la página de inicio",
        "labels.upload_deck": "Subir presentación HTML",
        "labels.upload_zip_deck": "Subir presentación ZIP",
        "labels.upload_pdf_deck": "Subir presentación PDF",
        "labels.upload_zip_package": "Subir ZIP",
        "labels.replace_zip_package": "Sustituir ZIP",
        "labels.run_chart_remap": "Reasignar gráficos",
        "labels.prompt_style_label": "Plantilla de la presentación",
        "labels.upload_action": "Subir",
        "labels.select_file": "Seleccionar archivo",
        "labels.cancel_action": "Cancelar",
        "labels.session_pdf_decks": "Presentaciones PDF de la sesión",
        "labels.brief_zip_loaded": "ZIP del briefing cargado",
        "labels.brief_zip_not_loaded": "El ZIP del briefing aún no se ha cargado.",
        "labels.chart_remap_job_status": "Estado de la reasignación de gráficos",
        "labels.chart_remap_step": "Fase de la reasignación de gráficos",
        "labels.download_unmatched_pngs": "Descargar PNG sin asociar",
        "labels.output_deck_label": "Resultado",
        "labels.status_pending": "Pendiente",
        "labels.status_running": "En curso",
        "labels.status_completed": "Completado",
        "labels.status_failed": "Fallido",
        "labels.status_cancelled": "Cancelado",
        "labels.remap_stage_queued": "En cola",
        "labels.remap_stage_reading_package": "Cargando ZIP",
        "labels.remap_stage_reading_ocr": "Leyendo OCR",
        "labels.remap_stage_layout_analysis": "Análisis de diseño",
        "labels.remap_stage_chart_understanding": "Interpretación de gráficos",
        "labels.remap_stage_validation": "Validando máscaras",
        "labels.remap_stage_repair": "Corrigiendo máscaras",
        "labels.remap_stage_notifying": "Enviando correo de finalización",
        "labels.remap_stage_matching_slides": "Asociando gráficos a diapositivas",
        "labels.remap_stage_patching_slides": "Aplicando máscaras blancas",
        "labels.remap_stage_substituting_slides": "Insertando gráficos",
        "labels.remap_stage_qa_patching": "Verificando máscaras",
        "labels.remap_stage_qa_substitution": "Verificando los gráficos insertados",
        "labels.notebook_remap_queued": "La reasignación de gráficos de Notebook está en cola.",
        "labels.remap_requires_pdf_first": "Sube primero al menos una presentación PDF.",
        "labels.remap_requires_zip_first": "Sube primero el ZIP del paquete del briefing.",
        "labels.remap_upload_pdf_before_zip": "Sube al menos una presentación PDF antes de subir el paquete ZIP.",
        "labels.remap_select_zip_package": "Selecciona un paquete de briefing .zip.",
        "labels.remap_brief_zip_required": "El paquete del briefing debe ser un archivo .zip.",
        "labels.concat_decks": "Combinar presentaciones",
        "labels.concat_dialog_title": "Combinar presentaciones",
        "labels.concat_deck_name": "Nombre de la nueva presentación",
        "labels.concat_helper": "Selecciona una o varias presentaciones para añadirlas en orden.",
        "labels.concat_confirm": "Crear presentación",
        "labels.deck_select_label": "Seleccionar presentación",
        "labels.deck_placeholder": "Seleccionar presentación",
        "labels.add_slide": "Añadir diapositiva",
        "labels.add_intro_slides": "Añadir título + aviso",
        "labels.delete_slide": "Eliminar diapositiva",
        "labels.import_slide": "Insertar desde una presentación",
        "labels.save_deck": "Guardar presentación",
        "labels.print_deck": "Exportar PDF",
        "labels.export_pptx": "Exportar PPTX",
        "labels.list_view": "Vista de lista",
        "labels.loading_status": "Cargando…",
        "labels.unsaved_changes": "Cambios sin guardar",
        "labels.storyboard_view": "Guion gráfico",
        "labels.storyboard_card_size": "Tamaño de las tarjetas",
        "labels.storyboard_mark_as_header": "Marcar como encabezado de sección",
        "labels.storyboard_empty_slide": "(diapositiva vacía)",
        "labels.storyboard_active_hint": "El guion gráfico está activo. Usa la cuadrícula para seleccionar y reordenar diapositivas.",
        "labels.add_section": "Añadir sección",
        "labels.sections_heading": "Secciones",
        "labels.section_fallback_title": "Sección {index}",
        "labels.section_header_prefix": "Encabezado",
        "labels.section_id_label": "ID",
        "labels.section_title_label": "Título",
        "labels.section_starts_at": "Empieza en",
        "labels.section_remove": "Eliminar",
        "labels.section_insert_header": "Insertar encabezado",
        "labels.section_use_selection_as_header": "Usar la selección como encabezado",
        "labels.section_add_subsection": "Añadir subsección",
        "labels.section_no_subsections": "Aún no hay subsecciones.",
        "labels.slides_heading": "Diapositivas",
        "labels.preview_label": "Vista previa de la diapositiva",
        "labels.title_label": "HTML del título",
        "labels.body_label": "HTML del contenido",
        "labels.notes_label": "Notas",
        "labels.notes_placeholder": "Añade una nota o un enlace (texto sin formato). Los enlaces siguen siendo clicables en las exportaciones.",
        "labels.import_dialog_title": "Insertar una diapositiva de otra presentación",
        "labels.import_dialog_close": "Cerrar",
        "labels.import_deck_label": "Presentación",
        "labels.import_deck_placeholder": "Selecciona una presentación",
        "tooltips.upload_deck": "Sube la carpeta completa de diapositivas HTML.",
        "tooltips.upload_zip_deck": "Sube una presentación empaquetada en formato .zip.",
        "tooltips.upload_pdf_deck": "Sube una presentación PDF para convertirla en diapositivas.",
        "tooltips.list_view": "Muestra las diapositivas como una lista.",
        "tooltips.storyboard_view": "Muestra las diapositivas en una cuadrícula de guion gráfico.",
        "tooltips.concat_decks": "Combina varias presentaciones en una sola presentación nueva.",
        "tooltips.print_deck": "Descarga una versión PDF de la presentación actual.",
        "tooltips.export_pptx": "Descarga una versión PPTX de la presentación actual.",
        "tooltips.add_slide": "Crea una diapositiva nueva justo después de la seleccionada.",
        "tooltips.add_intro_slides": "Inserta una diapositiva de título y otra de aviso al principio de la presentación.",
        "tooltips.delete_slide": "Elimina de esta presentación la diapositiva seleccionada.",
        "tooltips.import_slide": "Inserta una diapositiva de otra presentación después de la selección actual.",
        "tooltips.save_deck": "Guarda todos los cambios realizados en la presentación actual.",
        "tooltips.add_section": "Agrupa diapositivas relacionadas en secciones de navegación.",
        "tooltips.insert_header": "Inserta una diapositiva de encabezado de sección antes de la primera diapositiva del grupo.",
        "tooltips.use_selection_as_header": "Convierte la diapositiva seleccionada en el encabezado de esta sección.",
        "tooltips.add_subsection": "Crea una subsección que enlaza con una diapositiva concreta de esta sección.",
    },
    "check_entries": {
        "page_help": "Sube el diario, asigna las columnas clave, adjunta los PDF justificativos, ejecuta las comprobaciones automáticas y descarga los asientos señalados junto con el resumen de Excel.",
        "panels.upload.title": "Subir archivo de muestra",
        "panels.upload.subtitle": "Sube el extracto del libro mayor que se va a analizar.",
        "panels.mapping.title": "Asignación de columnas",
        "panels.mapping.subtitle": "Confirma qué columnas corresponden a los campos obligatorios.",
        "panels.pdf.title": "Subir PDF",
        "panels.pdf.subtitle": "Adjunta los documentos justificativos con los que se realizará la comparación.",
        "panels.parameters.title": "Configurar comprobaciones",
        "panels.parameters.subtitle": "Ajusta las tolerancias y las opciones de comparación de beneficiarios.",
        "panels.results.title": "Resultados",
        "panels.results.subtitle": "Revisa las discrepancias, descarga los informes y aplica correcciones.",
        "labels.select_journal": "Seleccionar archivo del diario",
        "labels.no_file": "Ningún archivo seleccionado",
        "labels.select_pdfs": "Seleccionar archivos PDF",
        "labels.no_files": "Ningún archivo seleccionado",
        "labels.files_selected": "{count} archivos seleccionados",
        "labels.contact_email": "Correo electrónico de contacto (opcional)",
        "labels.contact_email_placeholder": "nombre@ejemplo.com",
        "labels.contact_email_help": "La comprobación automática puede tardar desde unos minutos hasta varias horas. Te enviaremos un correo electrónico cuando termine la validación.",
        "labels.run_job_id": "ID de la tarea",
        "labels.run_job_link": "Enlace de estado",
        "labels.mapping_fields.movement_number": "Número de movimiento",
        "labels.mapping_fields.amount": "Importe",
        "labels.mapping_fields.debit_amount": "Importe del debe",
        "labels.mapping_fields.credit_amount": "Importe del haber",
        "labels.mapping_fields.date": "Fecha",
        "labels.mapping_fields.account": "Cuenta",
        "labels.mapping_fields.account_desc": "Descripción de la cuenta",
        "labels.mapping_fields.line_desc": "Descripción de la línea",
        "labels.mapping_fields.beneficiary": "Beneficiario",
        "labels.ocr_language": "Idioma de OCR",
        "labels.amount_tolerance": "Tolerancia del importe",
        "labels.date_window": "Intervalo de fechas (días)",
        "labels.timing_diff": "Diferencia temporal (días)",
        "labels.beneficiary_check": "Comprobación del beneficiario",
        "labels.beneficiary_similarity": "Similitud del beneficiario (%)",
        "labels.include_debug": "Incluir columnas de depuración en Excel",
        "labels.mismatches_title": "Discrepancias",
        "labels.download_pdf": "Descargar PDF",
        "labels.movement_title": "Movimiento {movement}",
        "labels.mismatch_option": "Discrepancia",
        "labels.ok_option": "Correcto",
        "labels.override_placeholder": "Motivo de la corrección (opcional)",
        "buttons.upload_file": "Subir archivo",
        "buttons.auto_map": "Asignar columnas automáticamente",
        "buttons.save_mapping": "Guardar asignación",
        "buttons.upload_pdfs": "Subir PDF",
        "buttons.run_checks": "Ejecutar comprobación automática",
        "buttons.cancel_job": "Cancelar comprobación",
        "buttons.copy_job_link": "Copiar enlace",
        "buttons.download_excel": "Descargar Excel",
        "buttons.download_summary": "Descargar resumen",
        "buttons.apply_review": "Aplicar revisión",
        "options.beneficiary_modes.compare": "Comparar",
        "options.beneficiary_modes.extract_only": "Solo extraer",
        "options.beneficiary_modes.off": "Desactivado",
        "messages.select_file_first": "Selecciona primero un archivo.",
        "messages.upload_status": "Se han cargado {rows} filas de {filename}.",
        "messages.upload_first": "Sube primero el diario.",
        "messages.auto_mapping_ok": "Se ha sugerido automáticamente la asignación de columnas.",
        "messages.mapping_saved": "Asignación guardada.",
        "messages.run_checks_needed": "Envía la asignación y los PDF antes de ejecutar la comprobación.",
        "messages.run_checks_init": "Ejecutando comprobaciones…",
        "messages.run_checks_done": "Comprobaciones completadas.",
        "messages.run_checks_pdfs": "Sube los archivos PDF justificativos antes de ejecutar la comprobación.",
        "messages.run_checks_failed": "La comprobación automática ha fallado. Inténtalo de nuevo.",
        "messages.run_checks_timeout": "La comprobación automática está tardando más de lo previsto. Inténtalo de nuevo dentro de unos minutos.",
        "messages.run_checks_batch_pending": "La comprobación automática se ha enviado como proceso por lotes. Puede tardar varias horas; te avisaremos por correo electrónico cuando termine.",
        "messages.run_checks_help": "Haz clic para ejecutar las comprobaciones. Pueden tardar desde unos minutos hasta varias horas.",
        "messages.run_checks_email_notice": "Te enviaremos un correo electrónico a {email} cuando terminen las comprobaciones. Puedes cerrar esta página.",
        "messages.run_checks_email_label": "tu dirección de acceso",
        "messages.run_checks_cancelled": "La comprobación automática se ha cancelado.",
        "messages.run_checks_leave_note": "Puedes cerrar esta página. Guarda el enlace anterior para reanudar el proceso o descargar los resultados más adelante.",
        "messages.run_job_link_copied": "Enlace de la tarea copiado.",
        "messages.pdf_download_failed": "Error al descargar el PDF",
        "messages.download_failed": "Error de descarga",
        "messages.review_first": "Ejecuta primero las comprobaciones.",
        "messages.select_pdfs_first": "Selecciona uno o varios archivos PDF.",
        "messages.pdfs_attached": "Se han adjuntado {count} PDF.",
    },
    "product_attributes": {
        "page_help": "Selecciona el retailer, la marca y la categoría, activa los filtros de atributos que te interesen y revisa o descarga los productos y variantes resultantes para centrar el análisis de atributos.",
        "labels.source": "Fuente",
        "labels.brand": "Marca",
        "labels.category": "Categoría",
        "labels.display_limit": "Elementos mostrados",
        "labels.rolling_months": "Meses móviles",
        "labels.show_all": "Mostrar todos los atributos",
        "record_types.parent": "Productos",
        "record_types.variant": "Variantes",
        "panels.attributes.title": "Filtros de atributos",
        "panels.attributes.subtitle_active": "Selecciona valores de atributos para refinar los resultados.",
        "panels.attributes.subtitle_wait": "Los atributos aparecerán cuando las categorías compartan campos comunes.",
        "panels.attributes.empty": "Las categorías seleccionadas no comparten ningún atributo.",
        "panels.sales_dimensions.title": "Dimensiones de atributos",
        "panels.sales_dimensions.subtitle": "Elige uno o varios atributos para analizar las ventas por dimensión.",
        "panels.sales_dimensions.label": "Seleccionar atributos",
        "panels.sales.summary": "Ventas: {sales} · Unidades: {units}",
        "panels.sales.empty": "No se han encontrado datos de ventas para los filtros actuales.",
        "panels.results.catalog_view": "Vista de catálogo",
        "panels.results.catalog_view_tooltip": "Ver productos filtrados.",
        "panels.results.sales_view": "Vista de ventas",
        "panels.results.sales_view_tooltip": "Analizar ventas por atributo.",
        "panels.results.toggle_show": "Mostrar tabla de datos",
        "panels.results.toggle_hide": "Ocultar tabla de datos",
        "panels.results.download_csv": "Descargar CSV",
        "panels.results.no_records": "Ningún registro coincide con los filtros seleccionados.",
        "pill.all_label": "Todos",
        "pill.no_options": "No hay opciones disponibles",
        "statuses.loading_retailers": "Cargando fuentes…",
        "statuses.loading_categories": "Cargando categorías…",
        "statuses.loading_brands": "Cargando marcas…",
        "statuses.loading_attributes": "Cargando filtros de atributos…",
        "statuses.loading_records": "Cargando registros…",
        "statuses.loading_sales": "Cargando ventas…",
        "records.summary_displaying": "Mostrando {count} de {total} {label}.",
        "records.summary_empty": "Aún no hay coincidencias.",
        "records.parent_label": "productos",
        "records.variant_label": "variantes",
        "records.parent_filename": "productos",
        "records.variant_filename": "variantes",
        "records.fallback_name": "Producto",
        "records.value_missing": "N/D",
        "records.image_alt": "Imagen del producto",
        "images.placeholder": "Imagen no disponible",
        "errors.request_failed": "La solicitud ha fallado ({status})",
        "errors.image_failed": "La solicitud de imagen ha fallado ({status})",
    },
    "report_builder": {
        "page_help": "Sube el libro de Excel exportado, confirma el tipo de informe detectado, revisa la asignación de secciones sugerida, añade el contexto necesario y genera y descarga el archivo DOCX.",
        "header_subtitle": "Sube los libros de Excel exportados, revisa las tablas detectadas, aporta contexto opcional y genera el informe DOCX.",
        "panels.upload.title": "Subir archivo",
        "panels.upload.subtitle": "Sube un archivo XLSX. Una tabla por hoja.",
        "panels.detection.title": "Tipo de informe",
        "panels.detection.subtitle": "Revisa la detección automática y ajústala si es necesario.",
        "panels.mapping.title": "Asignar tablas",
        "panels.mapping.subtitle": "Asigna cada sección de la plantilla a la hoja de Excel correspondiente.",
        "panels.context.title": "Notas de contexto",
        "panels.context.subtitle": "Añade observaciones manuales o sugerencias de edición que aparecerán en la narrativa.",
        "panels.build.title": "Generar y descargar",
        "panels.build.subtitle": "Genera el informe DOCX con la asignación y el contexto actuales.",
        "labels.ente": "Entidad",
        "labels.ente_placeholder": "Ayuntamiento de Ejemplo",
        "labels.year": "Año",
        "labels.contact_email": "Correo electrónico de contacto (opcional)",
        "labels.contact_email_placeholder": "nombre@ejemplo.com",
        "labels.zip_package": "Paquete ZIP",
        "labels.excel_workbook": "Archivo de Excel",
        "labels.select_zip": "Seleccionar archivo ZIP",
        "labels.select_excel": "Seleccionar archivo de Excel (.xlsx)",
        "labels.no_file": "Ningún archivo seleccionado",
        "labels.upload_hint": "Sube un XLSX con las tablas necesarias (una tabla por hoja).",
        "labels.report_type": "Tipo de informe",
        "labels.language_label": "Idioma",
        "labels.detection_confidence": "Confianza de la detección",
        "labels.unassigned_option": "— vacío —",
        "labels.context_empty": "Aún no hay notas de contexto. Añade una nota manual para aportar información adicional.",
        "labels.context_key": "Clave",
        "labels.context_value": "Nota",
        "labels.context_delete": "Eliminar",
        "labels.markdown_preview": "Vista previa de Markdown",
        "labels.analysis_preview": "Hallazgos detectados",
        "table_headers.section": "Sección",
        "table_headers.assigned_file": "Hoja asignada",
        "buttons.upload_detect": "Subir y detectar tablas",
        "buttons.reset_workflow": "Empezar de nuevo",
        "buttons.auto_map_tables": "Asignar tablas automáticamente",
        "buttons.save_mapping": "Guardar asignación",
        "buttons.add_context": "Añadir nota",
        "buttons.build_report": "Generar informe",
        "buttons.download_docx": "Descargar",
        "messages.confirm_new_session": "Al subir nuevos datos se iniciará una sesión nueva. ¿Quieres continuar?",
        "messages.uploading": "Subiendo…",
        "messages.processing_upload": "Procesando archivo…",
        "messages.provide_ente_year": "Indica tanto la entidad como el año.",
        "messages.both_files_error": "Sube un archivo ZIP o un libro de Excel, pero no ambos.",
        "messages.select_file_error": "Selecciona un archivo XLSX antes de subirlo.",
        "messages.invalid_excel": "Solo se admiten archivos .xlsx. Exporta o guarda el libro como XLSX.",
        "messages.upload_success": "{filename} se ha subido correctamente.",
        "messages.upload_failed": "La carga ha fallado.",
        "messages.switching_report_type": "Cambiando el tipo de informe…",
        "messages.report_type_updated": "Tipo de informe actualizado.",
        "messages.report_type_failed": "No se ha podido cambiar el tipo de informe.",
        "messages.mapping_auto_running": "Ejecutando la asignación automática…",
        "messages.mapping_auto_failed": "La asignación automática ha fallado.",
        "messages.mapping_saving": "Guardando la asignación de tablas…",
        "messages.mapping_saved": "Asignación actualizada.",
        "messages.mapping_save_failed": "No se ha podido guardar la asignación.",
        "messages.mapping_hint_auto": "Las tablas se han asignado automáticamente según los nombres de los archivos.",
        "messages.mapping_hint_manual": "Revisa y asigna las secciones manualmente si es necesario.",
        "messages.mapping_hidden_empty": "Las hojas vacías no se muestran en la asignación.",
        "messages.context_key_empty": "Las claves de contexto no pueden estar vacías.",
        "messages.context_key_exists": "La clave de contexto ya existe.",
        "messages.context_saving": "Guardando el contexto…",
        "messages.context_saved": "Contexto guardado.",
        "messages.context_save_failed": "No se ha podido guardar el contexto.",
        "messages.building": "Generando informe…",
        "messages.build_done": "Informe generado.",
        "messages.build_failed": "No se ha podido generar el informe.",
        "messages.build_enqueued": "La generación ha comenzado. Te enviaremos un enlace por correo electrónico cuando esté lista.",
    },
    "check_statements": {
        "page_help": "Sube los extractos bancarios y del libro mayor, asigna las columnas del libro mayor, ajusta la tolerancia y los intervalos de fechas y ejecuta la conciliación para revisar los movimientos sin conciliar y descargar el paquete de conciliación.",
        "panels.upload.title": "Subir archivos",
        "panels.upload.subtitle": "Proporciona los extractos bancarios y del libro mayor y, opcionalmente, una muestra de números de movimiento.",
        "panels.mapping.title": "Asignación del libro mayor",
        "panels.mapping.subtitle": "Confirma qué columnas del libro mayor contienen los identificadores y las descripciones de las cuentas.",
        "panels.parameters.title": "Parámetros",
        "panels.parameters.subtitle": "Ajusta la tolerancia y el intervalo de fechas y elige la cuenta del libro mayor que se va a conciliar.",
        "panels.results.title": "Resultados",
        "panels.results.subtitle": "Revisa las partidas sin conciliar, la cobertura por fase y descarga el paquete de conciliación.",
        "labels.bank_files": "Extractos bancarios",
        "labels.ledger_files": "Archivos del libro mayor",
        "labels.sample_file": "Muestra de movimientos (opcional)",
        "labels.select_bank": "Seleccionar archivos bancarios",
        "labels.select_ledger": "Seleccionar archivos del libro mayor",
        "labels.select_sample": "Seleccionar archivo de muestra",
        "labels.no_files": "Ningún archivo seleccionado",
        "labels.no_file": "Ningún archivo seleccionado",
        "labels.files_selected": "{count} archivos seleccionados",
        "labels.all_accounts": "Todas las cuentas",
        "labels.ledger_account": "Cuenta del libro mayor",
        "labels.ledger_account_desc": "Descripción de la cuenta del libro mayor",
        "labels.counter_account_desc": "Descripción de la contrapartida",
        "labels.extra_desc": "Descripción adicional",
        "labels.amount_tolerance": "Tolerancia del importe",
        "labels.date_window": "Intervalo de fechas (días)",
        "labels.account_select": "Cuenta del libro mayor",
        "labels.download_excel": "Descargar Excel",
        "labels.summary_stage": "Resumen por fase",
        "labels.summary_balanced": "Grupos conciliados",
        "labels.summary_bank_buckets": "Grupos bancarios",
        "labels.summary_ledger_buckets": "Grupos del libro mayor",
        "labels.summary_unmatched_bank": "Asientos bancarios sin conciliar (tras el filtrado)",
        "labels.summary_unmatched_ledger": "Asientos del libro mayor sin conciliar",
        "labels.summary_evidence": "Ejemplos de justificantes",
        "labels.summary_labels.unmatched_bank_raw": "Banco sin conciliar (bruto)",
        "labels.summary_labels.unmatched_bank_filtered": "Banco sin conciliar (filtrado)",
        "labels.summary_labels.unmatched_bank_total": "Total bancario sin conciliar",
        "labels.summary_labels.unmatched_ledger": "Libro mayor sin conciliar",
        "labels.summary_labels.unmatched_ledger_total": "Total del libro mayor sin conciliar",
        "labels.summary_labels.bank_drop": "Exclusiones preliminares no transaccionales",
        "labels.sample_filter.title": "Filtro de muestra",
        "labels.sample_filter.default_message": "Archivo de muestra procesado.",
        "labels.sample_filter.movements_detected": "{count} movimientos detectados",
        "labels.sample_filter.matched_template": "Se han conciliado {matched} movimientos de {total}.",
        "buttons.upload": "Subir archivos",
        "buttons.save_mapping": "Guardar asignación",
        "buttons.run": "Ejecutar conciliación",
        "buttons.download_excel": "Descargar Excel",
        "messages.upload_requirement": "Sube al menos un archivo bancario y uno del libro mayor.",
        "messages.files_uploaded": "Los archivos se han subido correctamente.",
        "messages.upload_first": "Sube primero los archivos.",
        "messages.mapping_saved": "Asignación guardada.",
        "messages.reconciliation_done": "Conciliación completada.",
        "messages.run_before_download": "Ejecuta la conciliación antes de descargar.",
        "messages.download_failed": "Error de descarga",
    },
    "presentations": {
        "page_help": "Consulta nuestras presentaciones y documentos PDF compartidos.",
        "form.title": "Introduce el token del proyecto",
        "form.label": "Proporciona el token para continuar.",
        "form.placeholder": "Token del proyecto",
        "form.button": "Continuar",
        "form.toggle_show": "Mostrar",
        "form.toggle_hide": "Ocultar",
        "form.error": "Token no válido. Inténtalo de nuevo.",
        "buttons.hand_bikes": "Bicicletas de mano",
        "buttons.combined_bikes": "Oportunidad de e-bikes",
        "buttons.setting_category_transformation": "transformación de la categoría de referencia",
        "buttons.print_deck": "Imprimir PDF",
        "buttons.export_pptx": "Exportar PPTX",
    },
    "launch_reports": {
        "page_help": "Explora las señales de retailers para ver qué combinaciones de atributos parecen ganadoras, emergentes o sobrerrepresentadas en el entorno del retailer.",
        "validation_status_checked": "La comprobación automática no ha encontrado elementos que requieran cautela.",
        "validation_status_noted": "La comprobación automática solo ha encontrado notas de cautela.",
        "validation_status_caution": "La comprobación automática ha encontrado elementos que deben revisarse.",
        "validation_status_unknown": "Se desconoce el estado de la validación automática; la mayoría de las unidades de texto del informe siguen sin resolver.",
        "validation_status_unknown_short": "desconocido",
        "validation_status_summary": "La comprobación automática del paquete no se aplica a este informe resumido.",
        "validation_status_pending": "La comprobación automática aún no está disponible.",
    },
    "brand_reports": {
        "page_help": "Usa los informes de afinidad de marca para ver qué señales del retailer ya cubre la marca y dónde puede seguir habiendo oportunidades de producto relevantes para el retailer.",
    },
    "product_hypotheses": {
        "page_help": "Explora hipótesis de producto derivadas de las señales de retailers y la afinidad de marca.",
    },
}
