from __future__ import annotations

__all__ = [
    "ATTRIBUTE_EMERGING_MAX_START_SHARE_PCT",
    "ATTRIBUTE_EMERGING_MIN_DELTA_PP",
    "ATTRIBUTE_EMERGING_MIN_END_SHARE_PCT",
    "ATTRIBUTE_POLARIZATION_MIN_DECLINER_DELTA_PP",
    "ATTRIBUTE_POLARIZATION_MIN_GAINER_DELTA_PP",
    "ATTRIBUTE_POLARIZATION_MIN_START_SHARE_PCT",
    "ATTRIBUTE_SHARE_SHIFT_MIN_DELTA_PP",
    "BRAND_CHALLENGER_MIN_DELTA_PP",
    "BRAND_CHALLENGER_MIN_END_SHARE_PCT",
    "BRAND_LEADER_MIN_SHARE_PCT",
    "BRAND_REDISTRIBUTION_MIN_TOTAL_PP",
    "BRIEF_SERIALIZED_MAX_BULLETS",
    "BRIEF_SERIALIZED_MAX_METRICS",
    "BRIEF_SUPPRESS_VOLATILITY_WHEN_STRUCTURAL_GROWTH",
    "BRIEF_UNSIGNED_PP_METRIC_KEYS",
    "DEFAULT_BRIEF_HIGHLIGHT_COUNT",
    "DEFAULT_BRIEF_MAX_FINDINGS",
    "DEFAULT_BRIEF_MAX_PER_LENS",
    "DEFAULT_DECK_PLAN_MAX_SLIDES",
    "DEFAULT_SHORTLIST_MAX_FINDINGS",
    "DEFAULT_SHORTLIST_MAX_PER_LENS",
    "DECK_PLAN_MAX_BULLETS_PER_SLIDE",
    "DECK_PLAN_MAX_SUMMARY_BULLETS",
    "DECK_PLAN_MAX_SUPPORTING_FINDINGS_PER_SLIDE",
    "FINDING_SCORE_HIGH_THRESHOLD",
    "FINDING_SCORE_MEDIUM_THRESHOLD",
    "GROWTH_LEVEL_SHIFT_MIN_RELATIVE_CHANGE",
    "GROWTH_SUSTAINED_MIN_DIRECTION_RATIO",
    "GROWTH_SUSTAINED_MIN_RELATIVE_CHANGE",
    "GROWTH_VOLATILITY_MIN_OBSERVATIONS",
    "GROWTH_VOLATILITY_MIN_SPIKE_RATIO",
    "PRICE_MID_SHIFT_MAX_VALUE_DELTA_PP",
    "PRICE_MID_SHIFT_MIN_MID_DELTA_PP",
    "PRICE_PREMIUMIZATION_MAX_VALUE_DELTA_PP",
    "PRICE_PREMIUMIZATION_MIN_PREMIUM_DELTA_PP",
    "PRICE_STRUCTURE_DOMINANT_MIN_DELTA_PP",
    "PRICE_VALUE_SHIFT_MAX_PREMIUM_DELTA_PP",
    "PRICE_VALUE_SHIFT_MIN_VALUE_DELTA_PP",
    "SALES_BRIEF_MAX_ATTRIBUTE_DIMENSIONS",
    "SALES_BRIEF_MIN_ATTRIBUTE_COVERAGE",
    "SALES_BRIEF_MIN_DISTINCT_VALUES",
    "SALES_BRIEF_PREFERRED_ATTRIBUTE_IDS",
]


SALES_BRIEF_PREFERRED_ATTRIBUTE_IDS = ("coverage", "form", "finish")
SALES_BRIEF_MAX_ATTRIBUTE_DIMENSIONS = 3
SALES_BRIEF_MIN_ATTRIBUTE_COVERAGE = 0.7
SALES_BRIEF_MIN_DISTINCT_VALUES = 3

DEFAULT_SHORTLIST_MAX_FINDINGS = 6
DEFAULT_SHORTLIST_MAX_PER_LENS = 2
DEFAULT_BRIEF_MAX_FINDINGS = 8
DEFAULT_BRIEF_MAX_PER_LENS = 3
DEFAULT_BRIEF_HIGHLIGHT_COUNT = 3
DEFAULT_DECK_PLAN_MAX_SLIDES = 6
DECK_PLAN_MAX_BULLETS_PER_SLIDE = 3
DECK_PLAN_MAX_SUMMARY_BULLETS = 3
DECK_PLAN_MAX_SUPPORTING_FINDINGS_PER_SLIDE = 2

FINDING_SCORE_HIGH_THRESHOLD = 0.75
FINDING_SCORE_MEDIUM_THRESHOLD = 0.45

GROWTH_LEVEL_SHIFT_MIN_RELATIVE_CHANGE = 0.15
GROWTH_SUSTAINED_MIN_RELATIVE_CHANGE = 0.10
GROWTH_SUSTAINED_MIN_DIRECTION_RATIO = 0.6
GROWTH_VOLATILITY_MIN_OBSERVATIONS = 6
GROWTH_VOLATILITY_MIN_SPIKE_RATIO = 1.35

BRAND_LEADER_MIN_SHARE_PCT = 8.0
BRAND_CHALLENGER_MIN_DELTA_PP = 4.0
BRAND_CHALLENGER_MIN_END_SHARE_PCT = 3.0
BRAND_REDISTRIBUTION_MIN_TOTAL_PP = 8.0

ATTRIBUTE_SHARE_SHIFT_MIN_DELTA_PP = 5.0
ATTRIBUTE_EMERGING_MIN_DELTA_PP = 4.0
ATTRIBUTE_EMERGING_MAX_START_SHARE_PCT = 10.0
ATTRIBUTE_EMERGING_MIN_END_SHARE_PCT = 5.0
ATTRIBUTE_POLARIZATION_MIN_GAINER_DELTA_PP = 3.0
ATTRIBUTE_POLARIZATION_MIN_DECLINER_DELTA_PP = -3.0
ATTRIBUTE_POLARIZATION_MIN_START_SHARE_PCT = 10.0

PRICE_PREMIUMIZATION_MIN_PREMIUM_DELTA_PP = 4.0
PRICE_PREMIUMIZATION_MAX_VALUE_DELTA_PP = -3.0
PRICE_VALUE_SHIFT_MIN_VALUE_DELTA_PP = 4.0
PRICE_VALUE_SHIFT_MAX_PREMIUM_DELTA_PP = -3.0
PRICE_MID_SHIFT_MIN_MID_DELTA_PP = 5.0
PRICE_MID_SHIFT_MAX_VALUE_DELTA_PP = -3.0
PRICE_STRUCTURE_DOMINANT_MIN_DELTA_PP = 4.0

BRIEF_SERIALIZED_MAX_METRICS = 3
BRIEF_SERIALIZED_MAX_BULLETS = 2
BRIEF_SUPPRESS_VOLATILITY_WHEN_STRUCTURAL_GROWTH = True
BRIEF_UNSIGNED_PP_METRIC_KEYS = (
    "total_redistribution_pp",
    "largest_brand_move_pp",
)
