"""Localized INPS memo labels; supplied evidence and conclusions are unchanged."""

from __future__ import annotations

__all__ = ["MEMO_TEXT"]

MEMO_TEXT: dict[str, dict[str, str]] = {
    "it": {
        "title": "Verifica della posizione contributiva INPS",
        "draft": "BOZZA PER REVISIONE PROFESSIONALE",
        "scope": "Perimetro",
        "question": "Quesito",
        "facts": "Fatti documentati",
        "timeline": "Cronologia esplicita",
        "fact_refs": "fatti",
        "no_events": "Nessun evento cronologico esplicito registrato.",
        "conclusions": "Conclusioni sottoposte a verifica delle fonti",
        "support": "Supporto",
        "reasoning": "Ragionamento",
        "uncertainty": "Incertezza o correzione",
        "none": "Nessuna indicata.",
        "sources": "Fonti",
        "dependencies": "Fatti dipendenti",
        "calculations": "Ricalcoli approvati",
        "not_calculated": "non calcolato",
        "no_calculations": "Nessun ricalcolo approvato incluso.",
        "missing": "Evidenze o chiarimenti mancanti",
        "no_missing": "Nessuna richiesta aggiuntiva registrata; il professionista deve comunque confermare la completezza del fascicolo.",
        "limits": "Limiti e responsabilità",
        "requests": "Richieste di documenti e chiarimenti",
        "confirmed": "confermato",
        "pending": "da rivedere",
        "supported": "supportato dalle fonti",
        "partially_supported": "parzialmente supportato",
        "not_supported": "non supportato",
        "contradicted": "contraddetto dalle fonti",
        "uncertain": "incerto",
        "passed": "controlli superati",
        "introduction": "Il documento organizza evidenze, ricerca e ricalcoli. Non costituisce un parere professionale. Può includere evidenze locali, esportazioni ufficiali o, solo dopo separata verifica del permesso del servizio, una cattura in sola lettura di una scheda INPS già autenticata; non gestisce credenziali, non attiva deleghe e non autorizza invii o adempimenti.",
        "model_review": "La selezione del quadro giuridico, delle fonti e delle conclusioni è stata svolta con ragionamento del modello e deve essere verificata dal professionista.",
        "mechanical_scope": "Gli script hanno controllato soltanto forma, provenienza, riferimenti e aritmetica esplicitamente approvata.",
        "no_inference": "Nessuna classificazione, aliquota, prescrizione o scadenza è stata scelta automaticamente.",
        "review_state": "Stato del documento: **pronto per revisione professionale**, non firmato e non depositabile.",
    },
    "en": {
        "title": "Review of the INPS contribution record",
        "draft": "DRAFT FOR PROFESSIONAL REVIEW",
        "scope": "Scope",
        "question": "Professional question",
        "facts": "Documented facts",
        "timeline": "Documented chronology",
        "fact_refs": "facts",
        "no_events": "No explicit chronological events recorded.",
        "conclusions": "Conclusions checked against sources",
        "support": "Source support",
        "reasoning": "Reasoning review",
        "uncertainty": "Uncertainty or correction",
        "none": "None recorded.",
        "sources": "Sources",
        "dependencies": "Supporting facts",
        "calculations": "Approved recalculations",
        "not_calculated": "not calculated",
        "no_calculations": "No approved recalculation included.",
        "missing": "Missing evidence or clarifications",
        "no_missing": "No additional request recorded; the professional must still confirm that the case file is complete.",
        "limits": "Limits and responsibilities",
        "requests": "Document and clarification requests",
        "confirmed": "confirmed",
        "pending": "pending review",
        "supported": "supported by sources",
        "partially_supported": "partially supported",
        "not_supported": "not supported",
        "contradicted": "contradicted by sources",
        "uncertain": "uncertain",
        "passed": "checks passed",
        "introduction": "This document brings together evidence, research and recalculations for professional review. It is not a professional opinion. Sources may include local documents, official exports or, only after separately checking the service permission, a read-only capture of an already authenticated INPS tab. The workflow does not handle credentials, activate delegations or authorise submissions.",
        "model_review": "The model selected the legal framework, sources and conclusions through reasoning; the professional must verify them.",
        "mechanical_scope": "The scripts checked only structure, provenance, references and explicitly approved arithmetic.",
        "no_inference": "No classification, contribution rate, limitation period or deadline was selected automatically.",
        "review_state": "Document status: **ready for professional review**, unsigned and not ready for submission.",
    },
    "fr": {
        "title": "Examen du relevé de cotisations INPS",
        "draft": "PROJET POUR REVUE PROFESSIONNELLE",
        "scope": "Périmètre",
        "question": "Question professionnelle",
        "facts": "Faits documentés",
        "timeline": "Chronologie documentée",
        "fact_refs": "faits",
        "no_events": "Aucun événement chronologique explicite enregistré.",
        "conclusions": "Conclusions examinées au regard des sources",
        "support": "Appui des sources",
        "reasoning": "Examen du raisonnement",
        "uncertainty": "Incertitude ou correction",
        "none": "Aucune indiquée.",
        "sources": "Sources",
        "dependencies": "Faits à l’appui",
        "calculations": "Recalculs approuvés",
        "not_calculated": "non calculé",
        "no_calculations": "Aucun recalcul approuvé inclus.",
        "missing": "Éléments ou précisions manquants",
        "no_missing": "Aucune demande supplémentaire enregistrée ; le professionnel doit néanmoins confirmer que le dossier est complet.",
        "limits": "Limites et responsabilités",
        "requests": "Demandes de documents et de précisions",
        "confirmed": "confirmé",
        "pending": "à revoir",
        "supported": "étayé par les sources",
        "partially_supported": "partiellement étayé",
        "not_supported": "non étayé",
        "contradicted": "contredit par les sources",
        "uncertain": "incertain",
        "passed": "contrôles réussis",
        "introduction": "Ce document réunit les éléments probants, la recherche et les recalculs pour une revue professionnelle. Il ne constitue pas un avis professionnel. Il peut inclure des documents locaux, des exports officiels ou, uniquement après vérification distincte de l’autorisation du service, une capture en lecture seule d’un onglet INPS déjà authentifié. Le workflow ne gère pas les identifiants, n’active pas de délégation et n’autorise aucun dépôt.",
        "model_review": "Le modèle a sélectionné le cadre juridique, les sources et les conclusions par raisonnement ; le professionnel doit les vérifier.",
        "mechanical_scope": "Les scripts ont uniquement contrôlé la forme, la provenance, les références et les calculs expressément approuvés.",
        "no_inference": "Aucune classification, aucun taux, délai de prescription ou échéance n’a été sélectionné automatiquement.",
        "review_state": "État du document : **prêt pour revue professionnelle**, non signé et non prêt au dépôt.",
    },
    "de": {
        "title": "Prüfung des INPS Beitragskontos",
        "draft": "ENTWURF ZUR FACHLICHEN PRÜFUNG",
        "scope": "Umfang",
        "question": "Fachliche Frage",
        "facts": "Dokumentierte Tatsachen",
        "timeline": "Dokumentierte Chronologie",
        "fact_refs": "Tatsachen",
        "no_events": "Keine ausdrücklich dokumentierten zeitlichen Ereignisse.",
        "conclusions": "Anhand der Quellen geprüfte Schlussfolgerungen",
        "support": "Quellenbeleg",
        "reasoning": "Prüfung der Begründung",
        "uncertainty": "Unsicherheit oder Korrektur",
        "none": "Keine angegeben.",
        "sources": "Quellen",
        "dependencies": "Zugrunde liegende Tatsachen",
        "calculations": "Freigegebene Nachberechnungen",
        "not_calculated": "nicht berechnet",
        "no_calculations": "Keine freigegebene Nachberechnung enthalten.",
        "missing": "Fehlende Belege oder Klärungen",
        "no_missing": "Keine zusätzliche Anforderung erfasst; die Vollständigkeit der Akte ist weiterhin fachlich zu bestätigen.",
        "limits": "Grenzen und Verantwortlichkeiten",
        "requests": "Anforderungen von Unterlagen und Klärungen",
        "confirmed": "bestätigt",
        "pending": "noch zu prüfen",
        "supported": "durch Quellen gestützt",
        "partially_supported": "teilweise gestützt",
        "not_supported": "nicht gestützt",
        "contradicted": "durch Quellen widerlegt",
        "uncertain": "ungewiss",
        "passed": "Prüfungen bestanden",
        "introduction": "Dieses Dokument führt Belege, Recherche und Nachberechnungen zur fachlichen Prüfung zusammen. Es ist kein Fachgutachten. Quellen können lokale Unterlagen, offizielle Exporte oder – erst nach gesonderter Prüfung der Berechtigung des Dienstes – eine schreibgeschützte Erfassung eines bereits angemeldeten INPS-Tabs umfassen. Der Ablauf verwaltet keine Zugangsdaten, aktiviert keine Vollmachten und erlaubt keine Einreichungen.",
        "model_review": "Das Modell hat Rechtsrahmen, Quellen und Schlussfolgerungen durch Begründung ausgewählt; diese bedürfen fachlicher Prüfung.",
        "mechanical_scope": "Die Skripte prüften nur Struktur, Herkunft, Referenzen und ausdrücklich freigegebene Berechnungen.",
        "no_inference": "Keine Einstufung, kein Beitragssatz, keine Verjährungsfrist und keine Frist wurde automatisch gewählt.",
        "review_state": "Dokumentenstatus: **bereit zur fachlichen Prüfung**, nicht unterzeichnet und nicht einreichungsbereit.",
    },
    "es": {
        "title": "Revisión del registro de cotizaciones INPS",
        "draft": "BORRADOR PARA REVISIÓN PROFESIONAL",
        "scope": "Alcance",
        "question": "Cuestión profesional",
        "facts": "Hechos documentados",
        "timeline": "Cronología explícita",
        "fact_refs": "hechos",
        "no_events": "No se ha registrado ningún evento cronológico explícito.",
        "conclusions": "Conclusiones sujetas a verificación de fuentes",
        "support": "Soporte",
        "reasoning": "Revisión del razonamiento",
        "uncertainty": "Incertidumbre o corrección",
        "none": "No se ha indicado ninguna.",
        "sources": "Fuentes",
        "dependencies": "Hechos de los que depende",
        "calculations": "Recálculos aprobados",
        "not_calculated": "no calculado",
        "no_calculations": "No se ha incluido ningún recálculo aprobado.",
        "missing": "Evidencias o aclaraciones pendientes",
        "no_missing": "No se ha registrado ninguna solicitud adicional; el profesional debe confirmar en todo caso que el expediente está completo.",
        "limits": "Límites y responsabilidades",
        "requests": "Solicitudes de documentos y aclaraciones",
        "confirmed": "confirmado",
        "pending": "pendiente de revisión",
        "supported": "respaldado por fuentes",
        "partially_supported": "parcialmente respaldado",
        "not_supported": "no respaldado",
        "contradicted": "contradicho por fuentes",
        "uncertain": "incierto",
        "passed": "controles superados",
        "introduction": "Este documento organiza evidencias, investigación y recálculos. No constituye un dictamen profesional. Puede incluir evidencias locales, exportaciones oficiales o, solo después de verificar por separado el permiso del servicio, una captura de solo lectura de una pestaña INPS ya autenticada; no gestiona credenciales, no activa delegaciones y no autoriza presentaciones ni trámites.",
        "model_review": "La selección del marco jurídico, de las fuentes y de las conclusiones se ha realizado con razonamiento del modelo y debe ser verificada por el profesional.",
        "mechanical_scope": "Los scripts solo han comprobado la forma, la procedencia, las referencias y la aritmética aprobada de manera explícita.",
        "no_inference": "No se ha elegido automáticamente ninguna clasificación, tipo de cotización, plazo de prescripción o fecha límite.",
        "review_state": "Estado del documento: **listo para revisión profesional**, sin firma y no apto para presentación.",
    },
}
