"""Human-readable labels for existing Concordato fields; no semantic decisions."""

from __future__ import annotations

__all__ = ["display_label"]

LABELS: dict[str, dict[str, str]] = {
    "debtor": {
        "it": "Debitore",
        "en": "Debtor",
        "fr": "Débiteur",
        "de": "Schuldner",
        "es": "Deudor",
    },
    "court": {
        "it": "Tribunale",
        "en": "Court",
        "fr": "Tribunal",
        "de": "Gericht",
        "es": "Tribunal",
    },
    "procedure_reference": {
        "it": "Riferimento della procedura",
        "en": "Procedure reference",
        "fr": "Référence de la procédure",
        "de": "Verfahrensreferenz",
        "es": "Referencia del procedimiento",
    },
    "stage": {
        "it": "Fase",
        "en": "Stage",
        "fr": "Étape",
        "de": "Verfahrensstand",
        "es": "Fase",
    },
    "plan_type": {
        "it": "Tipo di piano",
        "en": "Plan type",
        "fr": "Type de plan",
        "de": "Planart",
        "es": "Tipo de plan",
    },
    "reference_date": {
        "it": "Data di riferimento",
        "en": "Reference date",
        "fr": "Date de référence",
        "de": "Stichtag",
        "es": "Fecha de referencia",
    },
    "metric": {
        "it": "Indicatore",
        "en": "Measure",
        "fr": "Indicateur",
        "de": "Kennzahl",
        "es": "Indicador",
    },
    "value": {
        "it": "Valore",
        "en": "Value",
        "fr": "Valeur",
        "de": "Wert",
        "es": "Valor",
    },
    "assessment": {
        "it": "Valutazione",
        "en": "Assessment",
        "fr": "Évaluation",
        "de": "Beurteilung",
        "es": "Evaluación",
    },
    "judgment_basis": {
        "it": "Motivo della valutazione",
        "en": "Assessment basis",
        "fr": "Motif de l’évaluation",
        "de": "Beurteilungsgrundlage",
        "es": "Fundamento de la evaluación",
    },
    "evidence_refs": {
        "it": "Riferimenti ai documenti",
        "en": "Document references",
        "fr": "Références documentaires",
        "de": "Belegstellen",
        "es": "Referencias documentales",
    },
    "follow_up": {
        "it": "Passo successivo",
        "en": "Follow-up",
        "fr": "Suite à donner",
        "de": "Nächster Schritt",
        "es": "Paso siguiente",
    },
    "severity": {
        "it": "Priorità",
        "en": "Severity",
        "fr": "Gravité",
        "de": "Schweregrad",
        "es": "Gravedad",
    },
    "status": {
        "it": "Stato",
        "en": "Status",
        "fr": "État",
        "de": "Status",
        "es": "Estado",
    },
    "next_action": {
        "it": "Azione successiva",
        "en": "Next action",
        "fr": "Prochaine action",
        "de": "Nächste Maßnahme",
        "es": "Siguiente acción",
    },
    "candidate_count": {
        "it": "Importi del piano da confrontare",
        "en": "Plan amounts to compare",
        "fr": "Montants du plan à rapprocher",
        "de": "Abzugleichende Planbeträge",
        "es": "Importes del plan para comparar",
    },
    "match_count": {
        "it": "Corrispondenze di importo da verificare",
        "en": "Amount matches to review",
        "fr": "Concordances de montants à vérifier",
        "de": "Zu prüfende Betragsübereinstimmungen",
        "es": "Coincidencias de importes para revisar",
    },
    "numeric_limit": {
        "it": "Importi uguali sono solo possibili riscontri: occorre verificarne il significato nel contesto.",
        "en": "Equal amounts are possible matches only; their meaning needs contextual review.",
        "fr": "Des montants égaux ne constituent que des concordances possibles ; leur sens doit être vérifié dans le contexte.",
        "de": "Gleiche Beträge sind nur mögliche Übereinstimmungen; ihre Bedeutung ist im Zusammenhang zu prüfen.",
        "es": "Los importes iguales son solo coincidencias posibles; su significado requiere revisión en contexto.",
    },
    "creditor_count": {
        "it": "Numero di creditori",
        "en": "Number of creditors",
        "fr": "Nombre de créanciers",
        "de": "Anzahl der Gläubiger",
        "es": "Número de acreedores",
    },
    "class_count": {
        "it": "Numero di classi",
        "en": "Number of classes",
        "fr": "Nombre de classes",
        "de": "Anzahl der Klassen",
        "es": "Número de clases",
    },
    "total_claim_amount": {
        "it": "Crediti complessivi",
        "en": "Total claims",
        "fr": "Total des créances",
        "de": "Forderungen insgesamt",
        "es": "Créditos totales",
    },
    "total_proposed_cash_amount": {
        "it": "Pagamenti monetari proposti",
        "en": "Proposed cash payments",
        "fr": "Paiements monétaires proposés",
        "de": "Vorgeschlagene Geldzahlungen",
        "es": "Pagos monetarios propuestos",
    },
    "total_proposed_non_cash_amount": {
        "it": "Attribuzioni non monetarie proposte",
        "en": "Proposed non-cash recovery",
        "fr": "Attributions non monétaires proposées",
        "de": "Vorgeschlagene nicht monetäre Befriedigung",
        "es": "Recuperación no monetaria propuesta",
    },
    "total_proposed_recovery_amount": {
        "it": "Soddisfacimento complessivo proposto",
        "en": "Total proposed recovery",
        "fr": "Recouvrement total proposé",
        "de": "Vorgeschlagene Befriedigung insgesamt",
        "es": "Recuperación total propuesta",
    },
    "total_proposed_recovery_pct": {
        "it": "Soddisfacimento proposto (%)",
        "en": "Proposed recovery (%)",
        "fr": "Recouvrement proposé (%)",
        "de": "Vorgeschlagene Befriedigung (%)",
        "es": "Recuperación propuesta (%)",
    },
    "total_liquidation_recovery_amount": {
        "it": "Soddisfacimento in liquidazione",
        "en": "Liquidation recovery",
        "fr": "Recouvrement en liquidation",
        "de": "Befriedigung bei Liquidation",
        "es": "Recuperación en liquidación",
    },
    "total_liquidation_recovery_pct": {
        "it": "Soddisfacimento in liquidazione (%)",
        "en": "Liquidation recovery (%)",
        "fr": "Recouvrement en liquidation (%)",
        "de": "Befriedigung bei Liquidation (%)",
        "es": "Recuperación en liquidación (%)",
    },
    "plan_vs_liquidation_delta": {
        "it": "Differenza piano rispetto alla liquidazione",
        "en": "Plan less liquidation recovery",
        "fr": "Écart du plan par rapport à la liquidation",
        "de": "Differenz zwischen Plan und Liquidation",
        "es": "Diferencia del plan respecto a la liquidación",
    },
    "source_total": {
        "it": "Totale fonti",
        "en": "Total funding sources",
        "fr": "Total des ressources",
        "de": "Mittelherkunft insgesamt",
        "es": "Total de fuentes",
    },
    "use_total": {
        "it": "Totale impieghi",
        "en": "Total uses of funds",
        "fr": "Total des emplois",
        "de": "Mittelverwendung insgesamt",
        "es": "Total de aplicaciones",
    },
    "surplus_shortfall": {
        "it": "Eccedenza o insufficienza delle fonti",
        "en": "Funding surplus or shortfall",
        "fr": "Excédent ou insuffisance des ressources",
        "de": "Mittelüberschuss oder Fehlbetrag",
        "es": "Excedente o insuficiencia de fondos",
    },
    "funding_gap": {
        "it": "Impieghi meno fonti",
        "en": "Uses less funding sources",
        "fr": "Emplois moins ressources",
        "de": "Mittelverwendung abzüglich Mittelherkunft",
        "es": "Aplicaciones menos fuentes",
    },
    "minimum_reported_closing_cash": {
        "it": "Liquidità finale minima riportata",
        "en": "Minimum reported closing cash",
        "fr": "Trésorerie finale minimale déclarée",
        "de": "Niedrigster ausgewiesener Liquiditätsendbestand",
        "es": "Tesorería final mínima indicada",
    },
    "open_issue_count": {
        "it": "Questioni ancora aperte",
        "en": "Open issues",
        "fr": "Points encore ouverts",
        "de": "Offene Punkte",
        "es": "Cuestiones pendientes",
    },
    "open_critical_high_issue_count": {
        "it": "Questioni aperte critiche o alte",
        "en": "Open critical or high issues",
        "fr": "Points ouverts critiques ou importants",
        "de": "Offene kritische oder schwerwiegende Punkte",
        "es": "Cuestiones pendientes críticas o graves",
    },
    "procedure_identity": {
        "it": "Identificazione della procedura",
        "en": "Procedure identification",
        "fr": "Identification de la procédure",
        "de": "Verfahrensidentifikation",
        "es": "Identificación del procedimiento",
    },
    "proposal_plan_consistency": {
        "it": "Coerenza di proposta e piano",
        "en": "Proposal and plan consistency",
        "fr": "Cohérence de la proposition et du plan",
        "de": "Konsistenz von Vorschlag und Plan",
        "es": "Coherencia de propuesta y plan",
    },
    "document_perimeter": {
        "it": "Documentazione",
        "en": "Document coverage",
        "fr": "Périmètre documentaire",
        "de": "Dokumentenumfang",
        "es": "Documentación",
    },
    "creditor_perimeter": {
        "it": "Perimetro dei creditori",
        "en": "Creditor coverage",
        "fr": "Périmètre des créanciers",
        "de": "Gläubigerkreis",
        "es": "Perímetro de acreedores",
    },
    "creditor_treatment": {
        "it": "Trattamento dei creditori",
        "en": "Creditor treatment",
        "fr": "Traitement des créanciers",
        "de": "Gläubigerbehandlung",
        "es": "Tratamiento de acreedores",
    },
    "voting_homologation": {
        "it": "Voto e omologazione",
        "en": "Voting and court confirmation",
        "fr": "Vote et homologation",
        "de": "Abstimmung und gerichtliche Bestätigung",
        "es": "Votación y homologación",
    },
    "liquidation_alternative": {
        "it": "Alternativa liquidatoria",
        "en": "Liquidation alternative",
        "fr": "Alternative liquidative",
        "de": "Liquidationsalternative",
        "es": "Alternativa liquidatoria",
    },
    "feasibility_liquidity": {
        "it": "Fattibilità e liquidità",
        "en": "Feasibility and liquidity",
        "fr": "Faisabilité et liquidité",
        "de": "Durchführbarkeit und Liquidität",
        "es": "Viabilidad y liquidez",
    },
    "attestation": {
        "it": "Attestazione",
        "en": "Plan attestation",
        "fr": "Attestation du plan",
        "de": "Planbescheinigung",
        "es": "Atestación del plan",
    },
    "accounting_consistency": {
        "it": "Coerenza contabile",
        "en": "Accounting consistency",
        "fr": "Cohérence comptable",
        "de": "Konsistenz der Rechnungslegung",
        "es": "Coherencia contable",
    },
    "tax_social_security": {
        "it": "Tributi e contributi",
        "en": "Tax and social security",
        "fr": "Fiscalité et cotisations sociales",
        "de": "Steuern und Sozialbeiträge",
        "es": "Tributos y cotizaciones",
    },
    "continuity_economics": {
        "it": "Economia della continuità",
        "en": "Going-concern economics",
        "fr": "Économie de la poursuite d’activité",
        "de": "Wirtschaftlichkeit der Fortführung",
        "es": "Economía de la continuidad",
    },
    "sources_and_uses": {
        "it": "Fonti e impieghi",
        "en": "Sources and uses",
        "fr": "Ressources et emplois",
        "de": "Mittelherkunft und Verwendung",
        "es": "Fuentes y aplicaciones",
    },
    "milestones": {
        "it": "Tappe del piano",
        "en": "Plan milestones",
        "fr": "Étapes du plan",
        "de": "Planmeilensteine",
        "es": "Hitos del plan",
    },
    "other": {
        "it": "Altro",
        "en": "Other",
        "fr": "Autre",
        "de": "Sonstiges",
        "es": "Otro",
    },
    "addressed": {
        "it": "Trattato",
        "en": "Addressed",
        "fr": "Traité",
        "de": "Behandelt",
        "es": "Tratado",
    },
    "gap": {
        "it": "Elemento mancante",
        "en": "Gap",
        "fr": "Lacune",
        "de": "Lücke",
        "es": "Carencia",
    },
    "unclear": {
        "it": "Da chiarire",
        "en": "Unclear",
        "fr": "À clarifier",
        "de": "Unklar",
        "es": "Por aclarar",
    },
    "not_applicable": {
        "it": "Non applicabile",
        "en": "Not applicable",
        "fr": "Sans objet",
        "de": "Nicht anwendbar",
        "es": "No aplicable",
    },
    "critical": {
        "it": "Critica",
        "en": "Critical",
        "fr": "Critique",
        "de": "Kritisch",
        "es": "Crítica",
    },
    "high": {"it": "Alta", "en": "High", "fr": "Élevée", "de": "Hoch", "es": "Alta"},
    "medium": {
        "it": "Media",
        "en": "Medium",
        "fr": "Moyenne",
        "de": "Mittel",
        "es": "Media",
    },
    "low": {"it": "Bassa", "en": "Low", "fr": "Faible", "de": "Niedrig", "es": "Baja"},
    "not_assessed": {
        "it": "Non valutata",
        "en": "Not assessed",
        "fr": "Non évaluée",
        "de": "Nicht beurteilt",
        "es": "No evaluada",
    },
    "open": {
        "it": "Aperto",
        "en": "Open",
        "fr": "Ouvert",
        "de": "Offen",
        "es": "Abierto",
    },
    "resolved": {
        "it": "Risolto",
        "en": "Resolved",
        "fr": "Résolu",
        "de": "Erledigt",
        "es": "Resuelto",
    },
    "draft": {
        "it": "Bozza",
        "en": "Draft",
        "fr": "Projet",
        "de": "Entwurf",
        "es": "Borrador",
    },
    "filed": {
        "it": "Depositato",
        "en": "Filed",
        "fr": "Déposé",
        "de": "Eingereicht",
        "es": "Presentado",
    },
    "opened": {
        "it": "Procedura aperta",
        "en": "Procedure opened",
        "fr": "Procédure ouverte",
        "de": "Verfahren eröffnet",
        "es": "Procedimiento abierto",
    },
    "voting": {
        "it": "In fase di voto",
        "en": "Voting",
        "fr": "Vote en cours",
        "de": "Abstimmung",
        "es": "En votación",
    },
    "homologated": {
        "it": "Omologato",
        "en": "Court confirmed",
        "fr": "Homologué",
        "de": "Gerichtlich bestätigt",
        "es": "Homologado",
    },
    "execution": {
        "it": "In esecuzione",
        "en": "In execution",
        "fr": "En exécution",
        "de": "In Durchführung",
        "es": "En ejecución",
    },
    "closed": {
        "it": "Chiuso",
        "en": "Closed",
        "fr": "Clôturé",
        "de": "Abgeschlossen",
        "es": "Cerrado",
    },
    "continuity_direct": {
        "it": "Continuità diretta",
        "en": "Direct business continuation",
        "fr": "Poursuite directe de l’activité",
        "de": "Direkte Unternehmensfortführung",
        "es": "Continuidad directa",
    },
    "continuity_indirect": {
        "it": "Continuità indiretta",
        "en": "Indirect business continuation",
        "fr": "Poursuite indirecte de l’activité",
        "de": "Indirekte Unternehmensfortführung",
        "es": "Continuidad indirecta",
    },
    "liquidation": {
        "it": "Liquidatorio",
        "en": "Liquidation",
        "fr": "Liquidation",
        "de": "Liquidation",
        "es": "Liquidación",
    },
    "mixed": {
        "it": "Misto",
        "en": "Mixed",
        "fr": "Mixte",
        "de": "Gemischt",
        "es": "Mixto",
    },
}

# Workbook display strings only. Stored case models and CSV field names retain
# their canonical contracts; these labels never infer or change a judgment.
WORKBOOK_LABELS: dict[str, tuple[str, str, str, str, str]] = {
    "Overview": ("Riepilogo", "Overview", "Synthèse", "Übersicht", "Resumen"),
    "Documents": ("Documenti", "Documents", "Documents", "Unterlagen", "Documentos"),
    "Creditors": ("Creditori", "Creditors", "Créanciers", "Gläubiger", "Acreedores"),
    "Classes": ("Classi", "Classes", "Classes", "Klassen", "Clases"),
    "Sources Uses": (
        "Fonti e impieghi",
        "Sources and uses",
        "Ressources et emplois",
        "Mittelherkunft und Verwendung",
        "Fuentes y usos",
    ),
    "Liquidity": ("Liquidità", "Liquidity", "Trésorerie", "Liquidität", "Liquidez"),
    "Review Questions": (
        "Questioni di revisione",
        "Review questions",
        "Questions de revue",
        "Prüffragen",
        "Cuestiones de revisión",
    ),
    "Issues": (
        "Questioni aperte",
        "Open issues",
        "Points ouverts",
        "Offene Punkte",
        "Cuestiones pendientes",
    ),
    "Mechanical Checks": (
        "Controlli aritmetici",
        "Arithmetic checks",
        "Contrôles arithmétiques",
        "Rechenprüfungen",
        "Controles aritméticos",
    ),
    "Numeric Tie-Out": (
        "Confronto importi",
        "Amount comparison",
        "Comparaison des montants",
        "Betragsvergleich",
        "Comparación de importes",
    ),
    "semantic_model_status": (
        "Stato della revisione",
        "Review status",
        "État de la revue",
        "Prüfstatus",
        "Estado de revisión",
    ),
    "reviewed": (
        "Analisi documentale rivista",
        "Document analysis reviewed",
        "Analyse documentaire revue",
        "Dokumentenanalyse geprüft",
        "Análisis documental revisado",
    ),
    "needs_semantic_review": (
        "Interpretazione da rivedere",
        "Interpretation needs review",
        "Interprétation à revoir",
        "Interpretation zu prüfen",
        "Interpretación por revisar",
    ),
    "invalid_semantic_recipe": (
        "Revisione non valida",
        "Invalid review",
        "Revue non valide",
        "Ungültige Prüfung",
        "Revisión no válida",
    ),
    "currency": ("Valuta", "Currency", "Devise", "Währung", "Moneda"),
    "relative_path": ("Documento", "Document", "Document", "Dokument", "Documento"),
    "roles": (
        "Ruoli del documento",
        "Document roles",
        "Rôles du document",
        "Dokumentrollen",
        "Funciones del documento",
    ),
    "authoritative_for": (
        "Fonte di riferimento per",
        "Source of record for",
        "Source de référence pour",
        "Maßgebliche Quelle für",
        "Fuente de referencia para",
    ),
    "version_date": (
        "Data della versione",
        "Version date",
        "Date de version",
        "Versionsdatum",
        "Fecha de versión",
    ),
    "source_artifact_ref": (
        "Identificativo della fonte",
        "Source identifier",
        "Identifiant de source",
        "Quellenkennung",
        "Identificador de fuente",
    ),
    "creditor_id": (
        "ID creditore",
        "Creditor ID",
        "ID créancier",
        "Gläubiger-ID",
        "ID acreedor",
    ),
    "creditor_name": ("Creditore", "Creditor", "Créancier", "Gläubiger", "Acreedor"),
    "claim_amount": ("Credito", "Claim", "Créance", "Forderung", "Crédito"),
    "claim_status": (
        "Stato del credito",
        "Claim status",
        "État de la créance",
        "Forderungsstatus",
        "Estado del crédito",
    ),
    "priority": (
        "Rango del credito",
        "Claim priority",
        "Rang de la créance",
        "Forderungsrang",
        "Prelación del crédito",
    ),
    "class_id": ("Classe", "Class", "Classe", "Klasse", "Clase"),
    "treatment_form": (
        "Forma di trattamento",
        "Treatment form",
        "Forme de traitement",
        "Behandlungsform",
        "Forma de tratamiento",
    ),
    "proposed_cash_amount": (
        "Pagamento monetario proposto",
        "Proposed cash payment",
        "Paiement monétaire proposé",
        "Vorgeschlagene Geldzahlung",
        "Pago monetario propuesto",
    ),
    "proposed_non_cash_amount": (
        "Recupero non monetario proposto",
        "Proposed non-cash recovery",
        "Recouvrement non monétaire proposé",
        "Vorgeschlagene Sachleistung",
        "Recuperación no monetaria propuesta",
    ),
    "proposed_total_amount": (
        "Recupero totale proposto",
        "Total proposed recovery",
        "Recouvrement total proposé",
        "Vorgeschlagener Gesamtrückfluss",
        "Recuperación total propuesta",
    ),
    "proposed_recovery_pct": (
        "Recupero proposto (%)",
        "Proposed recovery (%)",
        "Recouvrement proposé (%)",
        "Vorgeschlagene Quote (%)",
        "Recuperación propuesta (%)",
    ),
    "liquidation_recovery_amount": (
        "Recupero in liquidazione",
        "Liquidation recovery",
        "Recouvrement en liquidation",
        "Liquidationserlös",
        "Recuperación en liquidación",
    ),
    "liquidation_recovery_pct": (
        "Recupero in liquidazione (%)",
        "Liquidation recovery (%)",
        "Recouvrement en liquidation (%)",
        "Liquidationsquote (%)",
        "Recuperación en liquidación (%)",
    ),
    "payment_start": (
        "Inizio pagamenti",
        "Payment start",
        "Début des paiements",
        "Zahlungsbeginn",
        "Inicio de pagos",
    ),
    "payment_end": (
        "Fine pagamenti",
        "Payment end",
        "Fin des paiements",
        "Zahlungsende",
        "Fin de pagos",
    ),
    "voting_treatment": (
        "Trattamento del voto",
        "Voting treatment",
        "Traitement du vote",
        "Stimmrechtsbehandlung",
        "Tratamiento del voto",
    ),
    "evidence_ref_count": (
        "Riferimenti documentali",
        "Evidence references",
        "Références documentaires",
        "Belegverweise",
        "Referencias documentales",
    ),
    "item_id": ("ID voce", "Item ID", "ID poste", "Positions-ID", "ID partida"),
    "side": (
        "Fonte o impiego",
        "Source or use",
        "Ressource ou emploi",
        "Herkunft oder Verwendung",
        "Fuente o uso",
    ),
    "category": ("Categoria", "Category", "Catégorie", "Kategorie", "Categoría"),
    "description": (
        "Descrizione",
        "Description",
        "Description",
        "Beschreibung",
        "Descripción",
    ),
    "amount": ("Importo", "Amount", "Montant", "Betrag", "Importe"),
    "period_id": ("ID periodo", "Period ID", "ID période", "Perioden-ID", "ID periodo"),
    "period": ("Periodo", "Period", "Période", "Zeitraum", "Periodo"),
    "opening_cash": (
        "Cassa iniziale",
        "Opening cash",
        "Trésorerie initiale",
        "Anfangsbestand",
        "Caja inicial",
    ),
    "total_inflows": (
        "Entrate totali",
        "Total inflows",
        "Entrées totales",
        "Gesamteingänge",
        "Entradas totales",
    ),
    "total_outflows": (
        "Uscite totali",
        "Total outflows",
        "Sorties totales",
        "Gesamtausgänge",
        "Salidas totales",
    ),
    "reported_closing_cash": (
        "Cassa finale del piano",
        "Plan closing cash",
        "Trésorerie finale du plan",
        "Plan-Endbestand",
        "Caja final del plan",
    ),
    "calculated_closing_cash": (
        "Cassa finale ricalcolata",
        "Recalculated closing cash",
        "Trésorerie finale recalculée",
        "Nachgerechneter Endbestand",
        "Caja final recalculada",
    ),
    "bridge_difference": (
        "Differenza di quadratura",
        "Cash bridge difference",
        "Écart de rapprochement",
        "Abstimmungsdifferenz",
        "Diferencia de conciliación",
    ),
    "bridge_within_tolerance": (
        "Entro la tolleranza",
        "Within tolerance",
        "Dans la tolérance",
        "Innerhalb der Toleranz",
        "Dentro de tolerancia",
    ),
    "question_id": (
        "ID domanda",
        "Question ID",
        "ID question",
        "Fragen-ID",
        "ID pregunta",
    ),
    "area": ("Area", "Area", "Domaine", "Bereich", "Área"),
    "question": (
        "Domanda di revisione",
        "Review question",
        "Question de revue",
        "Prüffrage",
        "Pregunta de revisión",
    ),
    "issue_id": ("ID questione", "Issue ID", "ID point", "Punkt-ID", "ID cuestión"),
    "statement": (
        "Questione rilevata",
        "Issue identified",
        "Point relevé",
        "Feststellung",
        "Cuestión detectada",
    ),
    "owner": ("Responsabile", "Owner", "Responsable", "Verantwortlich", "Responsable"),
    "check_id": ("Controllo", "Check", "Contrôle", "Prüfung", "Control"),
    "observation": (
        "Risultato del controllo",
        "Check result",
        "Résultat du contrôle",
        "Prüfergebnis",
        "Resultado del control",
    ),
    "mechanical_scope": (
        "Ambito del controllo",
        "Check scope",
        "Portée du contrôle",
        "Prüfumfang",
        "Alcance del control",
    ),
    "limitation": (
        "Limite del controllo",
        "Check limitation",
        "Limite du contrôle",
        "Prüfgrenze",
        "Límite del control",
    ),
    "plan_source_file": (
        "Documento del piano",
        "Plan document",
        "Document du plan",
        "Plandokument",
        "Documento del plan",
    ),
    "plan_location": (
        "Posizione nel piano",
        "Plan location",
        "Emplacement dans le plan",
        "Fundstelle im Plan",
        "Ubicación en el plan",
    ),
    "plan_amount": (
        "Importo nel piano",
        "Plan amount",
        "Montant du plan",
        "Planbetrag",
        "Importe del plan",
    ),
    "support_source_file": (
        "Documento di supporto",
        "Supporting document",
        "Document justificatif",
        "Belegdokument",
        "Documento de soporte",
    ),
    "support_location": (
        "Posizione nel supporto",
        "Supporting location",
        "Emplacement justificatif",
        "Belegstelle",
        "Ubicación del soporte",
    ),
    "support_amount": (
        "Importo nel supporto",
        "Supporting amount",
        "Montant justificatif",
        "Belegbetrag",
        "Importe del soporte",
    ),
    "difference": ("Differenza", "Difference", "Écart", "Differenz", "Diferencia"),
    "match_status": (
        "Stato del confronto",
        "Comparison status",
        "État de comparaison",
        "Vergleichsstatus",
        "Estado de comparación",
    ),
    "asserted": ("Rivendicato", "Asserted", "Déclarée", "Angegeben", "Declarado"),
    "admitted": ("Ammesso", "Admitted", "Admise", "Zugelassen", "Admitido"),
    "contested": ("Contestato", "Contested", "Contestée", "Bestritten", "Impugnado"),
    "conditional": (
        "Condizionato",
        "Conditional",
        "Conditionnelle",
        "Bedingt",
        "Condicionado",
    ),
    "prededuction": (
        "Prededucibile",
        "Priority procedure claim",
        "Créance prioritaire de procédure",
        "Verfahrensvorrang",
        "Crédito prioritario del procedimiento",
    ),
    "secured": ("Garantito", "Secured", "Garantie", "Besichert", "Garantizado"),
    "privileged": (
        "Privilegiato",
        "Preferred",
        "Privilégiée",
        "Vorrangig",
        "Privilegiado",
    ),
    "unsecured": (
        "Chirografario",
        "Unsecured",
        "Chirographaire",
        "Unbesichert",
        "Ordinario",
    ),
    "subordinated": (
        "Subordinato",
        "Subordinated",
        "Subordonnée",
        "Nachrangig",
        "Subordinado",
    ),
    "cash": ("Denaro", "Cash", "Numéraire", "Geldzahlung", "Dinero"),
    "non_cash": (
        "Non monetario",
        "Non-cash",
        "Non monétaire",
        "Sachleistung",
        "No monetario",
    ),
    "continuing_relationship": (
        "Rapporto continuativo",
        "Continuing relationship",
        "Relation poursuivie",
        "Fortgeführte Beziehung",
        "Relación continuada",
    ),
    "non_voting": (
        "Senza voto",
        "Non-voting",
        "Sans vote",
        "Ohne Stimmrecht",
        "Sin voto",
    ),
    "partially_voting": (
        "Voto parziale",
        "Partially voting",
        "Vote partiel",
        "Teilweises Stimmrecht",
        "Voto parcial",
    ),
    "source": ("Fonte", "Source", "Ressource", "Mittelherkunft", "Fuente"),
    "use": ("Impiego", "Use", "Emploi", "Mittelverwendung", "Uso"),
    "true": ("Sì", "Yes", "Oui", "Ja", "Sí"),
    "false": ("No", "No", "Non", "Nein", "No"),
    "passed": ("Superato", "Passed", "Réussi", "Bestanden", "Superado"),
    "attention": (
        "Da esaminare",
        "Needs attention",
        "À examiner",
        "Zu prüfen",
        "Por examinar",
    ),
    "complete": ("Completo", "Complete", "Complet", "Vollständig", "Completo"),
    "partial": ("Parziale", "Partial", "Partiel", "Teilweise", "Parcial"),
    "missing": ("Mancante", "Missing", "Manquant", "Fehlend", "Ausente"),
    "proposal": ("Proposta", "Proposal", "Proposition", "Vorschlag", "Propuesta"),
    "plan": ("Piano", "Plan", "Plan", "Plan", "Plan"),
    "creditor_schedule": (
        "Elenco creditori",
        "Creditor schedule",
        "Liste des créanciers",
        "Gläubigerliste",
        "Lista de acreedores",
    ),
    "accounting_records": (
        "Contabilità",
        "Accounting records",
        "Comptabilité",
        "Buchhaltung",
        "Contabilidad",
    ),
    "business_plan": (
        "Piano industriale",
        "Business plan",
        "Plan d’activité",
        "Geschäftsplan",
        "Plan de negocio",
    ),
    "financial_model": (
        "Modello finanziario",
        "Financial model",
        "Modèle financier",
        "Finanzmodell",
        "Modelo financiero",
    ),
    "liquidation_analysis": (
        "Analisi di liquidazione",
        "Liquidation analysis",
        "Analyse de liquidation",
        "Liquidationsanalyse",
        "Análisis de liquidación",
    ),
    "tax_social_security_schedule": (
        "Prospetto tributario e previdenziale",
        "Tax and social-security schedule",
        "Tableau fiscal et social",
        "Steuer- und Sozialübersicht",
        "Cuadro tributario y de seguridad social",
    ),
    "valuation": ("Valutazione", "Valuation", "Évaluation", "Bewertung", "Valoración"),
    "professional_report": (
        "Relazione professionale",
        "Professional report",
        "Rapport professionnel",
        "Fachbericht",
        "Informe profesional",
    ),
    "judicial_commissioner_report": (
        "Relazione del commissario",
        "Commissioner report",
        "Rapport du commissaire",
        "Bericht des Verfahrenskommissars",
        "Informe del comisario",
    ),
    "court_filing": (
        "Atto depositato",
        "Court filing",
        "Acte déposé",
        "Eingereichter Schriftsatz",
        "Escrito presentado",
    ),
    "court_order": (
        "Provvedimento del tribunale",
        "Court order",
        "Décision du tribunal",
        "Gerichtsbeschluss",
        "Resolución judicial",
    ),
    "other_support": (
        "Altro supporto",
        "Other support",
        "Autre justificatif",
        "Weiterer Beleg",
        "Otro soporte",
    ),
    "excluded": ("Escluso", "Excluded", "Exclu", "Ausgeschlossen", "Excluido"),
}
WORKBOOK_LABELS.update(
    {
        "numeric_not_executed": (
            "Il confronto opzionale degli importi non è stato eseguito in questa revisione. Consultare lo stato dei controlli per i requisiti di esecuzione.",
            "The optional amount comparison was not executed in this review. See the control status for execution requirements.",
            "La comparaison facultative des montants n’a pas été exécutée dans cette revue. Consulter l’état des contrôles pour les conditions d’exécution.",
            "Der optionale Betragsvergleich wurde in dieser Prüfung nicht ausgeführt. Die Ausführungsvoraussetzungen stehen im Kontrollstatus.",
            "La comparación opcional de importes no se ejecutó en esta revisión. Consulta el estado de los controles para los requisitos de ejecución.",
        ),
        "Source Notes": (
            "Riferimenti",
            "Source notes",
            "Notes sources",
            "Quellennotizen",
            "Notas de fuentes",
        ),
        "note_ref": ("Riferimento", "Reference", "Référence", "Verweis", "Referencia"),
        "schedule": ("Prospetto", "Schedule", "Tableau", "Aufstellung", "Cuadro"),
        "record_id": ("ID riga", "Row ID", "ID ligne", "Zeilen-ID", "ID fila"),
    }
)
WORKBOOK_LABELS.update(
    {
        "document_perimeter_status": (
            "Perimetro documentale",
            "Document coverage",
            "Périmètre documentaire",
            "Dokumentenumfang",
            "Perímetro documental",
        ),
        "creditor_population_status": (
            "Perimetro dei creditori",
            "Creditor coverage",
            "Périmètre des créanciers",
            "Gläubigerumfang",
            "Perímetro de acreedores",
        ),
        "review_question_coverage": (
            "Aree di revisione presenti",
            "Review areas present",
            "Domaines de revue présents",
            "Vorhandene Prüfbereiche",
            "Áreas de revisión presentes",
        ),
        "sources_and_uses_balance": (
            "Quadratura fonti e impieghi",
            "Sources and uses balance",
            "Équilibre ressources et emplois",
            "Mittelabstimmung",
            "Equilibrio de fuentes y usos",
        ),
        "liquidity_bridge": (
            "Quadratura di cassa",
            "Cash bridge",
            "Rapprochement de trésorerie",
            "Liquiditätsabstimmung",
            "Conciliación de caja",
        ),
        "open_material_issues": (
            "Questioni critiche o alte aperte",
            "Open critical or high issues",
            "Points critiques ou élevés ouverts",
            "Offene kritische oder hohe Punkte",
            "Cuestiones críticas o altas pendientes",
        ),
        "areas_count": (
            "{count} aree presenti; {required} richieste.",
            "{count} areas represented; {required} required.",
            "{count} domaines présents ; {required} requis.",
            "{count} Bereiche vorhanden; {required} erforderlich.",
            "{count} áreas presentes; {required} requeridas.",
        ),
        "outside_tolerance_count": (
            "{count} periodi fuori tolleranza",
            "{count} periods outside tolerance",
            "{count} périodes hors tolérance",
            "{count} Zeiträume außerhalb der Toleranz",
            "{count} periodos fuera de tolerancia",
        ),
        "material_issue_count": (
            "{count} questioni critiche o alte aperte",
            "{count} open critical/high issues",
            "{count} points critiques ou élevés ouverts",
            "{count} offene kritische oder hohe Punkte",
            "{count} cuestiones críticas o altas pendientes",
        ),
        "Reports the reviewer-assigned perimeter status.": (
            "Riporta lo stato del perimetro assegnato dal revisore.",
            "Reports the reviewer-assigned perimeter status.",
            "Affiche l’état du périmètre attribué par le réviseur.",
            "Zeigt den vom Prüfer zugeordneten Umfangsstatus.",
            "Muestra el estado del perímetro asignado por el revisor.",
        ),
        "Reports the reviewer-assigned population status.": (
            "Riporta lo stato della popolazione assegnato dal revisore.",
            "Reports the reviewer-assigned population status.",
            "Affiche l’état de la population attribué par le réviseur.",
            "Zeigt den vom Prüfer zugeordneten Populationsstatus.",
            "Muestra el estado de la población asignado por el revisor.",
        ),
        "Checks presence only, not adequacy of assessments.": (
            "Verifica la presenza delle aree, non l’adeguatezza delle valutazioni.",
            "Checks presence only, not adequacy of assessments.",
            "Vérifie la présence, pas l’adéquation des évaluations.",
            "Prüft das Vorhandensein, nicht die Angemessenheit der Bewertungen.",
            "Comprueba presencia, no suficiencia de las evaluaciones.",
        ),
        "Sources minus uses, compared with reviewed tolerance.": (
            "Fonti meno impieghi, confrontati con la tolleranza rivista.",
            "Sources minus uses, compared with reviewed tolerance.",
            "Ressources moins emplois, comparés à la tolérance revue.",
            "Herkunft minus Verwendung, verglichen mit der geprüften Toleranz.",
            "Fuentes menos usos, comparados con la tolerancia revisada.",
        ),
        "Opening cash plus inflows minus outflows.": (
            "Cassa iniziale più entrate meno uscite.",
            "Opening cash plus inflows minus outflows.",
            "Trésorerie initiale plus entrées moins sorties.",
            "Anfangsbestand plus Eingänge minus Ausgänge.",
            "Caja inicial más entradas menos salidas.",
        ),
        "Counts reviewer-classified issues without reclassifying them.": (
            "Conta le questioni classificate dal revisore senza riclassificarle.",
            "Counts reviewer-classified issues without reclassifying them.",
            "Compte les points classés par le réviseur sans les reclasser.",
            "Zählt die vom Prüfer eingeordneten Punkte ohne Neueinordnung.",
            "Cuenta las cuestiones clasificadas por el revisor sin reclasificarlas.",
        ),
        "This mechanical observation is not a legal, tax, feasibility, materiality, or evidence-sufficiency conclusion.": (
            "Il controllo non formula conclusioni legali, fiscali, di fattibilità, rilevanza o sufficienza delle prove.",
            "This mechanical observation is not a legal, tax, feasibility, materiality, or evidence-sufficiency conclusion.",
            "Ce contrôle ne conclut ni sur le droit, la fiscalité, la faisabilité, l’importance ou la suffisance des preuves.",
            "Diese Prüfung trifft keine rechtliche, steuerliche, Machbarkeits-, Wesentlichkeits- oder Belegbewertung.",
            "Este control no concluye sobre derecho, fiscalidad, viabilidad, relevancia ni suficiencia de pruebas.",
        ),
    }
)
LABELS.update(
    {
        key: dict(zip(("it", "en", "fr", "de", "es"), values, strict=True))
        for key, values in WORKBOOK_LABELS.items()
    }
)


def display_label(value: object, language: str) -> str:
    """Translate a declared field or state without changing its stored value."""
    text = str(value or "—")
    code = str(language).lower().replace("_", "-").split("-", 1)[0]
    return LABELS.get(text, {}).get(code, text)
