"use strict";
// Explicit fictional transport, not public producer or installed-host acceptance.
const fs=require('node:fs'),vm=require('node:vm'),{webcrypto}=require('node:crypto');
function fixture(source,overrides={},options={}){
 class Element{constructor(tag,text){this.tagName=tag.toUpperCase();this.text=text||'';this.children=[];this.attributes={};this.listeners={};this.checked=false;this.disabled=false;this.value='';}append(...items){this.children.push(...items);}replaceChildren(...items){this.children=items;}setAttribute(k,v){this.attributes[k]=v;}addEventListener(k,v){this.listeners[k]=v;}dispatch(k){return this.listeners[k]?.();}}
 const entry={id:'invoice-1',document:'Fictional invoice',status:'completed',proposed:[{value:'Fictional proposed account'}],actual:[{value:'Fictional observed posting'}],evidence:[{value:'Fictional complete line'}],outcome:'Fictional confirmed outcome',question:''};
 const page={work_ref:'fictional-batch',kind:'batch',revision:'current',source_ref:'exact-entry',selection:{id:entry.id},review_ticket:'fictional-ticket',entry,fields:{decision:'',note:''},draft_revision:'initial',draft_stale:false,can_write:true,pending_operations:[],data:{record:{payload:{reviews:[],entries:[entry],title:'Fictional batch',scope:'Fictional scope',expected_items:1},revision:1},history:[]},...overrides};
 let panel,current,epoch=0,dirty=false,generation=0;const calls=[];
 const node=(tag,text)=>new Element(tag,text),collect=e=>[e,...e.children.flatMap(collect)];
 const api={language:options.language,node,button(text,action){const e=node('button',text);e.action=action;return e;},confirmation(parent,text){const e=node('input');e.attributes['aria-label']=text;parent.append(e,node('span',text));return e;},say(){},setDirty(v){dirty=v;},leaveDraft(){if(dirty)throw new Error('Unsaved fictional fields');},enter(){return ++epoch;},isCurrent(v){return epoch===v;},shell(){panel?.dispose();current={main:node('main'),nav:node('nav')};return current;},openWorks:async()=>{},async call(name,args){calls.push({name,args:structuredClone(args)});if(name.endsWith('_catalogue'))return {configured:false,works:[]};if(name.endsWith('_read')||name.endsWith('_setup'))return structuredClone(page);if(name.endsWith('_draft_save')){if(options.failSave)throw new Error('Declared fictional save failure');page.fields=structuredClone(args.fields);page.draft_revision='draft-'+(++generation);return {draft_revision:page.draft_revision};}if(name.endsWith('_draft_clear')){page.fields={decision:'',note:''};page.draft_stale=false;page.draft_revision='draft-'+(++generation);return {draft_revision:page.draft_revision};}if(name.endsWith('_review_commit'))return {saved:true,accounting_correction_executed:false};throw new Error('Unexpected fictional tool '+name);}};
 const sandbox={globalThis:{},structuredClone,crypto:webcrypto,setTimeout:()=>1,clearTimeout(){},Object,Array,String,JSON,Set,URL};vm.runInNewContext(fs.readFileSync(source,'utf8'),sandbox,{filename:source});panel=sandbox.globalThis.VeraBrowser.create(api);
 return {panel,page,calls,elements:()=>collect(current.main),field:label=>collect(current.main).find(e=>e.attributes['aria-label']===label),button:label=>collect(current.main).find(e=>e.tagName==='BUTTON'&&e.text===label),text:()=>collect(current.main).filter(e=>e.tagName!=='STYLE').map(e=>e.text).join(' ')};
}
module.exports={fixture};
