"use strict";
// Declared fictional transport, not source-service or native-host acceptance.
const fs=require('node:fs'),vm=require('node:vm'),{webcrypto}=require('node:crypto');
function fixture(source,overrides={}){
 class Element{constructor(tag,text){this.tagName=tag.toUpperCase();this.text=text||'';this.children=[];this.attributes={};this.listeners={};this.checked=false;this.disabled=false;this.value='';}append(...items){this.children.push(...items);}setAttribute(k,v){this.attributes[k]=v;}addEventListener(k,v){this.listeners[k]=v;}dispatch(k){return this.listeners[k]?.();}}
 const fields={operation:'',reviewer:'',decisions:{},decision:'',note:''};
 const page={work_ref:'fictional-communication',revision:'exact-version',source_ref:'exact-version',review_ticket:'fictional-ticket',fields,draft_revision:'initial',draft_stale:false,can_write:true,pending_operations:[],data:{studio:'Fictional studio',run_id:'fictional-run',intake:{objective:'Fictional audience-bound update'},workbench:{required_review_scopes:['recommendation','claims'],contribution:{recommendation:'publish',claims:[{text:'Fictional full claim',qualification:'Scope remains unresolved'}]}},review_payload:{items:[{message:'Whole fictional claim review'}]},review_log:{events:[]},artifacts:[],final:null},...overrides};
 let panel,current,epoch=0,dirty=false,generation=0;const calls=[];
 const node=(tag,text)=>new Element(tag,text),collect=e=>[e,...e.children.flatMap(collect)];
 const api={node,button(text,action){const e=node('button',text);e.action=action;return e;},confirmation(parent,text){const e=node('input');e.attributes['aria-label']=text;parent.append(e,node('span',text));return e;},say(){},setDirty(v){dirty=v;},leaveDraft(){if(dirty)throw new Error('Unsaved fictional fields');},enter(){return ++epoch;},isCurrent(v){return epoch===v;},shell(){panel?.dispose();current={main:node('main'),nav:node('nav')};return current;},openWorks:async()=>{},async call(name,args){calls.push({name,args:structuredClone(args)});if(name.endsWith('_catalogue'))return {configured:Boolean(overrides.configured),works:overrides.works||[]};if(name.endsWith('_setup'))return structuredClone(page);if(name.endsWith('_draft_save')){page.fields=structuredClone(args.fields);page.draft_revision='draft-'+(++generation);return {draft_revision:page.draft_revision};}if(name.endsWith('_draft_clear')){page.fields=structuredClone(fields);page.draft_stale=false;page.draft_revision='draft-'+(++generation);return {draft_revision:page.draft_revision};}if(name.endsWith('_execute'))return {saved:true,sent_or_published:false};throw new Error('Unexpected fictional tool '+name);}};
 const sandbox={globalThis:{},structuredClone,crypto:webcrypto,setTimeout:()=>1,clearTimeout(){},Object,Array,String,JSON,Set,URL};
 vm.runInNewContext(fs.readFileSync(source,'utf8'),sandbox,{filename:source});panel=sandbox.globalThis.VeraCommunication.create(api);
 return {panel,page,calls,field:label=>collect(current.main).find(e=>e.attributes['aria-label']===label),button:label=>collect(current.main).find(e=>e.tagName==='BUTTON'&&e.text===label),text:()=>collect(current.main).map(e=>e.text).join(' ')};
}
module.exports={fixture};
