"use strict";
// Explicit fictional transport: verifies component events, never the case engine or host.
const fs=require('node:fs'),vm=require('node:vm'),{webcrypto}=require('node:crypto');
function fixture(source,overrides={}){
 class Element{constructor(tag,text){this.tagName=tag.toUpperCase();this.text=text||'';this.children=[];this.attributes={};this.listeners={};this.checked=false;this.disabled=false;this.value='';}append(...items){this.children.push(...items);}replaceChildren(...items){this.children=items;}setAttribute(k,v){this.attributes[k]=v;}addEventListener(k,v){this.listeners[k]=v;}dispatch(k){return this.listeners[k]?.();}}
 const empty=Object.fromEntries(['operation','proposal_ref','target_id','decision_id','professional_role','scope_text','confirmation','note'].map(k=>[k,'']));
 const page={work_ref:'fictional-merger',revision:'current-version',source_ref:'current-version',review_ticket:'fictional-ticket',fields:structuredClone(empty),draft_revision:'initial',draft_stale:false,can_write:true,can_approve:true,pending_operations:[],data:{report:{synthetic:true,actor:'fictional-case-actor',records:[{record:{id:'fact',kind:'Fact',version:2,data:{statement:'Complete fictional current fact',value:'101'}}}],history:[{id:'fact',version:1,data:{statement:'Retained fictional prior fact'}}]},grant:{role:'reviewer'},proposals:[{proposal_ref:'proposal-one',name:'fictional-proposal.json'}],exports:[]},...overrides};
 let panel,current,epoch=0,dirty=false,generation=0;const calls=[];
 const node=(tag,text)=>new Element(tag,text),collect=e=>[e,...e.children.flatMap(collect)];
 const api={node,button(text,action){const e=node('button',text);e.action=action;return e;},confirmation(parent,text){const e=node('input');e.attributes['aria-label']=text;parent.append(e,node('span',text));return e;},say(){},setDirty(v){dirty=v;},leaveDraft(){if(dirty)throw new Error('Unsaved fictional fields');},enter(){return ++epoch;},isCurrent(v){return epoch===v;},shell(){panel?.dispose();current={main:node('main'),nav:node('nav')};return current;},openWorks:async()=>{},async call(name,args){calls.push({name,args:structuredClone(args)});if(name.endsWith('_catalogue'))return {configured:false,works:[]};if(name.endsWith('_setup'))return structuredClone(page);if(name.endsWith('_draft_save')){page.fields=structuredClone(args.fields);page.draft_revision='draft-'+(++generation);return {draft_revision:page.draft_revision};}if(name.endsWith('_draft_clear')){page.fields=structuredClone(empty);page.draft_stale=false;page.draft_revision='draft-'+(++generation);return {draft_revision:page.draft_revision};}if(name.endsWith('_preview'))return {preview_ref:'fictional-full-preview',target:{version:2,statement:'Full fictional approval target'},proposed_confirmation:{scope_text:args.fields.scope_text},professional_confirmation_recorded:false};if(name.endsWith('_execute'))return {saved:true,authenticated_signature:false};throw new Error('Unexpected fictional tool '+name);}};
 const sandbox={globalThis:{},structuredClone,crypto:webcrypto,setTimeout:()=>1,clearTimeout(){},Object,Array,String,JSON,Set,URL};
 const reportSource=require('node:path').join(require('node:path').dirname(source),'model-data-report.js');
 vm.runInNewContext(fs.readFileSync(reportSource,'utf8'),sandbox,{filename:reportSource});
 vm.runInNewContext(fs.readFileSync(source,'utf8'),sandbox,{filename:source});panel=sandbox.globalThis.VeraFusion.create(api);
 return {panel,page,calls,field:label=>collect(current.main).find(e=>e.attributes['aria-label']===label),button:label=>collect(current.main).find(e=>e.tagName==='BUTTON'&&e.text===label),text:()=>collect(current.main).map(e=>e.text).join(' '),nodes:()=>collect(current.main)};
}
module.exports={fixture};
