"use strict";
// Declared fictional transport, not source-service or native-host acceptance.
const fs=require('node:fs'),vm=require('node:vm'),{webcrypto}=require('node:crypto');
function fixture(source,overrides={}){
 class Element{constructor(tag,text){this.tagName=tag.toUpperCase();this.text=text||'';this.children=[];this.attributes={};this.listeners={};this.checked=false;this.disabled=false;this.value='';this.style={};}append(...items){this.children.push(...items);}replaceChildren(...items){this.children=[...items];}focus(){}select(){}setAttribute(k,v){this.attributes[k]=v;}addEventListener(k,v){this.listeners[k]=v;}dispatch(k){return this.listeners[k]?.();}}
 const {reply,sendToChat,language,...pageOverrides}=overrides;
 const fields={operation:'',actor:'',record_kind:'',record_json:'',branch_id:'',proposal_digest:'',decision:'',reason:''};
 const page={work_ref:'fictional-transform',revision:'exact-version',source_ref:'exact-version',review_ticket:'fictional-ticket',fields,draft_revision:'initial',draft_stale:false,can_write:true,pending_operations:[],data:{state:{case:{id:'FICTIONAL-TR',purpose:'Synthetic demonstration only'},branches:{B1:{title:'Fictional branch',status:'blocked',proposal_digest:'exact-proposal-digest',blockers:['Missing valuation'],calculations:{}}},records:{finding:{F1:{statement:'Whole fictional finding',rationale:'Only synthetic interpretation',dependencies:['evidence:E1']}}},decisions:[]},record_contract:{finding:['statement','category','rationale','alternatives','confidence']},sources:[],exports:[],artifacts:[]},...pageOverrides};
 let panel,current,epoch=0,dirty=false,generation=0;const calls=[];
 const node=(tag,text)=>new Element(tag,text),collect=e=>[e,...e.children.flatMap(collect)];
 const api={node,sendToChat,language,button(text,action){const e=node('button',text);e.action=action;return e;},confirmation(parent,text){const e=node('input');e.attributes['aria-label']=text;parent.append(e,node('span',text));return e;},say(){},setDirty(v){dirty=v;},leaveDraft(){if(dirty)throw new Error('Unsaved fictional fields');},enter(){return ++epoch;},isCurrent(v){return epoch===v;},shell(){panel?.dispose();current={main:node('main'),nav:node('nav')};return current;},openWorks:async()=>{},async call(name,args){calls.push({name,args:structuredClone(args)});if(reply){const result=reply(name,args,page);if(result!==undefined)return structuredClone(result);}if(name.endsWith('_catalogue'))return {configured:Boolean(overrides.configured),works:overrides.works||[]};if(name.endsWith('_setup'))return structuredClone(page);if(name.endsWith('_draft_save')){page.fields=structuredClone(args.fields);page.draft_revision='draft-'+(++generation);return {draft_revision:page.draft_revision};}if(name.endsWith('_draft_clear')){page.fields=structuredClone(name.includes('_initial_')?{owner:'',purpose:''}:fields);page.draft_stale=false;page.draft_revision='draft-'+(++generation);return {draft_revision:page.draft_revision};}if(name.endsWith('_create')){page.created=true;page.can_write=false;page.data.state={case:{id:page.data.case_id,owner:page.fields.owner,purpose:page.fields.purpose,initial_form:null,final_form:null},branches:{},records:{},decisions:[]};return {created:true,synthetic_only:true,professional_validation:false};}if(name.endsWith('_execute'))return {saved:true,sent_or_published:false};throw new Error('Unexpected fictional tool '+name);}};
 const sandbox={globalThis:{},structuredClone,crypto:webcrypto,setTimeout:()=>1,clearTimeout(){},Object,Array,String,JSON,Set,URL};
 vm.runInNewContext(fs.readFileSync(source,'utf8'),sandbox,{filename:source});panel=sandbox.globalThis.VeraTransformation.create(api);
 return {panel,page,calls,tree:()=>current.main,field:label=>collect(current.main).find(e=>e.attributes['aria-label']===label),button:label=>collect(current.main).find(e=>e.tagName==='BUTTON'&&e.text===label),text:()=>collect(current.main).map(e=>e.text).join(' ')};
}
module.exports={fixture};
