"use strict";
/* Professional fields and complete existing case records, not a JSON authoring form. */
globalThis.VeraFusion=Object.freeze({create(api){
  const {node,button,call,say,confirmation}=api;let context,timer,queue=Promise.resolve();const urls=new Set();
  const scope=p=>({work_ref:p.work_ref,revision:p.revision,source_ref:p.source_ref});
  function dispose(){clearTimeout(timer);context=null;for(const url of urls)URL.revokeObjectURL(url);urls.clear();}
  async function persist(){const local=context;if(!local?.editable)return queue;const fields=structuredClone(local.fields),serialized=JSON.stringify(fields);queue=queue.then(async()=>{if(local.saved===serialized)return;const saved=await call("vera_workspace_fusion_draft_save",{...scope(local.page),review_ticket:local.page.review_ticket,expected_draft_revision:local.stamp,fields});local.stamp=saved.draft_revision;local.saved=serialized;local.error=null;if(context===local&&JSON.stringify(local.fields)===serialized)api.setDirty(false);say("Campi incompleti conservati. Nessuna conferma professionale registrata.");}).catch(error=>{local.error=error;api.setDirty(true);say("Campi non conservati: "+error.message,true);});return queue;}
  async function flush(){clearTimeout(timer);await persist();if(context?.error)throw context.error;}
  function readable(parent,value,title){const detail=node("details",undefined,"patent-record");detail.append(node("summary",title,"source-excerpt"));const walk=(into,item)=>{if(item!==null&&typeof item==="object")for(const [key,part]of Object.entries(item)){const section=node("section");section.append(node("h4",key));into.append(section);walk(section,part);}else into.append(node("p",item===null?"Non indicato":String(item),"source-excerpt"));};walk(detail,value);parent.append(detail);}
  function field(parent,local,label,key,options){const wrap=node("label",undefined,"field"),control=node(options?"select":"textarea");control.setAttribute("aria-label",label);if(options)for(const [value,text]of options){const option=node("option",text);option.value=value;control.append(option);}control.value=local.fields[key];control.maxLength=4000;control.disabled=!local.editable;control.addEventListener(options?"change":"input",()=>{local.fields[key]=control.value;local.confirm.checked=false;local.preview=null;local.execution=null;local.previewArea.replaceChildren();api.setDirty(true);clearTimeout(timer);timer=setTimeout(persist,450);});wrap.append(node("span",label),control);parent.append(wrap);return control;}
  function privacy(main){main.append(node("h2","Quali dati arrivano al modello"),node("p","Le route del pannello sono riservate all’app: mostrano tutte le revisioni accessibili all’operatore, riferimenti, importazioni dagli Archivi scelti, fatti, workpaper, problemi e conferme. Non chiamano il modello o servizi esterni. Nel workflow specialistico il runtime Codex o Cowork può leggere identità delle società e degli incarichi, documenti selezionati, saldi, basi fiscali, valutazioni, assegnazioni ai soci, date, fonti, bozze e conferme necessari al lavoro. Nulla è anonimizzato automaticamente. L’esportazione reale conserva l’esposizione al modello come non misurabile finché l’orchestratore non registra le fasi osservabili nel normale report dati. Le ricerche pubbliche devono usare quesiti senza identificativi del cliente. Il fascicolo combinato resta nel caso di fusione: il pannello non lo copia nei singoli Archivi e non chiude gli incarichi.","caption"));}
  async function catalogue(){await flush();api.leaveDraft();const generation=api.enter(),page=await call("vera_workspace_fusion_catalogue",{});if(!api.isCurrent(generation))return;const {nav,main}=api.shell();nav.append(button("← Clienti e incarichi",api.openWorks));main.append(node("p","Vera","eyebrow"),node("h1","Fusione guidata"),node("p","Riprendi un caso collegato, controlla i workpaper e conserva le conferme sulle versioni esatte.","intro"));for(const work of page.works){const row=node("section",undefined,"output");row.append(node("h2",work.objective),node("p",work.synthetic?"Caso interamente sintetico":"Caso da riesaminare"),node("p","Operatore dichiarato: "+work.case_actor),button("Apri fascicolo",()=>open(work.work_ref)));main.append(row);}if(!page.configured)main.append(node("p","Nessun caso collegato a questo operatore. Prepara o riprendi Fusione guidata nella chat e collega soltanto il caso esatto e un attore già autorizzato.","notice"));privacy(main);}
  async function download(page,args,row){const value=await call("vera_workspace_fusion_artifact",{...scope(page),...args}),bytes=Uint8Array.from(atob(value.base64),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:value.mime_type}));urls.add(url);const link=node("a","Scarica "+value.name);link.href=url;link.download=value.name;row.append(link);link.click();}
  async function open(workRef){await flush();api.leaveDraft();const generation=api.enter(),page=await call("vera_workspace_fusion_setup",{work_ref:workRef});if(!api.isCurrent(generation))return;const {nav,main}=api.shell();nav.append(button("← Casi di fusione",catalogue),button("← Clienti e incarichi",api.openWorks));const local={page,fields:structuredClone(page.fields),stamp:page.draft_revision,saved:JSON.stringify(page.fields),editable:page.can_write&&!page.draft_stale&&!page.pending_operations.length,preview:null};context=local;api.setDirty(false);
    main.append(node("p",page.data.report.synthetic?"Vera · caso interamente sintetico":"Vera · Fusione guidata","eyebrow"),node("h1","Workpaper e conferme della fusione"),node("p","Operatore dichiarato del caso: "+page.data.report.actor+" · ruolo: "+page.data.grant.role,"caption"),node("p","La conferma riguarda il contenuto, la versione e l’ambito scelti. Non autentica l’identità e non attesta firma, deposito o efficacia giuridica.","notice"));readable(main,page.data.report,"Tutti i record accessibili, revisioni, fatti, dipendenze, problemi e conferme");readable(main,page.data.proposals,"Proposte preparate collegate al caso");
    for(const item of page.data.exports){main.append(node("p","Report dati conservato · "+item.export_ref,"eyebrow source-excerpt"));globalThis.VeraModelDataReport.render(main,item.model_report_markdown,{node});readable(main,item.model_report,"Evidenze e dettagli del report dati · "+item.export_ref);readable(main,item.case_report,"Fascicolo esportato · "+item.export_ref);for(const artifact of item.artifacts){const row=node("section",undefined,"output");row.append(node("strong",artifact.name),button("Scarica elaborato verificato",()=>download(page,{export_ref:item.export_ref,artifact_ref:artifact.name},row)));main.append(row);}}
    if(page.pending_operations.length)main.append(node("p","Una scrittura precedente richiede recupero nel workflow specialistico. Non ripetere automaticamente il passaggio.","notice"));
    if(page.draft_stale){readable(main,local.fields,"Campi precedenti da confrontare");const check=confirmation(main,"Scarto soltanto i campi privati precedenti; conservo storia, prove e conferme"),clear=button("Scarta campi privati",async()=>{if(!check.checked)throw new Error("Conferma lo scarto dei soli campi privati.");await call("vera_workspace_fusion_draft_clear",{...scope(page),review_ticket:page.review_ticket,expected_draft_revision:local.stamp,confirmed:true});api.setDirty(false);await open(workRef);});check.disabled=clear.disabled=!page.can_write;main.append(clear);}
    const operations=[["","Scegli il passaggio"],["apply_proposal","Conserva una proposta preparata"],...(page.can_approve?[["approve","Registra una conferma professionale separata"]]:[]),["export","Esporta fascicolo e report dati"]];
    field(main,local,"Passaggio da conservare","operation",operations);field(main,local,"Proposta preparata","proposal_ref",[["","Scegli la proposta"],...page.data.proposals.map(x=>[x.proposal_ref,x.name])]);field(main,local,"Versione da confermare","target_id",[["","Scegli il record"],...page.data.report.records.filter(x=>!["Decision","ChangeImpact"].includes(x.record.kind)).map(x=>[x.record.id,x.record.kind+" · "+x.record.id+" · v"+x.record.version])]);field(main,local,"Identificativo nuovo della conferma","decision_id");field(main,local,"Ruolo professionale effettivo","professional_role");field(main,local,"Ambito definito della conferma","scope_text");field(main,local,"Conferma effettivamente espressa dal professionista","confirmation");field(main,local,"Nota privata · non entra nella conferma","note");
    local.previewArea=node("div");local.confirm=confirmation(main,"Ho riesaminato l’anteprima completa e confermo questo passaggio sul caso corrente");local.confirm.disabled=!local.editable;const inspect=button("Controlla passaggio scelto",async()=>{await flush();local.confirm.checked=false;const serialized=JSON.stringify(local.fields),value=await call("vera_workspace_fusion_preview",{...scope(page),fields:structuredClone(local.fields)});if(context!==local||serialized!==JSON.stringify(local.fields))return;local.preview=value;local.previewArea.replaceChildren();readable(local.previewArea,value,"Anteprima completa · non ancora conservata nel caso");say("Anteprima verificata sul caso corrente. Conferma del passaggio ancora da dare.");}),save=button("Conserva campi incompleti",flush),execute=button("Esegui e conserva il passaggio",async()=>{await flush();if(!local.preview||!local.confirm.checked)throw new Error("Controlla l’anteprima completa e conferma il passaggio corrente.");local.execution=local.execution||{...scope(page),review_ticket:page.review_ticket,expected_draft_revision:local.stamp,fields:structuredClone(local.fields),preview_ref:local.preview.preview_ref,confirmed:true,idempotency_key:crypto.randomUUID()};await call("vera_workspace_fusion_execute",local.execution);api.setDirty(false);await open(workRef);say("Passaggio conservato dal motore della fusione. Nessuna firma, deposito o chiusura di incarico eseguita.");},"primary");inspect.disabled=save.disabled=execute.disabled=!local.editable;main.append(inspect,save,execute,local.previewArea);privacy(main);
  }
  return Object.freeze({open,catalogue,flush,dispose,active:()=>Boolean(context),refresh:()=>context?open(context.page.work_ref):catalogue()});
}});
