"use strict";

globalThis.VeraStudioWork = Object.freeze({create(api) {
  const {node,button,call,say,main,sendToChat}=api;
  const prefix="vera_studio_work_panel_";
  const kinds=[["appointment","Appuntamento"],["task","Attività"],["deadline","Scadenza"],["follow_up","Sollecito"],["protected_time","Tempo riservato"]];
  const states=[["open","Aperto"],["waiting","In attesa"],["delegated","Delegato"],["done","Completato"],["cancelled","Annullato"]];
  const collections={items:"Impegni",meetings:"Riunioni",operations:"Operazioni calendario",history:"Cronologia"};
  const labels={title:"Titolo",kind:"Tipo",status:"Stato",client:"Cliente",engagement:"Incarico",owner:"Responsabile",due_date:"Scadenza",follow_up_date:"Data del sollecito",start_time:"Inizio · con scarto UTC",end_time:"Fine · con scarto UTC",duration_minutes:"Durata in minuti",priority:"Priorità dichiarata",category:"Categoria",notes:"Appunti",source:"Fonte o istruzione ricevuta",depends_on:"Dipendenze",revision:"Versione",id:"Riferimento",calendar:"Collegamento calendario",created_at:"Registrato",updated_at:"Aggiornato",completed_at:"Completato il",date:"Data",participants:"Partecipanti",summary:"Sintesi",decisions:"Decisioni",missing_documents:"Documenti mancanti",action_ids:"Impegni registrati",state:"Esito registrato",action:"Operazione",item_id:"Impegno",item_revision:"Versione dell’impegno",desired:"Evento richiesto",authorization:"Istruzione registrata",calendar_id:"Calendario",event_id:"Evento",evidence:"Evidenza ricevuta",timestamp:"Data e ora",body:"Contenuto registrato",sequence:"Sequenza"};
  let current,timer,queue=Promise.resolve(),epoch=0;
  const write=local=>({form:local.page.form,scope_revision:local.page.scope_revision,review_ticket:local.page.review_ticket,expected_draft_revision:local.page.draft.revision});
  function display(value,key){if(key==="kind")return kinds.find(row=>row[0]===value)?.[1]||String(value);if(key==="status")return states.find(row=>row[0]===value)?.[1]||String(value);if(Array.isArray(value))return value.map(row=>display(row)).join("\n");if(value&&typeof value==="object")return Object.entries(value).map(([name,item])=>(labels[name]||name)+": "+display(item,name)).join("\n");return value===null?"Non indicato":String(value);}
  function stored(parent,value){const dl=node("dl");for(const [key,item] of Object.entries(value)){dl.append(node("dt",labels[key]||key),node("dd",display(item,key)));}parent.append(dl);}
  function changed(local){if(local.confirm)local.confirm.checked=false;local.error=null;api.setDirty(true);clearTimeout(timer);timer=setTimeout(()=>persist(),450);}
  function assign(local,path,value){let target=local.fields;for(const name of path.slice(0,-1))target=target[name]??={};if(value===undefined)delete target[path.at(-1)];else target[path.at(-1)]=value;changed(local);}
  function valueAt(fields,path){return path.reduce((value,key)=>value?.[key],fields);}
  function field(parent,local,path,label,{choices,type="text",lines=false}={}){
    const wrap=node("label",undefined,"field"),control=node(choices?"select":type==="long"||lines?"textarea":"input");
    if(choices){const blank=node("option","Scegli…");blank.value="";control.append(blank);for(const [value,text] of choices){const option=node("option",text);option.value=value;control.append(option);}}
    if(control.tagName==="INPUT")control.type=type==="date"?"date":"text";
    const value=valueAt(local.fields,path);control.value=value===undefined?"":lines?value.join("\n"):String(value);
    control.maxLength=20000;control.disabled=!local.editable;control.setAttribute("aria-label",label);wrap.append(node("span",label),control);parent.append(wrap);local.controls.push(control);
    control.addEventListener(choices?"change":"input",()=>{
      let value=control.value;if(choices&&!value)value=undefined;
      else if(lines)value=value.split("\n").filter(row=>row!=="");
      else if(type==="number"){if(value==="")value=undefined;else if(/^\d+$/.test(value))value=Number(value);else{say("Inserisci un numero intero non negativo per "+label,true);if(local.confirm)local.confirm.checked=false;local.invalid.add(control);return;}}
      local.invalid.delete(control);assign(local,path,value);
    });return control;
  }
  function group(parent,title){const block=node("fieldset",undefined,"studio-work-fields");block.append(node("legend",title));parent.append(block);return block;}
  function itemFields(parent,local,path,title){
    const block=group(parent,title);
    for(const key of ["title","source","client","engagement","owner","category","notes","start_time","end_time","due_date","follow_up_date","duration_minutes","priority"]){field(block,local,[...path,key],labels[key],{type:["source","notes"].includes(key)?"long":key.endsWith("date")?"date":["duration_minutes","priority"].includes(key)?"number":"text"});}
    field(block,local,[...path,"kind"],labels.kind,{choices:kinds});field(block,local,[...path,"status"],labels.status,{choices:states});
    if(local.dependencies.length){const choices=node("fieldset");choices.append(node("legend","Dipende da questi impegni registrati"));block.append(choices);
      for(const item of local.dependencies){if(item.id===local.page.record?.id)continue;const wrap=node("label",undefined,"choice"),checkbox=node("input");checkbox.type="checkbox";checkbox.checked=(valueAt(local.fields,[...path,"depends_on"])||[]).includes(item.id);checkbox.disabled=!local.editable;wrap.append(checkbox,node("span",item.title+" · "+display(item.status,"status")));choices.append(wrap);local.controls.push(checkbox);checkbox.addEventListener("change",()=>{const values=new Set(valueAt(local.fields,[...path,"depends_on"])||[]);checkbox.checked?values.add(item.id):values.delete(item.id);assign(local,[...path,"depends_on"],[...values]);});}}
    block.append(node("p","Date e orari restano quelli dichiarati. Vera interpreta richieste ambigue nella chat; il pannello non assegna priorità né crea eventi.","caption"));
  }
  async function persist(){
    const local=current;if(!local?.editable)return queue;
    const fields=structuredClone(local.fields),serialized=JSON.stringify(fields);
    queue=queue.then(async()=>{if(local.saved===serialized)return;if(local.invalid.size)throw new Error("Correggi i campi numerici prima di conservare.");const result=await call(prefix+"draft_save",{...write(local),fields});local.page=result;local.saved=serialized;local.error=null;if(current===local&&JSON.stringify(local.fields)===serialized)api.setDirty(false);say("Campi incompleti conservati. Nessun impegno o evento è stato creato.");}).catch(error=>{local.error=error;api.setDirty(true);say("Campi non conservati: "+error.message,true);});return queue;
  }
  async function flush(){clearTimeout(timer);await persist();if(current?.error)throw current.error;}
  async function chat(parent,text){await flush();if(await sendToChat(text)){say("Richiesta ricevuta dalla chat. Letture e azioni restano da verificare.");return;}const copy=node("textarea",undefined,"request");copy.readOnly=true;copy.value=text;copy.setAttribute("aria-label","Richiesta da copiare nella chat corrente");parent.append(node("p","Copia questa richiesta nella chat corrente con Vera.","caption"),copy);copy.focus?.();copy.select?.();}
  function modelData(parent){const block=node("section",undefined,"model-data-report");block.append(node("h2","Quali dati arrivano al modello"),node("p","Gli strumenti del pannello restituiscono registro e bozze nei metadati dell’app, senza includerli nel testo inviato al modello. Il pannello non effettua chiamate al modello né a servizi calendario. Si applicano comunque il runtime e l’account scelti dallo studio; non è una garanzia di trattamento soltanto locale."),node("p","La richiesta di discussione invia alla chat il riferimento e la versione della selezione. Il successivo strumento di contesto restituisce quell’impegno, riunione o ricevuta per intero: nomi, appunti e dati del cliente non vengono anonimizzati. Gli strumenti ordinari del workflow possono restituire preferenze e altre voci al modello. Eventuali letture o scritture del calendario passano attraverso il connettore scelto e le autorizzazioni del servizio."));parent.append(block);}
  function shell(page){const parent=main();parent.replaceChildren();const nav=node("nav",undefined,"studio-work-nav");nav.setAttribute("aria-label","Registro del lavoro");parent.append(node("p","Vera · Registro dello studio","eyebrow"),node("h1","Organizzazione del lavoro"),node("p","Consulta impegni, riunioni e ricevute; conserva nuove attività e aggiornamenti locali. Per disponibilità, spostamenti o esiti incerti del calendario continua con Vera nella chat.","intro"),nav);
    for(const [collection,title] of Object.entries(collections))nav.append(button(title+" · "+page.counts[collection],()=>open({collection})));
    nav.append(button("Nuovo impegno",()=>open({form:"capture"})),button("Registra riunione",()=>open({form:"meeting"})));
    parent.append(node("p",page.settings.timezone?"Fuso configurato: "+page.settings.timezone+" · data di consultazione "+page.day:"Fuso e calendario da scegliere nella chat. Nessuna data viene ricavata dal computer del servizio.","caption"),button("Preferenze e calendario con Vera",()=>chat(parent,"Segui organizzazione-lavoro: leggi vera_studio_work_settings, chiarisci soltanto le preferenze mancanti con me e usa i calendari realmente collegati. Non creare eventi o automazioni per questa sola richiesta.")));
    parent.append(button("Lavori in Studio Archive",()=>chat(parent,"Apri vera_workspace_open per scegliere il cliente, l’incarico e il lavoro registrati in Studio Archive. Il registro degli impegni dello studio non completa né sostituisce gli incarichi specialistici.")));return parent;
  }
  async function dependencies(page){let offset=0,items=[];do{const result=await call(prefix+"page",{collection:"items",offset,expected_scope:page.scope_revision});items.push(...result.items);offset=result.next_offset;}while(offset!==null);if(items.length!==page.counts.items||new Set(items.map(row=>row.id)).size!==items.length)throw new Error("Inventario degli impegni incompleto. Rileggi il registro.");return items;}
  function meetingActions(parent,local){const holder=node("div");parent.append(holder);function render(){holder.replaceChildren();for(let index=0;index<(local.fields.actions||[]).length;index++){const block=node("section",undefined,"studio-work-action");holder.append(block);itemFields(block,local,["actions",index],"Impegno dalla riunione · "+(index+1));const remove=button("Rimuovi questo impegno incompleto",()=>{local.fields.actions.splice(index,1);changed(local);render();});remove.disabled=!local.editable;block.append(remove);}}render();const add=button("Aggiungi impegno dalla riunione",()=>{local.fields.actions??=[];if(local.fields.actions.length>=100)throw new Error("Una riunione supporta fino a 100 impegni.");local.fields.actions.push({});changed(local);render();});add.disabled=!local.editable;parent.append(add);}
  async function editor(parent,page,generation){
    const rows=await dependencies(page);if(generation!==epoch)return;
    const local={page,fields:structuredClone(page.draft.fields),saved:JSON.stringify(page.draft.fields),editable:page.draft.state==="draft"&&!page.draft.stale,controls:[],invalid:new Set(),dependencies:rows};current=local;api.setDirty(false);
    parent.append(node("h2",page.form==="capture"?"Nuovo impegno locale":page.form==="meeting"?"Riunione e impegni successivi":"Aggiorna questo impegno"));
    if(page.record){const actual=node("details",undefined,"studio-work-record");actual.open=true;actual.append(node("summary","Versione registrata · "+page.record.revision));stored(actual,page.record);parent.append(actual,node("p","I campi vuoti non cambiano la versione registrata. Le modifiche a titolo, orario, categoria o annullamento di un evento collegato richiedono il workflow calendario.","caption"));}
    if(page.draft.stale&&page.draft.state!=="completed")parent.append(node("p","Il registro è cambiato. Confronta i campi conservati con la versione corrente; scarta soltanto la bozza privata prima di proporre un nuovo salvataggio.","notice"));
    if(page.draft.state==="completed"){parent.append(node("p","Salvataggio locale conservato. Nessun evento è stato creato da questo pannello.","notice"));const result=node("details",undefined,"studio-work-record");result.open=true;result.append(node("summary","Ricevuta del salvataggio"));stored(result,page.draft.result);parent.append(result);}
    if(page.form==="meeting"){const block=group(parent,"Contenuto della riunione");for(const key of ["title","date","client","source","summary","participants","decisions","missing_documents"])field(block,local,["meeting",key],labels[key],{type:key==="date"?"date":["source","summary"].includes(key)?"long":"text",lines:["participants","decisions","missing_documents"].includes(key)});meetingActions(parent,local);}else itemFields(parent,local,[],"Campi da conservare");
    const save=button("Conserva i campi incompleti",flush);save.disabled=!local.editable;parent.append(save);
    const wrap=node("label",undefined,"choice"),confirm=node("input");confirm.type="checkbox";confirm.checked=false;confirm.disabled=!local.editable;wrap.append(confirm,node("span","Ho riesaminato i campi e la fonte. Confermo questo salvataggio locale"));parent.append(wrap);local.confirm=confirm;
    const submit=button("Registra il salvataggio locale",async()=>{if(!local.editable||!confirm.checked||local.invalid.size)throw new Error("Riesamina i campi e rinnova la conferma del salvataggio locale.");await flush();local.editable=false;confirm.checked=false;confirm.disabled=true;submit.disabled=true;save.disabled=true;for(const control of local.controls)control.disabled=true;try{const result=await call(prefix+"submit",{...write(local),human_confirmed:true});await render(result);}catch(error){say("Rileggi la ricevuta prima di riprovare: "+error.message,true);parent.append(button("Rileggi la ricevuta locale",()=>open({form:page.form},true)));throw error;}},"primary");submit.disabled=!local.editable;parent.append(submit);
    if(page.draft.state==="pending")parent.append(node("p","Un salvataggio locale è rimasto senza risposta. Recupera la stessa ricevuta: non viene eseguita alcuna operazione calendario.","notice"),button("Recupera il salvataggio locale",async()=>{const result=await call(prefix+"recover",write(local));await render(result);}));
    const discardWrap=node("label",undefined,"choice"),discardCheck=node("input");discardCheck.type="checkbox";discardCheck.checked=false;discardCheck.disabled=page.draft.state==="pending";discardWrap.append(discardCheck,node("span","Scarta soltanto i campi incompleti dopo il confronto con il registro corrente"));parent.append(discardWrap);
    const discard=button("Scarta soltanto la bozza privata",async()=>{if(!discardCheck.checked)throw new Error("Conferma lo scarto della sola bozza privata.");clearTimeout(timer);await queue;const result=await call(prefix+"draft_clear",write(local));api.setDirty(false);await render(result);});discard.disabled=page.draft.state==="pending";parent.append(discard);
    parent.append(button("Confronta con la bozza conservata",async()=>{clearTimeout(timer);await queue;const unsaved=structuredClone(local.fields);const result=await call(prefix+"page",{form:page.form});await render(result);const comparison=node("details",undefined,"studio-work-record");comparison.open=true;comparison.append(node("summary","Campi presenti nel pannello prima della rilettura · non applicati"));stored(comparison,unsaved);main().append(comparison);}));
    modelData(parent);
    say(page.draft.state==="completed"?"Salvataggio locale conservato e riletto. Nessuna operazione calendario eseguita.":page.draft.state==="pending"?"Salvataggio locale da recuperare dalla stessa ricevuta.":page.draft.stale?"Confronta la bozza con il registro corrente.":"Campi incompleti: nessun nuovo salvataggio confermato.");
  }
  async function render(page){const generation=++epoch;current=null;api.setDirty(false);const parent=shell(page);api.remember({collection:page.collection,offset:page.offset,...(page.form?{form:page.form}:{})});if(page.form){await editor(parent,page,generation);return;}
    parent.append(node("h2",collections[page.collection]),node("p",page.total?`${page.offset+1}–${page.offset+page.items.length} di ${page.total}`:"Nessuna voce registrata.","caption"));
    for(const item of page.items){const record=node("details",undefined,"studio-work-record");record.append(node("summary",item.title||item.desired?.title||"Operazione "+(item.action||item.action===0?item.action:item.sequence||item.id)));stored(record,item);parent.append(record);
      if(page.collection==="items")record.append(button("Aggiorna questo impegno",()=>open({form:"record:"+item.id})));
      if(page.collection!=="history")record.append(node("p","La discussione autorizza la lettura di questa voce per intero nella chat, inclusi fonte, nomi e appunti.","caption"),button("Discuti questa voce con Vera",()=>chat(record,`Segui organizzazione-lavoro. Leggi soltanto vera_studio_work_panel_context con ${JSON.stringify({scope_revision:page.scope_revision,collection:page.collection,item_id:item.id})}. Discuta la voce scelta e le eventuali informazioni mancanti. Per un esito calendario incerto usa il recupero con letture reali; questa richiesta non autorizza creazioni, modifiche, eliminazioni, inviti o automazioni.`)));
    }
    const nav=node("div",undefined,"pagination");parent.append(nav);if(page.offset)nav.append(button("← Voci precedenti",()=>open({collection:page.collection,offset:Math.max(0,page.offset-30),expected_scope:page.scope_revision})));if(page.next_offset!==null)nav.append(button("Altre voci →",()=>open({collection:page.collection,offset:page.next_offset,expected_scope:page.scope_revision})));modelData(parent);say("Registro riletto. Il calendario esterno richiede una lettura separata.");
  }
  async function open(args={},bypass=false){if(!bypass)await flush();clearTimeout(timer);const page=await call(prefix+"page",args);await render(page);}
  return {open,render,flush,active:()=>Boolean(current)};
}});

if(typeof document!=="undefined"&&document.getElementById("app"))(() => {
  const root=document.getElementById("app"),status=document.getElementById("status"),pending=new Map();let serial=0,host={},busy=false,last={},initialized=false,initial;
  function node(tag,text,className){const value=document.createElement(tag);if(text!==undefined)value.textContent=text;if(className)value.className=className;return value;}
  function say(text,error=false){status.textContent=text;status.className=error?"error":"";}
  function request(method,params){const id=++serial;return new Promise((resolve,reject)=>{const timer=setTimeout(()=>{pending.delete(id);reject(new Error("Risposta del pannello assente; rileggi la ricevuta prima di riprovare."));},35000);pending.set(id,{resolve,reject,timer});window.parent.postMessage({jsonrpc:"2.0",id,method,params},"*");});}
  async function call(name,args){const result=await request("tools/call",{name,arguments:args});if(result?.isError)throw new Error(result.content?.find(row=>row.type==="text")?.text||"Richiesta rifiutata");if(!result?._meta?.studioWork)throw new Error("Risposta privata del registro assente");return result._meta.studioWork;}
  async function run(action){if(busy)return;busy=true;root.setAttribute("aria-busy","true");try{await action();}catch(error){say(error.message,true);}finally{busy=false;root.setAttribute("aria-busy","false");}}
  function button(text,action,className){const value=node("button",text,className);value.type="button";value.addEventListener("click",()=>run(action));return value;}
  const panel=globalThis.VeraStudioWork.create({node,button,call,say,main:()=>{let main=root.querySelector("main");if(!main){main=node("main",undefined,"studio-work-main");root.append(main);}return main;},setDirty(value){root.dataset.dirty=String(value);},remember(value){last=value;},async sendToChat(text){if(!host.hostCapabilities?.message?.text)return false;const result=await request("ui/message",{role:"user",content:[{type:"text",text}]});if(result?.isError)throw new Error("La chat non ha confermato la richiesta; verifica prima di riprovare.");return true;}});
  document.getElementById("refresh").addEventListener("click",()=>run(()=>panel.open(last)));
  window.addEventListener("message",event=>{if(event.source!==window.parent||event.data?.jsonrpc!=="2.0")return;const message=event.data;if(pending.has(message.id)){const p=pending.get(message.id);pending.delete(message.id);clearTimeout(p.timer);message.error?p.reject(new Error(message.error.message)):p.resolve(message.result);return;}if(message.method==="ui/notifications/tool-result"&&message.params?._meta?.studioWork){initial=message.params._meta.studioWork;if(initialized)run(()=>panel.render(initial));}if(message.method==="ui/resource-teardown"){panel.flush().then(()=>window.parent.postMessage({jsonrpc:"2.0",id:message.id,result:{}},"*"),error=>window.parent.postMessage({jsonrpc:"2.0",id:message.id,error:{code:-32000,message:error.message}},"*"));}});
  run(async()=>{host=await request("ui/initialize",{protocolVersion:"2026-01-26",appInfo:{name:"Vera studio work",version:"1.0.0"},appCapabilities:{availableDisplayModes:["fullscreen"]}});initialized=true;window.parent.postMessage({jsonrpc:"2.0",method:"ui/notifications/initialized"},"*");document.getElementById("refresh").disabled=false;if(initial)await panel.render(initial);else await panel.open();});
})();
