"use strict";
/* Exact public site records and literal decisions; no embedded site execution. */
globalThis.VeraWebsite = Object.freeze({create(api){
  const {node,button,call,say,confirmation}=api;let context,timer,queue=Promise.resolve();const urls=new Set();
  const operations=[["","Scegli il passaggio"],["review","Registra una decisione professionale"],["validate_site","Verifica i file del sito"],["package_preview","Prepara il pacchetto dell’anteprima"],["package_release","Prepara il pacchetto finale"],["sites_preview_binding","Prepara il collegamento Sites dell’anteprima"],["sites_release_binding","Prepara il collegamento Sites finale"],["validate_run","Verifica la catena completa"]];
  const scope=p=>({work_ref:p.work_ref,revision:p.revision,source_ref:p.source_ref});
  function dispose(){clearTimeout(timer);context=null;for(const url of urls)URL.revokeObjectURL(url);urls.clear();}
  async function persist(){const local=context;if(!local?.editable)return queue;const fields=structuredClone(local.fields),serialized=JSON.stringify(fields);queue=queue.then(async()=>{if(local.saved===serialized)return;const result=await call("vera_workspace_website_draft_save",{...scope(local.page),review_ticket:local.page.review_ticket,expected_draft_revision:local.stamp,fields});local.stamp=result.draft_revision;local.saved=serialized;local.error=null;if(context===local&&JSON.stringify(local.fields)===serialized)api.setDirty(false);say("Campi incompleti conservati. Nessuna decisione professionale registrata.");}).catch(error=>{local.error=error;api.setDirty(true);say("Campi non conservati: "+error.message,true);});return queue;}
  async function flush(){clearTimeout(timer);await persist();if(context?.error)throw context.error;}
  function input(parent,local,label,key,options){const wrap=node("label",undefined,"field"),control=node(options?"select":"textarea");control.setAttribute("aria-label",label);if(options)for(const [value,text]of options){const option=node("option",text);option.value=value;control.append(option);}control.value=local.fields[key];control.maxLength=key==="note"?2000:200;control.disabled=!local.editable;control.addEventListener(options?"change":"input",()=>{local.fields[key]=control.value;local.confirm.checked=false;local.execution=null;api.setDirty(true);clearTimeout(timer);timer=setTimeout(persist,450);});wrap.append(node("span",label),control);parent.append(wrap);return control;}
  function readable(main,value,title){const detail=node("details",undefined,"patent-record");detail.append(node("summary",title));main.append(detail);const walk=(parent,item)=>{if(item!==null&&typeof item==="object")for(const [key,part]of Object.entries(item)){const group=node("section");group.append(node("h4",key));parent.append(group);walk(group,part);}else parent.append(node("p",item===null?"Non indicato":String(item),"source-excerpt"));};walk(detail,value);}
  function privacy(main){main.append(node("h2","Quali dati arrivano al modello"),node("p","Le route di questo pannello sono riservate all’app: mostrano intake, breve progettuale completo, registro delle fonti, verifica dei file, valutazione responsive, decisioni e pacchetti esatti. Non trasferiscono contenuti al modello né riaprono gli originali. Nel workflow specialistico il modello può leggere le fonti esplicitamente approvate per il sito; dopo il brief usa il source_use_plan: soli fatti mappati, materiali nominati oppure fonte completa per la ragione registrata. Ispezione pubblica, connettori, assistenza creativa e hosting seguono ciascuno il percorso selezionato nell’intake. La scelta dell’account Codex o Cowork determina il trattamento del modello: il workflow non è esclusivamente locale.","caption"));}
  async function catalogue(){await flush();api.leaveDraft();const generation=api.enter(),page=await call("vera_workspace_website_catalogue",{});if(!api.isCurrent(generation))return;const {nav,main}=api.shell();nav.append(button("← Clienti e incarichi",api.openWorks));main.append(node("p","Vera","eyebrow"),node("h1","Sito dello studio"),node("p","Riesamina un sito preparato nella cartella privata dello studio e conserva le decisioni sulla versione esatta.","intro"));for(const work of page.works){const row=node("section",undefined,"output");row.append(node("h2",work.studio),node("p",work.objective),node("p",work.status),button("Riesamina questo sito",()=>open(work.work_ref)));main.append(row);}if(!page.configured)main.append(node("p","Nessun sito collegato a questo operatore. Avvia o riprendi presenza-digitale-studio nella chat; l’host può collegare soltanto il workspace privato e il run esatti.","notice"));privacy(main);}
  async function artifact(page,item,row,showImage=false){const value=await call("vera_workspace_website_artifact",{...scope(page),artifact_ref:item.name}),bytes=Uint8Array.from(atob(value.base64),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:value.mime_type}));urls.add(url);if(showImage){if(!["image/png","image/jpeg"].includes(value.mime_type))throw new Error("Apri soltanto la cattura PNG o JPEG dichiarata.");const img=node("img");img.src=url;img.alt="Cattura del viewport riesaminato: "+item.name;img.style.maxWidth="100%";img.style.height="auto";row.append(img);}else{const link=node("a","Scarica "+value.name);link.href=url;link.download=value.name;row.append(link);link.click();}}
  async function open(workRef){await flush();api.leaveDraft();const generation=api.enter(),page=await call("vera_workspace_website_setup",{work_ref:workRef});if(!api.isCurrent(generation))return;const {nav,main}=api.shell();nav.append(button("← Siti dello studio",catalogue),button("← Clienti e incarichi",api.openWorks));const local={page,fields:structuredClone(page.fields),stamp:page.draft_revision,saved:JSON.stringify(page.fields),editable:page.can_write&&!page.draft_stale&&!page.pending_operations.length};context=local;api.setDirty(false);main.append(node("p",page.data.studio,"eyebrow"),node("h1","Riesame del sito"),node("p",page.data.intake.objective,"intro"),node("p",page.data.validation.valid?"La catena è corrente. Riesamina identità e affermazioni, comportamento responsive e destinazione separatamente.":"Il workflow segnala punti da completare o correggere. Una registrazione esistente non dimostra che il sito sia pronto.","notice"));readable(main,page.data.intake,"Identità, scopo, pagine e percorsi selezionati");readable(main,page.data.records,"Brief completo, piano delle fonti, file, valutazione responsive e decisioni conservate");readable(main,page.data.validation,"Verifica corrente e problemi effettivi");readable(main,page.data.packages,"Pacchetti esatti conservati");
    for(const item of page.data.artifacts){const row=node("section",undefined,"output");row.append(node("strong",item.name),button("Scarica questo file",()=>artifact(page,item,row)));if(item.name.startsWith("reviews/browser/")&&/\.(png|jpe?g)$/i.test(item.name))row.append(button("Mostra questa cattura",()=>artifact(page,item,row,true)));main.append(row);}
    if(page.pending_operations.length)main.append(node("p","Una scrittura precedente richiede recupero nel workflow specialistico. Conserva i record e non ripetere automaticamente il passaggio.","notice"));
    if(page.draft_stale){readable(main,local.fields,"Campi precedenti da confrontare");const confirm=confirmation(main,"Scarto soltanto questi campi privati dopo il confronto con il sito corrente"),clear=button("Scarta campi privati",async()=>{if(!confirm.checked)throw new Error("Conferma lo scarto dei soli campi privati.");await call("vera_workspace_website_draft_clear",{...scope(page),review_ticket:page.review_ticket,expected_draft_revision:local.stamp,confirmed:true});api.setDirty(false);await open(workRef);});confirm.disabled=clear.disabled=!page.can_write;main.append(clear);}
    else{input(main,local,"Passaggio da conservare","operation",operations);input(main,local,"Professionista che ha svolto il riesame","reviewer");input(main,local,"Ambito della decisione","scope",[["","Scegli l’ambito"],...page.data.required_review_scopes.map(x=>[x,x])]);input(main,local,"Decisione professionale","decision",[["","Da decidere"],["accepted","Accetta"],["returned","Restituisci"],["rejected","Rifiuta"]]);input(main,local,"Nota privata sul passaggio · non inclusa nel record professionale","note");local.confirm=confirmation(main,"Confermo questo passaggio sul sito e sui record correnti. Preparare un pacchetto o un collegamento non pubblica il sito");local.confirm.disabled=!local.editable;const save=button("Conserva campi incompleti",flush),execute=button("Esegui e conserva il passaggio",async()=>{await flush();if(!local.confirm.checked)throw new Error("Riesamina e conferma il passaggio corrente.");local.execution=local.execution||{...scope(page),review_ticket:page.review_ticket,expected_draft_revision:local.stamp,fields:structuredClone(local.fields),confirmed:true,idempotency_key:crypto.randomUUID()};await call("vera_workspace_website_execute",local.execution);api.setDirty(false);await open(workRef);say("Passaggio conservato dal workflow. Pubblicazione da eseguire separatamente sul percorso approvato.");},"primary");save.disabled=execute.disabled=!local.editable;main.append(save,execute);}
    privacy(main);
  }
  return Object.freeze({open,catalogue,flush,dispose,active:()=>Boolean(context),refresh:()=>context?open(context.page.work_ref):catalogue()});
}});
